### ISSUE TITLE
Time definitions

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#10]
IMO for some attributes it is dangerous to have them defined with strong dependency on the specific serialisation.

The typical case here are the time definitions, which refer to the internally handled timestamp:

https://github.com/phenopackets/phenopacket-schema/blob/2626158aaab70689dd5a46271a6321c2d49b0200/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L12

This does not give any indication to the user of how to I/O time.

Time formats are something [where a single, clean definition exists](https://www.iso.org/iso-8601-date-and-time-format.html), and which has been [well documented](https://ga4gh-metadata.github.io/formats.html) in the metadata schema. I am __strongly__ for defining time (poits, spans e.g. ages ...) as string/ISO8601, and leave the deparsing to the I/O handlers.

This is just one example where we _easy implementation_ NE _clear definition_.

**Comment by mbaudis** [comment]
Ping @julesjacobsen ...

**Comment by julesjacobsen** [comment]
Timestamp is very well documented and makes complete sense to use in a field such as 'created' or 'updated'. I can make the docs slightly more clear, but it's strongly typed such that you can't do something stupid like put a name in that field like you could with a string.

With date of birth it I agree its a bit over-specified an perhaps having an age field would be better.

```protobuf
// A Timestamp represents a point in time independent of any time zone
// or calendar, represented as seconds and fractions of seconds at
// nanosecond resolution in UTC Epoch time. It is encoded using the
// Proleptic Gregorian Calendar which extends the Gregorian calendar
// backwards to year one. It is encoded assuming all minutes are 60
// seconds long, i.e. leap seconds are "smeared" so that no leap second
// table is needed for interpretation. Range is from
// 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z.
// By restricting to that range, we ensure that we can convert to
// and from  RFC 3339 date strings.
// See [https://www.ietf.org/rfc/rfc3339.txt](https://www.ietf.org/rfc/rfc3339.txt).
//
// # Examples
//
// Example 1: Compute Timestamp from POSIX `time()`.
//
//     Timestamp timestamp;
//     timestamp.set_seconds(time(NULL));
//     timestamp.set_nanos(0);
//
// Example 2: Compute Timestamp from POSIX `gettimeofday()`.
//
//     struct timeval tv;
//     gettimeofday(&tv, NULL);
//
//     Timestamp timestamp;
//     timestamp.set_seconds(tv.tv_sec);
//     timestamp.set_nanos(tv.tv_usec * 1000);
//
// Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.
//
//     FILETIME ft;
//     GetSystemTimeAsFileTime(&ft);
//     UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;
//
//     // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
//     // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
//     Timestamp timestamp;
//     timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
//     timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));
//
// Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.
//
//     long millis = System.currentTimeMillis();
//
//     Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
//         .setNanos((int) ((millis % 1000) * 1000000)).build();
//
//
// Example 5: Compute Timestamp from current time in Python.
//
//     timestamp = Timestamp()
//     timestamp.GetCurrentTime()
//
// # JSON Mapping
//
// In JSON format, the Timestamp type is encoded as a string in the
// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
// format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
// where {year} is always expressed using four digits while {month}, {day},
// {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
// seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
// are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
// is required, though only UTC (as indicated by "Z") is presently supported.
//
// For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
// 01:30 UTC on January 15, 2017.
//
// In JavaScript, one can convert a Date object to this format using the
// standard [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString]
// method. In Python, a standard `datetime.datetime` object can be converted
// to this format using [`strftime`](https://docs.python.org/2/library/time.html#time.strftime)
// with the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one
// can use the Joda Time's [`ISODateTimeFormat.dateTime()`](
// http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime--)
// to obtain a formatter capable of generating timestamps in this format.
//
//
message Timestamp {

  // Represents seconds of UTC time since Unix epoch
  // 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
  // 9999-12-31T23:59:59Z inclusive.
  int64 seconds = 1;

  // Non-negative fractions of a second at nanosecond resolution. Negative
  // second values with fractions must still have non-negative nanos values
  // that count forward in time. Must be from 0 to 999,999,999
  // inclusive.
  int32 nanos = 2;
}
```

**Comment by mellybelly** [comment]
+1 for ISO as a type, seems more computable? what is the argument for the string flavor? is it a display issue or did i miss something?

**Comment by buske** [comment]
It seems like the other design choices within phenopacket favor human-readability, simplicity of interpretation, and ease of use, and leave it to software to do the heavy lifting. I think the ISO string does this better than a structured object of seconds/nanos. Most systems offer date-time validation of strings, so the strong typing doesn't seem like a huge win. @julesjacobsen Just because it's an int64 doesn't mean it's valid (as your comments say) :)

**Comment by julesjacobsen** [comment]
I'm going to have to respectfully completely disagree with you here. We all agree that we want to specify standardised timestamps? In both Protobuf (above) and [JSON Schema](https://spacetelescope.github.io/understanding-json-schema/reference/string.html ) there is provision for a timestamp/data-time, although JSON Schema chooses to encode this as a string with a data-time format, whereas Protobuf went more strongly typed.

Both of these specs refer to the [RFC3339](http://tools.ietf.org/html/rfc3339) as being the standard used (read this, it's short and informative).

From the perspective of developer receiving a phenopacket in Java the transformation from protobuf to Java is trivially simple: 

```java
private Instant toInstant(Timestamp timestamp) {
    return Instant.ofEpochSecond(timestamp.getSeconds());
}
```

From the perspective of someone manually writing a phenopacket with a created/updated timestamp the JSON/YAML representation is simply a string in a standard format. e.g. ```1985-04-12T23:20:50.52Z```.

RFC3339 is both human readable and computable according to universally supported internet standards and supported out of the box in any relevant computer language. I think we should use it.

**Comment by julesjacobsen** [comment]
As for age/date of birth, sure we can use a string if you like, but there is an Age type which fits with the FHIR interoperabliity.

@buske you can always make a deliberate mess of things if you want to but using a type instead of something utterly generic like a string makes this harder to do.

Lastly I know of places where they have encoded time as  strings and it is a nightmare for them.

**Comment by julesjacobsen** [comment]
I've updated the documentation to make it clear what is expected as input for a timestamp field. e.g.

```
    // ISO8601 UTC timestamp at which this Biosample record was updated, in
    // the format YYYY-MM-DDTHH:MM:SS.SSSZ e.g 2007-12-03T10:15:30.00Z
```

I hope this clears up any ambiguity. I've also update individual to have both data_of_birth and age_at_collection fields as the DOB wasn't always made available.

**Comment by mbaudis** [comment]
Good - I think making clear what the representation of the value is supposed to be is already much better. However, ASAP we should provide attribute documentation outside of the proto implementation.

Another problem is [Period](https://github.com/phenopackets/phenopacket-schema/blob/2626158aaab70689dd5a46271a6321c2d49b0200/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L400): Time intervals are a single value in ISO8601; this can be defined as ISO string, and you don't even need the `Period` object.

**Comment by pnrobinson** [comment]
@mbaudis @julesjacobsen Is this issue closable? 
Michael, I am not sure I understand the objection to a period -- sometimes we might have the information that a feature had onset between somebody's 22nd and 25th birthday for instance?

**Comment by mbaudis** [comment]
@pnrobinson These are 2 things: start + end only works for something like your example if you *also* have the DOB. 

 * between dates
    - (`start` _AND_ `end`) OR ISO8601 period
*  between ages
    - (`start_age` _AND_ `end_age`) _OR_ ([{`start` _AND_ `end`} OR ISO8601 period] _AND_ `date_of_birth`) 
    - this would also be an alternative to the use of a class for a certain age group - see parallel discussion in https://github.com/phenopackets/phenopacket-schema/issues/30

You can close this, I guess, since t5he discussions are carried on elsewhere ...

**Comment by julesjacobsen** [comment]
This seems to have become a bit side-tracked. I don't understand the issue with Period - its a duration between two points in time. Unless you mean by using a single value you mean that this single value is the period? My preference is to follow [FHIR definitions](http://build.fhir.org/datatypes.html#instant) as this is what we are attempting to be compatible with:

```
FHIR Name | Value Domain | XML Representation | JSON representation
----------- |--------------- |--------------------- | ---------------------
instant | An instant in time in the format YYYY-MM-DDThh:mm:ss.sss+zz:zz  (e.g. 2015-02-07T13:28:17.239+02:00 or 2017-01-01T00:00:00Z). The time  SHALL specified at least to the second and SHALL include a time zone.  	   Note: This is intended for when precisely observed times are  required (typically system logs etc.), and not human-reported times -  for those, use date or dateTime (which can be as precise as instant, but is not required to be). instant is a more constrained dateTime | xs:dateTime | A JSON string - an xs:dateTime
  | Note: This type is for system times, not human times (see date and dateTime below).
  | Regex: ([0-9]([0-9]([0-9][1-9]\|[1-9]0)\|[1-9]00)\|[1-9]000)-(0[1-9]\|1[0-2])-(0[1-9]\|[1-2][0-9]\|3[0-1])T([01][0-9]\|2[0-3]):[0-5][0-9]:([0-5][0-9]\|60)(\.[0-9]+)?(Z\|(\+\|-)((0[0-9]\|1[0-3]):[0-5][0-9]\|14:00))
date | A date, or partial date (e.g. just year or year + month) as used  in human communication. The format is YYYY, YYYY-MM, or YYYY-MM-DD, e.g.  2018, 1973-06, or 1905-08-23. There SHALL be no time zone. Dates SHALL be valid dates | union of xs:date, xs:gYearMonth, xs:gYear | A JSON string - a union of xs:date, xs:gYearMonth, xs:gYear
  | Regex: ([0-9]([0-9]([0-9][1-9]\|[1-9]0)\|[1-9]00)\|[1-9]000)(-(0[1-9]\|1[0-2])(-(0[1-9]\|[1-2][0-9]\|3[0-1]))?)?
dateTime | A date, date-time or partial date (e.g. just year or year +  month) as used in human communication. The format is YYYY, YYYY-MM,  YYYY-MM-DD or YYYY-MM-DDThh:mm:ss+zz:zz, e.g. 2018, 1973-06, 1905-08-23,  2015-02-07T13:28:17-05:00 or 2017-01-01T00:00:00.000Z.     If hours and minutes are specified, a time zone SHALL be populated.  Seconds must be provided due to schema type constraints but may be  zero-filled and may be ignored at receiver discretion. Dates SHALL be  valid dates. The time "24:00" is not allowed. Leap Seconds are allowed - see below | union of xs:dateTime, xs:date, xs:gYearMonth, xs:gYear | A JSON string - a union of xs:dateTime, xs:date, xs:gYearMonth, xs:gYear
  | Regex: ([0-9]([0-9]([0-9][1-9]\|[1-9]0)\|[1-9]00)\|[1-9]000)(-(0[1-9]\|1[0-2])(-(0[1-9]\|[1-2][0-9]\|3[0-1])(T([01][0-9]\|2[0-3]):[0-5][0-9]:([0-5][0-9]\|60)(\.[0-9]+)?(Z\|(\+\|-)((0[0-9]\|1[0-3]):[0-5][0-9]\|14:00)))?)?)?
time | A time during the day, in the format hh:mm:ss. There is no date  specified. Seconds must be provided due to schema type constraints but  may be zero-filled and may be ignored at receiver discretion.     The time "24:00" SHALL NOT be used. A time zone SHALL NOT be present. Times can be converted to a Duration since midnight. | xs:time | A JSON string - an xs:time
  | Regex: ([01][0-9]\|2[0-3]):[0-5][0-9]:([0-5][0-9]\|60)(\.[0-9]+)?
```

**Comment by mbaudis** [comment]
@julesjacobsen But an age range („between ages 12 and 16“) isn‘t a period between time points. And this is the most frequent information you have to work with (outside EHRs): A single age or an age range.
No dates.

**Comment by julesjacobsen** [comment]
references:
https://github.com/ga4gh-schemablocks/blocks/issues/8
issue #30

**Comment by julesjacobsen** [comment]
See commit: a401e948074198a27da850752b6b3803d60c4e74
