### ISSUE TITLE
Biosample -- can it be independent?

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#104]
Currently, the Biosample does not have a metadata element. This is OK only if we mandate that a Biosample can only exist within a Phenopacket.  I think this is OK, but @mellybelly @cmungall are there any use cases that would speak against this?

**Comment by cmungall** [comment]
I am not familiar with the Biosample phenopacket use cases but it seems low cost to add an optional reference to a metadata message to Biosample

**Comment by pnrobinson** [comment]
After some discussion, it seems the best way forward would actually be to recommend that a Biosample be included in a Phenopacket. Downstream software does not need to enforce this, although it would be sensible. We will discuss the entire package in Hinxton, I think it is hard to do so in isolation.
