### ISSUE TITLE
Individual insonsistency

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#105]
datasetId should be dataaset_id
dateOfBirth should be data_of_birth
karyotypicSex should be karyotypic_sex
similarly, 
ageOfIndividualAtCollection
histologicalDiagnosis
diagnosticMarkers
isControlSample
sampledTissue
htsFiles
metaData

or do we want to go stooped-camel case?

**Comment by julesjacobsen** [comment]
Sorry, Peter, I don't understand here you're looking. In protobuf messages are named similarly to Java classes, variables use Python snake_case. All of these are named appropriately in the schema. 

The fun thing about protobuf is that it will generate canonical language implementations for the language in question. So Java looks like Java, Python becomes idiomatic Python...

**Comment by pnrobinson** [comment]
my dumb :-0,. c;losing
