### ISSUE TITLE
cancer rtd example comments

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-schema#106]
Too lazy to make a PR...

overall looks great! minor cmts follow

I think this is an anti-pattern:

`  "description": ""`

should use CURIEs:

`        "id": "UBERON_0001256",`

**Comment by pnrobinson** [comment]
@julesjacobsen 

perhaps we should rename "id" to sample_id  here? I do not thin kthis can be a CURIE, it is meant to identify a sample with some identifier.
```
"id": "sample1",
"datasetId": "",
"individualId": "patient1",
"description": ""
```

As to description, it is hard to completely abandon the one last field for free text...

**Comment by cmungall** [comment]
I just meant the field should be null if there is no description, rather than an empty string

**Comment by pnrobinson** [comment]
@julesjacobsen  -- I agree with Chris and I do not 100% understand how to best format this -- the JSON printer either seems to mess things up or to print all of the default fields. Is there some way of suppresing the empty fields in the output?

**Comment by julesjacobsen** [comment]
Yes. The default is to not output empty fields:

```java
JsonFormat.printer().print(phenoPacket);
```
outputs:
```json
"id": "sample1",
"individualId": "patient1",
```

**Comment by julesjacobsen** [comment]
Is this still an issue? I note that the empty fields are still present - do you want to simply remove them from the examples? This seems like the clearest thing to do.

**Comment by pnrobinson** [comment]
We have now thoroughly revised the documentation and this issue has become stale, closing.
