### ISSUE TITLE
Rename Phenotype.negated to Phenotype.absent

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#107]
I don't think that the term `negated` is particularly informative as to how it should be used. Would it not be more obvious to use the term `absent` or even `confirmed_absent`?

**Comment by pnrobinson** [comment]
I suspect most physicians would more readily recognize the word "excluded" in this context.

**Comment by julesjacobsen** [comment]
"Excluded" seems a bit specialised. Let me try a quick office survey...

**Comment by julesjacobsen** [comment]
The office unanimously votes 'absent'. I think it would be better to use a plain language term as this isn't necessarily going to be used directly by clinicians or ontologists.

**Comment by pnrobinson** [comment]
The only other person who is awake here is Sherlock the dog, so I cannot perform a representative survey...but absent seems fine and is definitely better than negated.

**Comment by julesjacobsen** [comment]
One woof for yes, two for no?

**Comment by cmungall** [comment]
What if the phenotype is absent X? Then it's absent absent X?

Is there not a danger people will read absent as being the *physical structure* not present? E.g. abnormal lung morphology + absent = absent lung?

Also is the schema read by physicians or bioinformaticians? I think a logical term such as negated, not, is less prone to misuse

**Comment by julesjacobsen** [comment]
So perhaps the 

```proto
message Phenotype {
...
    // The primary ontology class which describes the phenotype. For example "HP:0001363"  "Craniosynostosis"
    // FHIR mapping: Condition.identifier
    OntologyClass type = 2;
    
    // Flag to indicate whether the phenotype was observed or not. Default is 'false', in other words the phenotype was
    // observed. Therefore it is only required in cases to indicate that the phenotype was looked for, but found to be
    // absent. 
    // More formally, this modifier indicates the logical negation of the OntologyClass used in the 'type' field.
    // *CAUTION* It is imperative to check this field.
    bool negated= 3;
...
```
