### ISSUE TITLE
Variant.genotype or Variant.zygosity

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#108]
Also, regarding the genotype field spec - i would consider renaming this `zygosity` if the point here is simply to capture a GENO term describing the zygosity of the indicated allele. The underlying issue here is that indicating allele zygosity suggests what the genotype of the indicated allele might be, but doesn't definitively describe the genotype in all cases.  For example, consider compound genotype comprised of two different variants at the same location, such as `fgf8a<ti282a>/fgf8a<x15>`).   Annotating with the GENO term `compound heterozygous` in this case doesn't tell you the actual genotype because you don't know what the other variant allele is.   
  
If what you really want here is to explicitly and unambiguously represent the genotype at a particular locus, then this may require modeling a proper Genotype message, instead of just a GENO zygosity term.  I am happy to make suggestions based on GENO modeling if that is the case.  But if all you really want is to know the zygosity of the indicated allele, then I would simply rename the field 'zygosity' instead of 'genotype'.

_Originally posted by @mbrush in https://github.com/phenopackets/phenopacket-schema/pull/90#issuecomment-477748780_

**Comment by pnrobinson** [comment]
I agree that naming this field zygosity is a good idea, noting that genotype has many meaning including zygosity of an allele so that the current name is not wrong, but it is easier to misinterpret than zygosity.

**Comment by julesjacobsen** [comment]
OK, I'm in the process of adding the following test example:

```java
package org.phenopackets.schema.v1.core;

import org.junit.jupiter.api.Test;
import org.phenopackets.schema.v1.Phenopacket;

public class VariantTest {

    private static final OntologyClass HOM = OntologyClass.newBuilder().setId("GENO:").setLabel("").build();
    private static final OntologyClass HET = OntologyClass.newBuilder().setId("GENO:").setLabel("").build();
    private static final VcfAllele FGFR2_PATH_ALLELE_1 = VcfAllele.newBuilder()
            .setGenomeAssembly("GRCh37")
            .setChr("10")
            .setPos(123256215)
            .setRef("T")
            .setAlt("G")
            .build();

    private static final VcfAllele FGFR2_LIKELY_PATH_ALLELE_2 = VcfAllele.newBuilder()
            .setGenomeAssembly("GRCh37")
            .setChr("10")
            .setPos(123247569)
            .setRef("T")
            .setAlt("C")
            .build();

    @Test
    void homozygousVariant() {
        Variant hom = Variant.newBuilder()
                .setVcfAllele(FGFR2_PATH_ALLELE_1)
                .setGenotype(HOM)
                .build();

        Phenopacket phenopacket = Phenopacket.newBuilder()
                .addVariants(hom)
                .build();
    }

    @Test
    void heterozygousVariant() {

        Variant het = Variant.newBuilder()
                .setVcfAllele(FGFR2_PATH_ALLELE_1)
                .setGenotype(HET)
                .build();

        Phenopacket phenopacket = Phenopacket.newBuilder()
                .addVariants(het)
                .build();
    }

    @Test
    void compoundHeterozygousVariant() {

        Variant het1 = Variant.newBuilder()
                .setVcfAllele(FGFR2_PATH_ALLELE_1)
                .setGenotype(HET)
                .build();

        Variant het2 = Variant.newBuilder()
                .setVcfAllele(FGFR2_LIKELY_PATH_ALLELE_2)
                .setGenotype(HET)
                .build();

        Phenopacket phenopacket = Phenopacket.newBuilder()
                .addVariants(het1)
                .addVariants(het2)
                .build();
    }
}
```
