### ISSUE TITLE
wrong reference

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#109]
Analysis of genetic inheritance in a family quartet by whole-genome sequencing is not the correct reference for the rare disease example. It is actually " kindred 1" in this publication: https://www.nature.com/articles/ng.499

I will fix this and add some more details.

**Comment by pnrobinson** [comment]
@julesjacobsen is this the correct way to refer to PubMed?
```
(...)
 {
      "id": "pubmed",
      "name": "PubMed",
      "namespacePrefix": "PMID",
      "iriPrefix": "https://www.ncbi.nlm.nih.gov/pubmed/"
    }],
    "externalReferences": [{
      "id": "PMID:19915526",
      "description": "Kindred 1 in Ng SB et al. Exome sequencing identifies the cause of a mendelian disorder. Nat Genet. 2010;42(1):30-5."
    }]
```

**Comment by pnrobinson** [comment]
Looking more closely at this example, I would vote that we substitute a different example, because the paper does not clearly identify the 9 year old boy in Figure 1 as kindred 1A (or not) and that fact that there is a second, independent Mendelian disease here unnecessarily complicates the case. 
I will find a better example? @julesjacobsen

**Comment by julesjacobsen** [comment]
Perhaps I chose the wrong publication?  You said that it came from https://www.nature.com/articles/nrg2783.

**Comment by pnrobinson** [comment]
Your reference is to a review, not to the original publication. The review cites the original pub. Still, I would propose we choose another example, the phenotype data in this publication are very hard to interpret and we would basically have to make the data up. I will find something in one of our curated cases, OK?

**Comment by julesjacobsen** [comment]
> Your reference is to a review, not to the original publication. The review cites the original pub.

Yes, this is why I used what I thought was the original publication linked to by the DOI. But that's irrelevant now. By all means find and use whatever case you think most appropriate. The multi-diagnosis was somewhat complicated, but was a good example of using absent phenotype terms. If you can find some way of including these it would be good.

**Comment by julesjacobsen** [comment]
Although I'd ask you leave the existing RareDiseaseFamilyExample as this was one of the Toronto Examples and I'd like to leave these intact. Perhaps resurrect the Spherocytosis example you had?

**Comment by pnrobinson** [comment]
OK. I will rename the class MillerSyndromeExample, though, because it is actually not a great example and people should not think it is the primary one.

**Comment by julesjacobsen** [comment]
I think this has now morphed into BethlemMyopathyExample:
https://github.com/phenopackets/phenopacket-schema/blob/master/src/test/java/org/phenopackets/schema/v1/examples/BethlemMyopathyExample.java
