### ISSUE TITLE
Remove free text Phenotype.description

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#110]
I can't remember the original decision to put this in here, but this seems ripe for abuse and undermining the entire rationale for having structured fields.
```proto
message Phenotype {
    // Free-text description of the phenotype. Note this is not a acceptable place to document/describe the phenotype -
    // the type and onset etc... fields should be used for this purpose.
    string description = 1;
...
```
@pnrobinson I think you made a similar reference to this somewhere else?

Vote now!

**Comment by cmungall** [comment]
Channeling @dosumis, we should use ontologies but not everything can be boiled down to an ontology. Having optional free text is often a good idea. Of course we have to guard against people using it instead of a rich HPO term

**Comment by julesjacobsen** [comment]
OK, easy change there.

**Comment by pnrobinson** [comment]
We could add one free text field to the Phenopacket instead?
