### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#112]
I have the impression that it is difficult to compile the two protobuf files with protoc for C++ because one of the files imports the other with the complete path starting from org...I cannot figure out how to compile the files. I am wondering if it would be better to combine phenopackets.proto and core/base.proto into a single file? I might be doing something dumb.

**Comment by pnrobinson** [comment]
By combining the two files into one (and adjusting the paths within the file) I am able to compile the code in C++. @julesjacobsen can we take a look at this and consider whether it is worthwhile to just use one file for the phenopackets definition? I suspect that hard coding the paths (e.g., `` org.phenopackets.schema.v1.core.Individual subject = 2;`` is something that is more or less normal for Java but does not seem to be very natural for C++, and this might be what is tripping things up.

**Comment by pnrobinson** [comment]
Here is a demo in C++
I needed to combine the two input files into a single file and adjust some of the paths.
But it reads in a JSON formatted phenopacket and outputs some of the fields. It is relatively easy to figure out the C++ API, which is noticably fast...

https://github.com/pnrobinson/phenopacketpp

**Comment by julesjacobsen** [comment]
Cool stuff @pnrobinson! What are you referring to with the hard-coding of paths? Is this in the C++ / Java implementation?

**Comment by julesjacobsen** [comment]
You could try the new [Graal](https://www.graalvm.org/) [AOT native code compilation](https://www.graalvm.org/docs/reference-manual/aot-compilation/) feature for Java code and compare the performance of that. C++ doesn't have the overhead of starting up the JVM so small CLI applications like this will always trounce a Java implementation.

**Comment by pnrobinson** [comment]
With the current implementation, maven generated two header and two source c++ files.(target/generated-sources/protobuf/cpp/org/phenopackets/schema/v1...
phenopackets.pb.h
phenopackets.pb.cpp
core/base.pb.h
core/base.pb.cc

And the path to base.pb.* is hard coded in the phenopackets.pb.h/cc in a way that the compiler does not find. 

#include "org/phenopackets/schema/v1/core/base.pb.h"

This is fine in Java but in C++ it means that the compiler is looking essentially for this
org/phenopackets/schema/v1/org/phenopackets/schema/v1/base.pb.h

I tried various ways of including this with -I etc in the Makefile but was not able to get this to run. My best guess is that Google's C++ generator does not expect to see protobuf being put into a Java-like "class hierarchy".

**Comment by julesjacobsen** [comment]
Ah, this might be an issue with the protobuf-maven-plugin not being correctly configured for C++ - check out the docs for [C++ compilation](https://www.xolstice.org/protobuf-maven-plugin/compile-cpp-mojo.html)

**Comment by pnrobinson** [comment]
possibly <protoSourceRoot> I will try.

**Comment by pnrobinson** [comment]
sorry, currently we do not have this plugin? Should we add it? Right now c++ is a goal of protobuf-maven-plugin only

**Comment by julesjacobsen** [comment]
We're using this plugin already:

https://github.com/phenopackets/phenopacket-schema/blob/d60c819ec90d822cf299d8a8736f3854bf48eaae/pom.xml#L122-L141

**Comment by julesjacobsen** [comment]
@pnrobinson  I'm looking at a C++ 11 project using protobuf where the data is laid-out in a similar way to what we have:

https://github.com/envoyproxy/envoy/blob/master/test/config/utility.h

They have the same include statements e.g.

```c++
#include <chrono>
#include <functional>
#include <string>
#include <vector>


#include "envoy/api/api.h"
#include "envoy/api/v2/cds.pb.h"
#include "envoy/api/v2/core/base.pb.h"
#include "envoy/api/v2/core/protocol.pb.h"
#include "envoy/api/v2/eds.pb.h"
#include "envoy/api/v2/route/route.pb.h"
#include "envoy/config/bootstrap/v2/bootstrap.pb.h"
#include "envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.h"
#include "envoy/http/codes.h"


#include "common/network/address_impl.h"
#include "common/protobuf/protobuf.h"


#include "test/integration/server_stats.h"
```

Notice how the protobuf source for `"envoy/api/v2/cds.pb.h"` is at https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/cds.proto which is nested in a folder hierarchy.

Can you use these examples to figure out what is going wrong at our end?

**Comment by pnrobinson** [comment]
This repo is using a build system I am not familiar with. Even if this is possible, I think we want phenopackets C++ integration to be relatively straightforward, so that one can do it with a plain Makefile or CMake. I am hoping that we can somehow tweak the maven file to enable this but it does not seem to be simple to me right now. Perhaps we can find some others to cogitate about this.

**Comment by julesjacobsen** [comment]
doing something like this
```shell
$ cd ~/projects
$ git clone https://github.com/phenopackets/phenopacket-schema.git
$ PFX_PROTO=~/projects/phenopacket-schema/src/main/proto
$ bin/protoc --proto_path=$PFX_PROTO --cpp_out=. $PFX_PROTO/org/phenopackets/schema/v1/phenopackets.proto  $PFX_PROTO/org/phenopackets/schema/v1/core/base.proto
$ ls -R  org/phenopackets/schema/v1/
org/phenopackets/schema/v1/:
core  phenopackets.pb.cc  phenopackets.pb.h

org/phenopackets/schema/v1/core:
base.pb.cc  base.pb.h
```

Which produces the attached output. How do you usually import external libraries in a C++ project?

[phenopacket_schema_cpp.zip](https://github.com/phenopackets/phenopacket-schema/files/3134636/phenopacket_schema_cpp.zip)

**Comment by pnrobinson** [comment]
Can you compile both files on your side? Something like the following

g++  -Wall -g -O0 --std=c++17 $(INC) -pthread  -c  phenopackets.pb.cc

**Comment by julesjacobsen** [comment]
Will check. Is this some elaborate ruse to get me to start using C++?

**Comment by pnrobinson** [comment]
it is hard to pull the wool over your eyes :-0

**Comment by julesjacobsen** [comment]
I *knew* it.

```shell
$ g++ -Wall -g -O0 --std=c++17 $(INC) -pthread -c org/phenopackets/schema/v1/phenopackets.pb.cc
INC: command not found
org/phenopackets/schema/v1/phenopackets.pb.cc:4:10: fatal error: org/phenopackets/schema/v1/phenopackets.pb.h: No such file or directory
 #include "org/phenopackets/schema/v1/phenopackets.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by pnrobinson** [comment]
INC is a Makefile (or shell) variable that tells g++ where to look for files to include.
I got exactly the same error message as you did.
However, since the other project found some way around this, I am guessing there is a solution...C++ builds are insanely complicated compared to Java.

**Comment by julesjacobsen** [comment]
Shouldn't `$(INC)` be `-I $(INC)`?

Still I agree why are these things so complicated? Surely there must be a standard build tool like maven or gradle for C++? I note there is a [gradle C++ build tool](https://guides.gradle.org/building-cpp-executables/), but maybe this is better being [built as a C++ library](https://guides.gradle.org/building-cpp-libraries/)?

**Comment by pnrobinson** [comment]
There are lots of tools for C++ -- automake, CMake, plain make etc. The Java tools tend to be easier to use though.

**Comment by julesjacobsen** [comment]
@pnrobinson are you happy for me to close this? I think there is at least one prior example (the [envoyproxy dataplane-api](https://github.com/envoyproxy/data-plane-api)) of a large-scale C++ project, at least in part implemented in protobuf and the directory layout and headers all replicate what we have.

**Comment by pnrobinson** [comment]
@julesjacobsen I think we need to be able to compile these classes before we close this issue. The repo you found is not easy to replicate. We will use C++ users, I think, if we cannot provide a clear path for how to use this.

**Comment by pnrobinson** [comment]
When I try this, I cannot compile
```
<configuration>
               <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
        <protoSourceRoot>org/phenopackets/schema/v1</protoSourceRoot>
</configuration>
```

**Comment by julesjacobsen** [comment]
Remove the `<protoSourceRoot>org/phenopackets/schema/v1</protoSourceRoot>`

**Comment by pnrobinson** [comment]
But we were saying that we could somehow solve the compilation problem by changing the root element -- I meant to say that I cannot figure this out. Have you been able to get the C++ code compiled somehow? Currently, the only thing I can get to work is this https://github.com/pnrobinson/phenopacketpp
with a different directory structure and a single proto file

**Comment by julesjacobsen** [comment]
I'm trying this out in VisualStudio and have a certain amount of success.

I've simply got the main.cpp followed by the complete directory structure of  `org/phenopackets/schema/v1/...` created from the maven build.

```c++
#include <google/protobuf/message.h>
#include <google/protobuf/util/json_util.h>

#include "org/phenopackets/schema/v1/phenopackets.pb.h"
```
The  `google/protobuf` includes are not found, but the `org/phenopackets...` is. Commenting out the `google/protobuf` and compiling results in errors being thrown for both `base.pb.h` and `phenopackets.pb.h` not having the requisite protobuf lib available. I freely admit to having no idea about how it is going about  compiling and linking, but it not throwing errors about the paths or being unable to find the relevant headers that we saw when trying to compile by hand. Consequently I don't think this is a problem, other than we're having issues ourselves!

https://stackoverflow.com/questions/11447950/integrate-google-protocol-buffers-proto-files-to-visual-c-2010
and
https://stackoverflow.com/questions/34738616/using-google-protobuf-with-libraries-in-cmake-on-windows-visual-studio-2013

might help, but I really need to do something else!

**Comment by pnrobinson** [comment]
Duplicate with https://github.com/phenopackets/phenopacket-schema/issues/150, the issue now seems to be fixed.
