### ISSUE TITLE
Mouse allele: superscript separation

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#113]
The superscripted portion of the allele symbol should NEVER be listed or displayed separately from the genetic marker according to the IMNC.  By doing this, you have rendered your “allele code” non-unique and non-traceable, and does not conform to nomenclature guidelines. For example, the ‘tm1Mak’ superscript may refer to one of 64 different alleles.  The tm1a(EUCOMM)Wtsi superscript refers to thousands of alleles.  Why is the requirement to break apart the allele nomenclature symbol, other than the stated difficulty  to distinguish superscripts. Presenting only part of the allele symbol is unacceptable.

**Comment by pnrobinson** [comment]
@cindyJax  both elements are required, and thus if the validation software works correctly, allele_code and gene will never be separated. Is there a better way of doing this?
https://phenopackets-schema.readthedocs.io/en/latest/variant.html

**Comment by pnrobinson** [comment]
As mentioned, after discussions in Hinxton it appears to be better to defer to the VMC group for variants that today cannot be represented in standards such as VCF. Closing.
