### ISSUE TITLE
 Mouse allele: use MGI allele ID

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#114]
The mouse allele ID should preferably be an MGI ID, not “an arbitrary identifier”.  ID must be required, not recommended.

**Comment by pnrobinson** [comment]
In this case, the Phenopackets standard intends to be for a broad range of use cases, and so we do not want to enforce a specific type of identifier for fields such as this. If MGI were to adopt phenopackets, then MGI would have to check that submitters were using proper MGI ids in this field (and similar comments apply for other databases that use phenopackets).
