### ISSUE TITLE
Mouse allele: gene/marker ID

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#115]
The gene should be rendered as a stable marker ID (preferably MGI ID), not a text string.  Gene symbols can change. IDs can be merged or withdrawn. Who is responsible to keep these IDs/text strings current? The originating database?  Is there versioning of this section when nomenclature changes?

**Comment by pnrobinson** [comment]
The problem that is being addressed here is one that affects any database and the Phenopacket, as a standard, is not the right place to enforce policies for keeping identifiers up to date -- databases and software etc need to implement that, and each database that uses Phenopackets will likely have differing needs.
