### ISSUE TITLE
Mouse allele: alleles with no superscript

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#116]
How are mouse allele symbols with **no** superscript portion rendered in this model?  The ‘allele code’, or superscript portion, is required in your documentation.
a.	ex: a (MGI:1855937) [allele of gene ID MGI:87853]
b.	ex2: T (MGI:1856184) [allele of gene ID MGI:98472]
c.	ex3: all of the transgenes, deletion regions, gene traps in intergenic regions etc. (Gt(OST75692)Lex (MGI:3521912)) 
d.	ex4: heritable phenotypic markers  -7a6ex (MGI:3578177)

**Comment by pnrobinson** [comment]
As discussed, it was perhaps overambitious to want to model such complicated alleles within the phenopacket itself, and this will require coordination with other GA4GH standards including especially VMC. The phenopacket will implement the VMC model as soon as that is released, and if the model groups would like to adopt that then it would work wioth phenopackets. We cannot implement this in our current scheme, and so I am closing this issue.
