### ISSUE TITLE
Mouse allele: no "gene" 

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#117]
How are allele symbols with no ‘gene’ rendered in this model? Or by ‘gene’ do you mean any mouse genomic marker with an ID?  How do you define “gene”. This needs to be clarified. We have many alleles of markers that are not traditional protein or RNA coding genes
a.	ex: Igs15<tm1.1Ddu> (MGI:5523224)
b.	ex2: Cigs2<tm1.1Anse> (MGI:5313809)

**Comment by pnrobinson** [comment]
As mentioned, the way to go after the discussions in Hinxton seems to be that we should work with VMC to represent alleles such as this in the GA4GH variant representation schema if desired. We are not able to model this in our current scheme.
