### ISSUE TITLE
Mouse allele: allele affects more than one 'gene'

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#118]
How will alleles/mutations with more than one affected gene (or genomic marker) be modeled? 
a.	ex: Del(2Hoxd11-Hoxd13)29Ddu (MGI:1857661) affects 4 genes, Hoxd10, Hoxd11, Hoxd12, Hoxd13
b.	ex2: Bglap/Bglap2<tm3.1Kry> (MGI:4949088) affects both Bglap and Bglap2
c.	ex3: Down’s syndrome model,  Dp(16Cbr1-Fam3b)1Rhr affects 68 genes.

**Comment by pnrobinson** [comment]
Thanks! As mentioned, after discussion in Hinxton, it appears better to defer to the VMC group for standards scuh as this, which go beyond what can be achieved within the phenopacket.
