### ISSUE TITLE
Mouse allele: alleles with more than one variant

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#119]
How will alleles with more than one variant within the allele be modeled? There is an apparent confounding of the terms variant element, variant and allele that needs to be clarified.
a.	ex: Pdgfra<tm7Sor> (MGI:2656148) has 5 noncontiguous engineered variants within the allele.  
b.	ex2: Foxe3<dyl> (MGI:1856851) has two noncontiguous variants (point mutations), both of which are responsible in combination for the mutant phenotype.

**Comment by julesjacobsen** [comment]
As you say, there appears to be a clash in terminologies here. We aim to adopt the [VMC](https://github.com/ga4gh/vmc) data model, whenever that is ready.

**Comment by pnrobinson** [comment]
After discussions at Hinxton, we have decided to shelve this option until better standards are available for representing this kind of variant. VMC will be able to represent this. It will still be some work to represent the MGI data using the VMC model, but this is out of scope for phenopackets.
