### ISSUE TITLE
Mouse allele: variants in different inbred strains

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#120]
Where should we specify the mouse inbred strain for variants? There are now multiple reference genomes in mouse. We have variants in every MGP strain.

**Comment by cindyJax** [comment]
Examples: Cftr<tm1Eur> (MGI:1857899), Cftr<tm1Kth> (MGI:1857151), Cftr<tm2Cam> (MGI:1857896) all carry engineered versions of the p.F508del mutation similar to human variants, but these were all created in different genomic contexts (i.e. strain backgrounds).  How do we designate the genomic context (mouse strain?)

**Comment by pnrobinson** [comment]
Thanks! As mentioned, after discussion in Hinxton, it appears better to defer to the VMC group for standards scuh as this, which go beyond what can be achieved within the phenopacket.
