### ISSUE TITLE
Mouse allele: transgenes

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#121]
We need to consider how transgenes in mouse will be handled, in particular, those expressing non-mouse genes (e.g human variants). These include important disease models that we have to fit into the schema.

**Comment by pnrobinson** [comment]
Thanks! As mentioned, after discussion in Hinxton, it appears better to defer to the VMC group for standards scuh as this, which go beyond what can be achieved within the phenopacket.
