### ISSUE TITLE
Murine Disease Model: section label

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#122]
Why is this labeled “Murine disease model”?  Most of these mouse phenotype packets will not be describing disease models. Or even a ‘model’.  Better terminology is required… Perhaps “Mouse Phenotype Profile” ? Or more extensibly to "Rodent phenotype profile"?

**Comment by pnrobinson** [comment]
Do you mean this page? https://phenopackets-schema.readthedocs.io/en/latest/animal-model-example.html
It is an example, but I agree we should say that it could be a Mouse/Rodent Phenotype Profile.

**Comment by pnrobinson** [comment]
The schema itself does not have anything like  “Murine disease model”, that was intended merely for the example.
