### ISSUE TITLE
Murine Disease Model: disease annotation?

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#123]
Where is the slot to add the human disease model annotation in this particular specification, when appropriate? Or is that not being considered yet? We also require the ability to negate disease annotations. There exist many examples in mice in which a specific mutation made did **not** phenocopy a similar pathogenic variant in humans.

**Comment by pnrobinson** [comment]
@julesjacobsen  This will be relevant for the IMPC model, but a simple solution would be to use the disease field with a human disease identifier and to provide MP terms to describe the model. The user could then decide computationally whether the model is a faithful model of the human disease or not.

**Comment by pnrobinson** [comment]
We have decided to not include model organisms in this first release of phenopackets, but instead to gather requirements for a potential future release.
