### ISSUE TITLE
Murine disease model: modifiers of phenotypes

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#124]
Modifiers of phenotypes and other fields are defined using human-specific ontologies and descriptors and are not appropriate for other species including mouse or other model organisms.  Such additional descriptors should be added. For example, age of onset and severity are all currently defined by human terms.

**Comment by julesjacobsen** [comment]
We've used human-specific terms because that is our primary use-case. These are purely for documentation, in practice any ontology term can be used.

**Comment by pnrobinson** [comment]
As Jules says, any ontology term can be used here!
