### ISSUE TITLE
Murine disease model: conditions

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#125]
Where do we record environmental conditions?  For example, high-fat diet, surgical intervention, chemical exposures? Do you envision a separate packet for each intervention and control as well? Or will this be recorded with each individual annotation?

**Comment by pnrobinson** [comment]
This is not specific to the murine disease model. We are planning on introducing a field for environmental exposures once community resources for this (e.g., ECTO) have matured and the requirements are more obvious. I do not think we can address this though at the current time point.
