### ISSUE TITLE
Murine disease model: annotation vs packet evidence

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#126]
What is your current definition for a single unique phenotype annotation line? What modifiers and evidence are required, recommended or optional?  We are not completely clear why some annotation qualifiers/modifiers/evidence are at the whole phenopacket level (e.g. references and sex) and others are at the individual annotation level.  It makes much more sense to move all of these to the annotation level.

**Comment by cindyJax** [comment]
MGI does not distinguish sex or karyotypic sex at the genotype level (except perhaps for implied annotations to genotypes carrying X-linked and Y-linked mutations).  The sex is specified in each individual phenotype or disease annotation attached to the genotype. Are you expecting to have different packets for each sex?  I’m considering references where most of the data is generated on an undetermined or pooled sex, but there is a simple mention of male or female infertility.  Would you expect to make separate packets for that one annotation away from the rest of the data?  You could miss a lot of information if you only pick up one phenopacket based on your search.    Examples: Genotype MGI:2175703 would be split to at least 5 phenopackets (ref and sex) . Genotype MGI:3711773 would be split into at least 4 phenopackets (ref, sex and how will genetic background differences be noted?). Genotype MGI:3623749 would be split into 23 phenopackets (one single reference to female infertility, multiple refs).

**Comment by julesjacobsen** [comment]
We took the approach of modelling data at the level of the individual, whereas these examples have amalgamated all the different phenotypes from different individuals in the cohort into a virtual individual. 

Sex/karyotypic sex is an optional field. The default value for these is 'unknown'.

The rest of this is discussed at the end of issue #83 from [this comment onwards](https://github.com/phenopackets/phenopacket-schema/issues/83#issuecomment-483399379)
