### ISSUE TITLE
Murine disease model:subjects

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#127]
A) Subjects with phenotype/disease can also be MGI strains, not just MGI genotypes.  Examples: STR/Ort (MGI:2164380), model for osteoarthritis, SAMP6/TaSlc (MGI:6155688), model for osteoporosis, TALLYHO/JngJ (MGI:3511696) model for type II diabetes. Allele and zygosity fields will not apply (your ‘variant’ section). In the “subject” section.  The allele and zygosity field is currently required. 
B) Phenotype/Disease data are also directly attached to genes and alleles in mouse and other organisms.  In the “subject” section, can the ID then be any data object?

**Comment by julesjacobsen** [comment]
A) Variants / Allele isn't a required field so you can have just phenotype information associated with a subject

**Comment by pnrobinson** [comment]
After discussions at Hinxton, we have decided to shelve this option until better standards are available for representing straing/backgrounds. This is out of scope for Phenopackets.
