### ISSUE TITLE
Murine disease model: expression data

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#128]
Mouse genotypes at MGI also have mouse expression data attached – and some consider expression as an aspect of phenotype.  How will we eventually incorporate and link such expression data to phenopacket data?

**Comment by pnrobinson** [comment]
The Phenopacket is not intended to be a complete model of all aspects of phenotype, and expression data seems out of scope. It would be easily possible to link Phenopackets with files or URIs that point to expression data. I would suggest that we consider how to implement such links for a version 2 if Phenopackets turn out to be useful for MGI data. @cindyJax

**Comment by pnrobinson** [comment]
expression data is out of scope for phenopackets but could be combined.
