### ISSUE TITLE
Murine disease model: complex genotypes

### ISSUE THREAD

**Issue by cindyJax** [phenopackets/phenopacket-schema#129]
How will complex genotypes be modeled?  In this example, your label "heterozygous" is attached to the genotype entity, not the allele pair.  If you have more than one allele pair in the genotype, how will you specify the zygosity for each allele pair?

**Comment by pnrobinson** [comment]
It's actually a variant, 
```
"variants": [{
 "zygosity": {
   "id": "GENO:0000135",
   "label": "heterozygous"
 },
 "background": "involves: 129S1/Sv * 129X1/SvJ * C57BL/6J",
 "mouseAllele": {
   "id": "MGI:3690325",
   "gene": "Fbn1",
   "alleleSymbol": "tm1Hcd"
 }
}],
```

**Comment by pnrobinson** [comment]
In this example, the variant Fbn1^{tm1Hcd} is denoted a heterozygous, and the genotype of other variants can be provided as well.

**Comment by pnrobinson** [comment]
The full GA4GH Variant Model, which is not yet incorporated into Phenopackets, can represent alleles, variants, haplotypes. We are meeting with the GA4GH VMC group about this in Hinxton next week. If you have examples of complex variants that might need to be represented please send them!

**Comment by pnrobinson** [comment]
After discussions at Hinxton, we have decided to shelve this option of modeling MGI notated alleles/genotype/background until better standards are available for them. This is out of scope for Phenopackets.
