### ISSUE TITLE
Difference between disease and phenotype messages?

### ISSUE THREAD

**Issue by mcourtot** [phenopackets/phenopacket-schema#13]
https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L201

seem to indicate they are similar.

**Comment by pnrobinson** [comment]
@mcourtot I am not sure I understand this and sorry this has gotten old. The phenopacket is intended to transmit information about the phenotypes about a subject with a known or unknown disease. Can you specify where we need to improve the documentation?

**Comment by mcourtot** [comment]
https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L461 is a message for a disease

https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L77 is a message for a phenotype

Defined as (simplified):

```
message Phenotype {
    string description = 1;
    OntologyClass type = 2;
    bool negated = 3;
    OntologyClass severity = 4;
    repeated OntologyClass modifiers = 5;
    oneof onset {}
    repeated Evidence evidence = 10;
}

message Disease {
    // The identifier of this disease e.g. MONDO:0007043, OMIM:101600, Orphanet:710, DOID:14705 (note these are all equivalent)
    string id = 1;
    // Textual name of the disease e.g. Pfeiffer syndrome
    string label = 2;
    oneof onset { }
}
```

They seem slightly different (should `Disease` use an `OntologyClass` object?) now. I can't remember if they were that different when this ticket was created - for example `modifiers` is a fairly recent addition I believe. They still seem quite overlapping, and I'm not sure how to choose the right one. For example, is adrenogenital syndrome a disease or a phenotype? It is in both [Mondo]( http://purl.obolibrary.org/obo/MONDO_0015898) and [HPO](http://purl.obolibrary.org/obo/HP_0000840)

Ultimately the question is whether it is worth having the 2 types of messages and if yes why.

**Comment by cmungall** [comment]
I'll defer on the d vs p discussion for now

but good point about the modeling. We need to refactor disease. If id is a key, and we have two disease messages with the same class id and different onsets, we have incoherency. So I think disease should use the same kind of modeling as phenotype

**Comment by pnrobinson** [comment]
I think that many phenotypes will define the disease diagnosis as well as the phenotypes that the patient with this disease had. This is extremely useful for phenotype genotype correlation studies. Other phenopackets will leave out the disease if the diagnosis is unknown.
In essence, for us the difference is that phenotypes are observed components of a disease, and the disease is the inferred diagnosis.  Both coexist peacefully in the same phenopacket.

**Comment by pnrobinson** [comment]
There is no reason that two disease messages with different onsets are inconsistent. For instance, if I get the common cold last year and this year and want to use FaceBook to broadcast my suffering to my friends, then I might send two such messages.

**Comment by pnrobinson** [comment]
there do not seem to be any open action items here, closing. Reopen if needed!
