### ISSUE TITLE
DOB concerns 

### ISSUE THREAD

**Issue by mellybelly** [phenopackets/phenopacket-schema#136]
I don't think we want to have DOB as part of the Phenopacket, or if so, there needs to be a whole lot of warning/optional documentation and QC checks regardless.

https://phenopackets-schema.readthedocs.io/en/latest/individual.html

**Comment by pnrobinson** [comment]
The idea is that some people might want to use a phenopacket within a hospital setting while ordering a lab and never go beyond a firewall. But I guess you are worried about phenopackets with DOB mistakenly being transmitted elsewhere?

**Comment by allisonheath** [comment]
Would it be worth the effort to have identifiable/deidentified versions of Phenopackets? Kind of like other systems have flag PHI fields so you can programmatically strip them and/or have transforms to time intervals? Having a set process we could take to compliance folks would definitely up the appeal of Phenopackets to cross both the internal/external interchange use cases.

**Comment by mellybelly** [comment]
yes that would be ideal i expect. we just need to make SURE that it is very clear how this is managed. If you have a good example of another system that does this well, lets take a look. I do have a lot of concerns here... its just all too easy.

**Comment by pnrobinson** [comment]
@julesjacobsen thoughts about removing the possibilities for DOB?

**Comment by julesjacobsen** [comment]
I don't mind removing it if people think its too risky. We already have an age and age range, so it might be a bonus to simplify things.

**Comment by pnrobinson** [comment]
Then let's remove it. I do not think there is an absolute use case for DOB being within the packet anyway

**Comment by julesjacobsen** [comment]
Having chatted to some IMPC folks, they really need a DOB for their analyses. In this case it's only a timestamp which can be as specific or non-specific as you like. It's computable and accessible from standard language libraries (ISO is not). So perhaps we'll have to ensure people use these things wisely.

The Age message doesn't actually mitigate the risk as it is just a string type and could just as easily contain the patioent's DOB as a timestamp.
