### ISSUE TITLE
OntologyClass for reference vs. abnormal samples

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#139]
In the cancer example, there is an attribute `"isControlSample": false`  used to classify the cancer vs. reference samples.

The need to distinguish between "samples representing an unaltered/normal aspect of the organism" vs. "abnormal" has been recognised before &  we have recently initiated the creation of classes in EFO for this purpose; please [see the discussion](https://github.com/EBISPOT/efo/issues/365#issuecomment-462274090) and the resulting classes (OLS [reference](http://www.ebi.ac.uk/efo/EFO_0009654) and [abnormal](https://www.ebi.ac.uk/efo/EFO_0009655) sample etc.).

This example shows our current use in `progenetix.biosamples`.

```
	"provenance" : {
		"material" : {
			"description" : "normal cervix",
			"type" : {
				"id" : "EFO:0009654",
				"label" : "reference sample"
			}
		},
```

#### Proposal

Use an `OntologyClass` instead of a custom attribute to distinguish between reference - abnormal ( - neoplastic) samples, either in a new wrapper or as part of `sampledTissue` (which would need to become a list, then).

**Comment by pnrobinson** [comment]
@mbaudis so basically in the above example we would have a list of two ontology terms, one for "cervix" and one for "reference sample"?

**Comment by mbaudis** [comment]
@pnrobinson The anatomic locus/topography stays separate (e.g. right now you use `sampledTissue`).

In the example, the `"description" : "normal cervix"` is just a text label (we use an extra wrapper for most ontology objects; the real "ontology objects" are behind `type`). Not strictly necessary, but helpful in many cases (e.g. here "cervix" doesn't have a relation to the ontology, but the "normal" word in the description is a helpful sanity check).

The point would be to use this `provenance.material` - or another attribute - to represent non-phenotype ... attributes, relevant for interpretation. Here this would be

```  
  "isControlSample": true` 
```
could become
```
  "material" : [
    {
      "id" : "EFO:0009654",
      "label" : "reference sample"
    }
  ]
```
... leaving space for additional attributes.
(As you can see, while I used the `provenance.material` structure, I'm not bound to that. The important point is to replace an arbitrary attribute with a more general expression.)

**Comment by mbaudis** [comment]
@pnrobinson Btw., since all the attributes `histologicalDiagnosis`, `tumorGrade`, `sampledTissue` ... use ontology classes - why have them in separate attributes, if the classes have implicit scopes? I'm personally not a big fan of too many named attributes - we have e.g. just a `biocharacteristics` list for locus, histology, diagnostic code ... (In the prostate ca. example, `"histologicalDiagnosis": { "id": "NCIT:C5596" ...` is even a bit questionable, since the term does not really reflect a histology but a diagnostic class, including organ...).

**Comment by julesjacobsen** [comment]
No longer relevant. Closing this.
