### ISSUE TITLE
FHIR profile with custom extensions

### ISSUE THREAD

**Issue by allisonheath** [phenopackets/phenopacket-schema#141]
I know there's the https://github.com/phenopackets/phenopacket-schema-fhir-interop repository and #75 to update it. But from the GA4GH connect meeting today, there seemed to be some strong use cases for more directly defining the information content of Phenopackets in FHIR. Sounds like this would need:

- [ ] Bringing together the fields that exist in FHIR into a single profile: https://www.hl7.org/fhir/profiling.html
- [ ] Defining custom extensions for any properties that do not currently exist: https://www.hl7.org/fhir/extensibility-examples.html

Others who have more experience in FHIR please chime in if this would be a right approach - this is what I've gleaned in my initial dabbling. But from what we were hearing, sounds like this could help with adoption in the clinical/medical field and the actual message could be fairly readily implemented stand alone in a research context (not needing a entire FHIR server etc - just compatible with the JSON).

**Comment by julesjacobsen** [comment]
@ametke can you comment on this?

**Comment by ametke** [comment]
I think we need a FHIR implementation guide (which includes profiles, extensions, etc.) that formalises how a collection of FHIR resources should look like so they can be transformed into a Phenopacket. Happy for you to assign this to me. I think this is a separate project / product / standard in itself and I will look into creating a proposal for it.

**Comment by julesjacobsen** [comment]
@ametke are you making any progress with this? We need to have things ready by mid-June for the approval committee.

**Comment by ametke** [comment]
Yes, @julesjacobsen, I've made some progress and will show you what I've got during next week's GA4GH call (Tuesday 6am my time).

**Comment by julesjacobsen** [comment]
@ametke brilliant! Looking forward to seeing this.

**Comment by julesjacobsen** [comment]
Links here:
https://github.com/aehrc/fhir-phenopackets-api

https://simplifier.net/phenopackets

**Comment by pnrobinson** [comment]
Please move this discussion to https://github.com/phenopackets/core-ig
