### ISSUE TITLE
Add reference to external phenotypic data, eg FHIR bundle

### ISSUE THREAD

**Issue by RobertJCarroll** [phenopackets/phenopacket-schema#144]
From my perspective, being able to link out to a FHIR bundle containing the resources describing the "complete" data of a patient could be quite helpful.

I can imagine a study tracking certain outcomes that would be recorded in the phenopacket, then one could do some interesting computation on the full set of data as appropriate. One discovery example from a study I'm participating in would be to record date at event of Grade 2 Chemotherapy Induced Peripheral Neuropathy. Having the recorded date (whether by retrospective review or prospectively) explicitly described in the phenopacket (as it's not an EHR feature) would allow me to use the detailed medication information in FHIR to look at total dose to event. Linking out to the evidence documented in the FHIR bundle would be helpful as well, eg identifying the clinical note that indicated the CIPN.

Now I can do my study! Having summarized protocols and such would be handy too, eg understanding concomitant therapy with other neurotoxic treatments.

**Comment by pnrobinson** [comment]
@RobertJCarroll  I think the goal of the Phenopacket is to provide a "minimal computational unit" that will allow analysis using a standard way of capturing information. We have added lots of new features for v2 that we are currently discussing and that might cover your use case. I would suggest if it is not possible to use the phenopacket in a particular study that it would be more "in the spirit of the phenopacket" to store the phenopacket and links to other information separately. We can discuss this topic either via zoom, tomorrow (9AM EST, Dec 17) at the GA4GH call or at the subsequent GA4GH call and we will try to make the decision that reflects the will of the majority (the above is just my personal take...).

**Comment by julesjacobsen** [comment]
Closing this due to lack of action.
