### ISSUE TITLE
Biosamples information - add a preservation method

### ISSUE THREAD

**Issue by allisonheath** [phenopackets/phenopacket-schema#145]
Reviewing the biospecimen components of [GDC](https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=sample) the information is typically broken up into:
- composition: represents the cellular composition of the sample, e.g. `Blood`, `Saliva`, `Solid Tissue`, `Derived Cell Lines` as some of the most common I see
- tumor_descriptor: kind of disease present in the tumor specimen as related to a specific timepoint., e.g. `Primary`, `Recurrence`, `Metastatic` etc
- preservation_method: represents the method used to preserve the sample., e.g. `Frozen`, `FFPE`

No claims to how well this represents biosample information for computational use, but it'll probably be a question of how these map (or don't map) to phenopacket fields.

Just looking at the docs perhaps:
- `tumor_descriptor` = `tumor_progression` which is labeled as TODO?
- `composition` = `sampled_tissue` but would cell lines, blood, saliva fit in here?
- Don't see an analogy for preservation method, but not sure the importance in this context? Would you expect the calls provided to already have taken care of artifacts in genomic analysis introduced by different preservation methods? 

Probably worth a check against the ICGC data dictionary as well: https://docs.icgc.org/dictionary/viewer/#?viewMode=details&dataType=specimen

**Comment by julesjacobsen** [comment]
Thanks for the links @allisonheath that's a really nice resource.

It's up to the users to decide on how the calls are created. If its a standard requirement for the preservation method to be specified, we could easily add this as an `OntologyClass`.

@pnrobinson any objections?

**Comment by pnrobinson** [comment]
This could inherit from
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C49337  (Tissue Preparation or Processing Technique)

**Comment by julesjacobsen** [comment]
There is no 'frozen'/ 'fresh frozen' concept there..

**Comment by pnrobinson** [comment]
Freezing is under "action" https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C48160

**Comment by julesjacobsen** [comment]
freezing != frozen

**Comment by julesjacobsen** [comment]
Computationally, I'm not sure how useful this will be. I'm going to put this as a 1.1.0 feature for the time being as I personally don't have enough knowledge on this to say what is or isn't useful and would want feedback from someone who is knowledgeable on these matters. It might be that we also need starage as well as preservation for this to be useful.

**Comment by allisonheath** [comment]
Typically, the most important thing is whether it's FFPE - which results in noisier genomic data, but can be corrected for if you're aware. The secondary is that sometimes you'll see batch affects with other preservation methods.

**Comment by pnrobinson** [comment]
@allisonheath  Are there any examples of how this information is structured that we could consult?
It seems there are many possible ways of doing so

**Comment by allisonheath** [comment]
Digging through NCIt a bit more, looks like potentially you have to go up to [Laboratory Procedure](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16475#) to find a common parent for [FFPE](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16475#) and [Cryopreservation (aka Frozen)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16475)

Many of the others I'm aware of are more biobanking operations oriented, e.g. https://github.com/biobanking/biobanking/. Or at a high level description: https://biospecimens.cancer.gov/bestpractices/to/bcpsrd.asp

**Comment by pnrobinson** [comment]
@allisonheath We are having difficulty with this item. It seems there is preparation, preservation, storage, etc., and probably we do not want to go into this level of detail? Is there a case to be made for sample_processing and recommending terms such as FFPE and Cryopreservation as above? @julesjacobsen

**Comment by pnrobinson** [comment]
@allisonheath we are hoping to finalize the v2 in the next few months. Can we touch bases about this?

**Comment by julesjacobsen** [comment]
https://docs.icgc-argo.org/dictionary Specimen

specimen storage: 

Cut slide
Frozen in -70 freezer
Frozen in liquid nitrogen
Frozen in vapour phase
Not Applicable
Other
Paraffin block
RNA later frozen

specimen processing:
Cryopreservation in liquid nitrogen (dead tissue)
Cryopreservation in dry ice (dead tissue)
Cryopreservation of live cells in liquid nitrogen
Cryopreservation - other
Formalin fixed & paraffin embedded
Formalin fixed - buffered
Formalin fixed - unbuffered
Fresh
Other

**Comment by julesjacobsen** [comment]
A potential ontology for this might be [OBIB](https://www.ebi.ac.uk/ols/ontologies/obib), specifically children of [OBI_0001472](https://www.ebi.ac.uk/ols/ontologies/obib/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001472&viewMode=All&siblings=false) and  [OBI_0000047](https://www.ebi.ac.uk/ols/ontologies/obib/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000047&viewMode=All&siblings=false), but these don't map precisely.
