### ISSUE TITLE
Product Approval Forms - To Be Completed

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#146]
[Product Approval Information](https://docs.google.com/document/d/1UUJSnsPw32W5r1jaJ0vI11X0LLLygpAC9TNosjSge_w/edit?usp=sharing)
- [x] [Product Approval Form - Pxf v1 Submission](https://docs.google.com/document/d/1gMA6rRyHrkv-RPCtwHwzVY8jpYu0cT9WDRos-oGdx7w/edit?usp=sharing)

There are these forms that need to be completed and linked in the above form:
- [x] [Security Form](https://docs.google.com/document/d/1WciRhrzQFb0cZR3lXNSuSvBrFZ49nrFqxGQqZ9fYn2k/edit?usp=sharing)
- [x] [Product Proposal Security Form](https://docs.google.com/document/d/1vtd9ppIYOFIh7UxrJzwaTo8amqoIALGwdI0mVsJS1RA/edit?usp=sharing)
- [x] [Regulatory and Ethics Form](https://docs.google.com/document/d/1e5PePA9-lMLzQIuwO1bpJT-irF8HxOFgoHGvE3kOvuU/edit?usp=sharing)
- [x] [Partner Engagement Form](https://docs.google.com/document/d/1I3yerXIihNt1b7CYjCS6usoLrXECpNr_nNzDIfaeqgE/edit?usp=sharing)

**Comment by pnrobinson** [comment]
I have taken a first pass at these forms, please provide feedback @cmungall @mellybelly @julesjacobsen  others

**Comment by julesjacobsen** [comment]
Thanks @pnrobinson, I'll look through them.

**Comment by julesjacobsen** [comment]
@lindsmith  where do I find the 'Product-Proposal Security Questionnaire' required by the Security form?

**Comment by lindsmith** [comment]
@julesjacobsen I don't think phenopackets ever filled that form out. I know phenopackets never filled out a "Product Proposal Form" (because it didn't exist at the time). Just leave that section blank, secretariat is aware!

**Comment by julesjacobsen** [comment]
@lindsmith @pnrobinson I think these are all done! I'm going to leave the issue open until they've all been double-checked and we've been approved.

**Comment by pnrobinson** [comment]
we are all set on this, closing!
