### ISSUE TITLE
Choosing a Product Review Committee

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#147]
We need to choose three people who will make up the PRC, and contact them to confirm they are happy with this role. I am giving us a deadline of **May 31st** to choose some potential members, so that we have time to contact them before submission. The criteria for PRC members is as follows:

_Work Stream Lead_ - the first member must be the lead of a different Work Stream to the main proposing Work Stream.
_Driver Project Representative_ - the second member must be a representative of the source Driver Project for this product. This member should have knowledge of the specification development.
_Third Member_ - this may be any individual who is an active member of a Work Stream different to the Primary Work Stream and the Work Stream led by the individual named above, or another individual with expertise in the field.

I suggest we choose 2-3 people for each of the above, so we have backup options if needed! With many potential deliverables being submitted, it could be challenging to find someone available.

**Comment by julesjacobsen** [comment]
@lindsmith do you have enough people to fill the roles now? If so, can you close the ticket, please.

**Comment by lindsmith** [comment]
@julesjacobsen We don't have a backup for Bob but hopefully he'll be available! We'll discuss if there's an issue.
