### ISSUE TITLE
c++ compilation

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#150]
protoc --proto_path=src/main/proto/ --cpp_out=. src/main/proto/org/phenopackets/schema/v1/phenopackets.proto src/main/proto/org/phenopackets/schema/v1/core/base.proto 

remove the packages from the C++ headers 
then 

g++ --std=c++17 -o app main.cpp phenopackets.pb.o base.pb.o -lprotobuf

**Comment by pnrobinson** [comment]
Interestingly, the maven generated and the protoc generated files differ in their use of NULL and nullptr to represent a null pointer (the later is now recommended):
```
<   GOOGLE_DCHECK(value != NULL);
---
>   GOOGLE_DCHECK(value != nullptr);
```
https://github.com/protocolbuffers/protobuf/issues/4094

If the rest of the code is correct, this will have no effect, but there is more typechecking with nullptr than with NULL and so now nullptr is preferred.

**Comment by pnrobinson** [comment]
fixed with https://github.com/phenopackets/phenopacket-schema/pull/152

**Comment by julesjacobsen** [comment]
This has now been merged into master
