### ISSUE TITLE
Product Landing Page:

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#153]
For the GA4GH, we need to indicate a landing page. I am going to put the read the docs right now, but it would be good to switch to http://phenopackets.org/. To do that, we will need to update that webpage. I would be happy to do so in the form of a PR if @cmungall / @mellybelly would like -- otherwise, please make another suggestion.

**Comment by julesjacobsen** [comment]
We need to make a new repo for the site and add the existing code there. It is currently hosted from here:

https://github.com/phenopackets/phenopacket-format/tree/master/docs

**Comment by julesjacobsen** [comment]
I'm closing this as we have the Docs as a landing page. Will open a new issue about the old website.
