### ISSUE TITLE
MAINTAINERs page

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#154]
We need to indicate: ```Please provide a URL to a user facing document that details how a user may make changes, and the decision making process```

GA4GH suggests a page like this
https://github.com/samtools/hts-specs/blob/master/MAINTAINERS.md

@mellybelly @cmungall @julesjacobsen others,  thoughts?

**Comment by julesjacobsen** [comment]
The link doesn't really explain the decision-making process, but other than that doesn't seem outrageous. I'll add one.

I'd go so far as to say there ought to be a CONTRIBUTING.rst as per the GitHub suggestions which is focussed on the process of making contributions.

**Comment by julesjacobsen** [comment]
How does this look?

https://github.com/phenopackets/phenopacket-schema/blob/master/CONTRIBUTING.rst

**Comment by pnrobinson** [comment]
Looks fine to me! So we would use this page instead of a MAINTANERS page? That sounds like a good idea...
