### ISSUE TITLE
Implementation Details

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#155]
GA4GH writes
```
Each standard requires two implementations. They do not have to be open source. Please indicate where these can be viewed/obtained. In a client-server relevant APIs there should be 2 clients and 2 servers.
```
I would say that the Java code that we have written should qualify as one implementation? 
What should our second implementation be?
I could expand the C++ code for reading phenopackets, but at present, I do not know of any audience for C++ code to do things with HPO etc. 
@mellybelly @cmungall @julesjacobsen others, thoughts?

**Comment by julesjacobsen** [comment]
@ametke is producing a FHIR profile (or was it implementation guide?) which should certainly count as one implementation, the actual schema output i.e. Java/Python/C++ would all count as another.

We have applications using the implementations already - Solve-RD is using both the Python and Java implementations, Your HPO Annotator code? LIRICAL uses the phenopacket as an input parameter. The [Phenopacket-FHIR interoperbility server] (https://github.com/phenopackets/phenopacket-schema-fhir-interop) is another example.

**Comment by julesjacobsen** [comment]
On GitHub, these projects are dependent on the schema:

https://github.com/phenopackets/phenopacket-schema/network/dependents
