### ISSUE TITLE
Interoperability Notes

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#156]
GA4GH writes:
```
Different standards will have different paradigms that demonstrate the interoperability of 
implementation instances of the specification. Please detail how implementations have shown to 
interoperate with each other here. You can add information showing how multiple clients were able to 
connect with multiple servers correctly, or how different clients were able to process or roundtrip the 
data in the same way. This can be a link to an interop document with further details as well.
```
This is not exactly applicable to our standard. We could possibly roundtrip a phenopacket from JSON/protobuf/Java/C++/Python (various permutations ...), but we would mainly be testing Google's code if we did this.
@mellybelly @cmungall @julesjacobsen others, thoughts?

**Comment by julesjacobsen** [comment]
I'd say these were all the same implementation - that's the point of the protobuf schema. This was also the reason I chose it as there ought not to be a need to re-implement it yourself.
