### ISSUE TITLE
Add validation via protoc-gen-validate

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#157]
This is pretty cool and worth a look at, the only problem being it states it is at alpha stage and will almost certainly change.
 
https://github.com/envoyproxy/protoc-gen-validate

**Comment by pnrobinson** [comment]
This does look like a very interesting project!

**Comment by julesjacobsen** [comment]
The project is still a bit immature and caused problems with the python build (issue #207), so this is on-hold for the time being.

**Comment by pnrobinson** [comment]
This project still is in the alpha stage (March 26,2021), and I do not think we can rely on it. I think we will likely want to write our own code to validate phenopackets and it may be easier to code from scratch to avoid issues with alpha-stage libraries. @julesjacobsen  can we close this issue?

**Comment by julesjacobsen** [comment]
@pnrobinson yes, I agree. The use-cases for phenopackets also means that there is no one-size-fits-all  validation we can apply. For example a rare disease and a cancer phenopacket will be very different.
