### ISSUE TITLE
biosamples

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#16]
The current comment needs some attention, methinks.
```
// Biosample(s) derived from the patient or a collection of biosamples in isolation
```

With the recent revisions, we have decided that a PhenoPacket describes one individual. It seems to me that if we allow a Phenopacket to describe a collection of isolated biosamples, that it is scope creep, and many of the other fields do not make sense (e.g., patient describes one individual and not a cohort).

We would simplify things enormously if we make another element called ``biosample-collection`` that has the required metadata. Both the phenopackets and this object would then be interoperable, and we would greatly simplify the use of the PhenoPacket.

Suggested revision of the comment
```
// Biosample(s) derived from the patient
```

Medium-term: also consider creation of biosample-collection message.

**Comment by cmungall** [comment]
biosample doesn't seem to be linked from anywhere, so maybe leave out?

**Comment by cmungall** [comment]
Explicit proposal: omit biosample from standard. What is the use case for including it, vs linking where required? How exactly are biosamples linked to individuals? Do we include details of their processing analyses? Feels way out of scope. Note also that we reference datasets but we don't explicitly model them.

This would eliminate the need to decide on other tickets, e.g. #34

**Comment by drseb** [comment]
I also do not understand why we would include this and it feels a bit out of scope.

**Comment by pnrobinson** [comment]
Well, this is the class that we are going to use to describe a biopsy from a patient, in cancer but also in other diseases. Why do you think this is out of scope?

**Comment by julesjacobsen** [comment]
@cmungall Biosample is related to Individual via individual_id https://github.com/phenopackets/phenopacket-schema/blob/76723e2438747b3480ebd31802909a35f8be5afd/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L231

It's a one-way link. I guess you could say it's a bit inconsistent, not being a list of Biosample directly in the individual, but the phenopacket could simply have an enviromental sample in it, unrelated to any individual. The individual_id is there for cases where the sample is a biopsy taken from an individual.

**Comment by pnrobinson** [comment]
We have addressed all open issues, closing
