### ISSUE TITLE
Wire format for unspecified types 

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#162]
Currently there are three top-level types: `Cohort`, `Family` and `Phenopacket`. The `Cohort` and `Family` types both utilise a `Phenopacket` in various ways. 

There could be cases where the exact type is unknown. [Kubernetes](kubernetes.io) solves this using [this mechanism](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md#wire-format) - 

```proto
message Unknown {
  optional TypeMeta typeMeta = 1;
  optional bytes value = 2;
  optional string contentEncoding = 3;
  optional string contentType = 4;
}

message TypeMeta {
  optional string apiVersion = 1;
  optional string kind = 2;
}
```

**Comment by pnrobinson** [comment]
@julesjacobsen should we implement (something like) this? It might simplify some APIs because the optionality would be already baked in but on the other hand, there would be a natural way of representing the options in a REST API.

**Comment by julesjacobsen** [comment]
Closing - slightly out of scope.
