### ISSUE TITLE
Days to recurrence/Time to recurrence

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#166]
https://cdebrowser.nci.nih.gov/cdebrowserClient/cdeBrowser.html#/search?publicId=6154731&version=1.0

Time to recurrence, can use P2Y3M12D

Add to biosample

**Comment by pnrobinson** [comment]
Alternatively, should this be in the Diagnosis?

**Comment by pnrobinson** [comment]
@julesjacobsen this seems reasonable to add to v1. @mellybelly @cmungall thoughts?

**Comment by julesjacobsen** [comment]
Or possibly ought to be on Disease?

**Comment by pnrobinson** [comment]
Let's discuss this on the GA4GH call tomorrow.
The proposal is to add
timeToRecurrence as an element of ``Disease``
I am not sure we have the proper time element for it?

**Comment by julesjacobsen** [comment]
This seems somewhat related to the ARGO `Follow Up` file.

field name | description
------------|--------------
interval_of_followup | Interval from the primary diagnosis date to the follow-up date, in days.
disease_status_at_followup | Indicate the donor's disease status at time of follow-up. (Reference: RECIST)
relapse_type | Indicate the donor's relapse type.
relapse_interval |  If the donor was clinically disease free following primary treatment and then relapse or recurrence or progression (for liquid tumours) occurred afterwards, then this field will indicate the length of disease free interval, in days.

We don't really have any way of expressing this.

**Comment by pnrobinson** [comment]
It seems more idiomatic to allow this number to be computed from other elements of the Phenopacket that would describe primary disease and recurrence. Closing.
