### ISSUE TITLE
3.8.0

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#169]
In playing around with the C++ version, I noticed that we need to use the same protoc version as we have in the pom file if we use the pom file to generate the C++ code (doh!). I am going to make my C++ script use protoc for this rather than using maven, but still we may want to upgrade to the latest version prior to the 1.0 release. 

https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.8.0

**Comment by julesjacobsen** [comment]
12c9e9773611b88b38ba752caf8afe9b4b0df9a0
