### ISSUE TITLE
'Placeholder' doc for genes is confusing

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#17]
I think the word Placeholder is confusing in the comment for the genes element:
```
// Placeholder for gene concepts - could be used for either describing candidate genes or causative genes. The
// resources using these fields should define what this represents in their context.
```

suggested revision
```
This field defines a list of one or more genes that can be used to denote a collection of 
candidate genes or causative genes. The resources using these fields should define what this
represents in their context.
```

**Comment by pnrobinson** [comment]
same comment applies to use of Placeholder for the variants element. Every single variable in a computer program is a Placeholder, and it is confusing if we only designate some of our elements as Placeholders and others not.

**Comment by pnrobinson** [comment]
@julesjacobsen do you agree? If so I will just fix this with a commit?

**Comment by drseb** [comment]
I think your point is valid.

**Comment by julesjacobsen** [comment]
Fair enough, that makes sense.

**Comment by julesjacobsen** [comment]
I think I'm going to remove 'Placeholder' as this was meant to mean 'Provisional', but they appear to have stood the test of time so far, so this is no only misleading, but inaccurate!

**Comment by pnrobinson** [comment]
In German there is a saying that means roughly "Nothing is as permanent as a temporary measure" haha
