### ISSUE TITLE
Incorrect PubMed prefix in documentation and examples

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#177]
Original post:
> The correct prefix for PubMed references is `pubmed:` instead of `PMID:`.
> https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/base.proto#L136
> ... and others.

... which now should be reversed: `PMID` preferred. But see the discussions - started with the original post - below (edited on 2019-08-28).

**Comment by pnrobinson** [comment]
@mbaudis  -- interesting! I have always used and seen PMID. What is the source of this, is that from NCBI?

**Comment by mbaudis** [comment]
The registered prefix at [identifiers.org](http://identifiers.org).

**Comment by pnrobinson** [comment]
Quel surprise!
Still, Pubmed actually *uses* PMID. I think this prefix is universally recognizable and some users would ask what exactly pubmed:300212322 is. @cmungall @mellybelly @mbaudis would it be acceptable and possibly even a good idea to make an exception and use PMID ?

**Comment by mellybelly** [comment]
PMID is much more common in my world and is used by Pubmed.

As part of a coordination effort between N2T, identifiers.org, Monarch, and other resources, we have the synonyms curated. N2T may have more synonyms and has additional features that may be useful here. PMID: curies should work for identifiers.org and for N2T resolvers.

An example: https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld

I would use PMID, since it is the native use in pubmed and in most graph dbs.

We have discussed the need for CURIE context .jsonld files and standardized ways to reference URIs in other GA4GH tickets:
https://github.com/ga4gh/vr-spec/issues/32
https://github.com/ga4gh/mme-apis/issues/113
https://github.com/ga4gh-discovery/ga4gh-case-discovery/issues/29

@jmcmurry

**Comment by mellybelly** [comment]
I guess this one is missing from identifiers.org... there are others with issues reported here:
https://github.com/prefixcommons/biocontext/blob/master/reports/clashes.txt

Here is that same pub in N2T:
https://n2t.net/PMID:22824167, resolves fine.

**Comment by mbaudis** [comment]
Thanks @mellybelly for the context! We, too, used “PMID” until I tested looked for a resolver example following identifiers.org as suggested by @mcourtot in the [link above](https://github.com/ga4gh-discovery/ga4gh-case-discovery/issues/29). So my take home here is to

* stick with PMID here
* provide a working resolver example in the annotation, as a general procedure
* hope for some external cleanup (Monarch)
* re-think a more structured way to integrate resolvers, maybe in SchemaBlocks

**Comment by mcourtot** [comment]
I've sent an email to Sarala from identifiers.org asking if there was a specific reason to use pubmed rather than pmid - and if it was possible to use an additional alias.

**Comment by mellybelly** [comment]
I think it would be absolutely terrific if SchemaBlocks/Monarch/VICC could help maintain prefix commons, and if multiple resolvers could promise resolution of the same minimal set required for GA4GH. This was the original intent of PrefixCommons. 

I don't know why identifiers.org isn't resolving this common prefix - it would have been used in the prior projects that had an agreed upon shared subset between N2T and identifiers.org. It would be a good idea to check on this and make a plan. I think it is VERY important to have redundancy and use multiple resolvers. @jkunze @sarala can we review what is/could be a shared resolution set of prefixes? 

@ahwagner @monicacecilia why don't we put PrefixCommons on our shared talks calendar? its relevant across much of GA4GH. Perhaps @jmcmurry or @cmungall could present?

**Comment by mbaudis** [comment]
@mellybelly @mcourtot I am very much in favour of a project defining / documenting a safe set of common identifiers and respective / safe resolvers under the {S}[B] umbrella. This would best be driven by having implementations for all identifiers used in any of the blocks, with phenopackets being an obviously driver.

**Comment by jkunze** [comment]
I don't know why pmid:22824167 doesn't work at identifiers.org, but I'm pretty sure it used to in their old system. Maybe their aliases didn't make the transition.

I'm coming late to this discussion, so please forgive me if I'm stating the obvious. Regarding GA4GH, you may be aware that n2t.net and identifiers.org support the prefixes ga4ghdos and dev.ga4ghdos. You can see the raw prefix record by submitting just the prefix to N2T, eg, "http://n2t.net/dev.ga4ghdos:" and changes or additions for both N2T and identifiers.org can be requested through the usual means, eg, http://n2t.net/e/prefix_request .

**Comment by mellybelly** [comment]
That is exactly what i was wondering - the agreed upon synonyms from prefixcommons don't seem to all be there now?

For GA4GH just to bring you up to speed, there are two things: 1) resolving things to GA4GH resources, and 2) leveraging a shared set of curies and a GA4GH context file via PrefixCommons (my proposal).

**Comment by jkunze** [comment]
Looking at the prefixcommons prefixes, I don't find any other entry for GA4GH. Could you remind me what agreement and what details you're referring to? I see no reason not to support any set of prefixes and resolution targets that you vouch for.

**Comment by sarala** [comment]
@mbdebian will be working on the support for aliases in the new platform in the coming weeks. Apologies for the inconvenience caused.

**Comment by julesjacobsen** [comment]
Bit late to this thread, but this namespace resolution is what the [Resource](https://phenopackets-schema.readthedocs.io/en/latest/resource.html) element is supposed to achieve in the phenopacket.

_i.e._ the internally in the phenopacket the CURIE can be defined as `PMID:22824167` with the `Resource` defined like this:

```json
{
    "id": "pubmed",
    "name": "NCBI PubMed",
    "url": "https://www.ncbi.nlm.nih.gov/pubmed",
    "namespacePrefix": "PMID",
    "iriPrefix": "https://www.ncbi.nlm.nih.gov/PubMed/"
}
```

So people could define their own resolvers within the scope of the phenopacket.

**Comment by julesjacobsen** [comment]
This issue petered-out, so I'm closing this.
