### ISSUE TITLE
Document format of "id" in ExternalReference; possibly including long form URI/L

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#178]
While the `id` examples for `ExternalReference` point toward "CURIE style", this is not made explicit.

https://github.com/phenopackets/phenopacket-schema/blob/d12f1931f4f3517954b4680d815a609ae201c16b/src/main/proto/base.proto#L137

Additionally, it may be productive to also allow/include long form URIs as format for `id`. While this may not be optimal for e.g. ontology classes, it would allow a more general use of this object prototype (e.g. we're discussing its use for "contributors", where we want to avoid "address overload" but [not everybody may have an ORCID](https://github.com/ga4gh-schemablocks/blocks-json-schema/issues/6#issuecomment-511724120) etc.).

**Comment by julesjacobsen** [comment]
Seems reasonable. As you say we never specified it _couldn't_ be something else, hence the use of a string value.

I've changed the text to say:

```
The syntax of the identifier is application specific. It is RECOMMENDED that this is a CURIE that uniquely identifies 
the evidence source, e.g. **ISBN:978-3-16-148410-0** or **PMID:123456**. However, it could be a URL/URI, or other 
relevant identifier.
```
