### ISSUE TITLE
Replace protobuf fields in docs with table 

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#182]
https://github.com/phenopackets/phenopacket-schema/blob/a5efcb2eefe28660ad1d931b92379f8a04e13eec/src/main/proto/base.proto#L482-L487

**Comment by julesjacobsen** [comment]
I suggest we go with this format:

|Field| Type| Status| Description|
|----|------|-------|------------|
|id| string| recommended| An arbitrary identifier|
|var| string| required| t(8;9;11)(q12;p24;p12)|

Example:

```json
{
    "id": "ISCN:12345",
    "var": "t(8;9;11)(q12;p24;p12)"
}
```

Using this as a template:
```rst
**Data model**

.. csv-table::
   :header: Field, Type, Status, Description
   :align: left
   id, string, recommended, An arbitrary identifier
   var, string, required, t(8;9;11)(q12;p24;p12)

**Example**

.. parsed-literal::
    
  {
      "id": "ISCN:12345",
      "var": "t(8;9;11)(q12;p24;p12)"
  }
```


This can be auto-generated using the library [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc)
https://github.com/pseudomuto/protoc-gen-doc/blob/master/examples/doc/example.md#manufacturer

**Comment by julesjacobsen** [comment]
For Enum types we just want a name and description

**Data model**

|Name| Description|
|----|------------|
|UNKNOWN_SEX|  Not assessed or not available.
|FEMALE| female sex.
|MALE| male sex.
|OTHER_SEX| It is not possible to accurately assess the applicability of MALE/FEMALE.

**Example**

``` json
{
    "sex": "UNKNOWN_SEX"
}
```

Using this as a template:
```rst
**Data model**

.. csv-table::
   :header: Name, Description

    UNKNOWN_SEX,  Not assessed or not available.
    FEMALE, female sex.
    MALE, male sex.
    OTHER_SEX, It is not possible to accurately assess the applicability of MALE/FEMALE.

**Example**

.. code-block:: json

    {
        "sex": "UNKNOWN_SEX"
    }
```

**Comment by pnrobinson** [comment]
This is now implemented.
