### ISSUE TITLE
Re-word Pedigree documentation

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#189]
Currently the overview looks like  this:

``` rst
This element is used to represent a pedigree file (PRD file). A PED file ("pedigree file") describes the family relationships of each sample along with their
gender and phenotype (See the detailed description
at the `PLINK <http://zzz.bwh.harvard.edu/plink/data.shtml>`_ website for more information).
PED files are typically used by software for genetic linkage analysis.
PED files have six mandatory columns, and additional optional columns (that are typically not used
in the context of genomic analysis).

This message represets the core Ped file information
that is used by many programs for analysis of a multi-sample VCF file with exome or genome sequences of members
of a family, some of whom are affected by a Mendelian disease.
```

which elicited this reviewer response 

> The way files are referenced varies between different parts of the spec.  File provides a URI to a generic file (which may be on a local or network drive), HtsFile is wrapper around File that specializes it for genome sequencing files of particular formats (specified in the enum), while Pedigree is a structured breakdown of the PED file format.  The different approaches to supporting files makes the spec feel less internally consistent, and the special casing may limit generalizability and scalable extensibility.

I semi-agree with what was said, but I would say this is a mistaken comment based on the pedigree documentation being somewhat inaccurate. We're not trying to represent a PED file specifically, we're merely using the PED structure. We're _not_ PED compliant as we have enumerated types instead of encoding sex and affected status as integers and we do not embed a TSV file or reference one. 

@pnrobinson I propose we change the documentation to clarify this and include this in the response.

**Comment by pnrobinson** [comment]
agree -- Maybe we can skype at about 10:30AM?
