### ISSUE TITLE
Delete or expand Metadata 'updated' field

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#190]
Bob F's comment:
```
How do created, created_by, and submitted_by relate to updated?  Do the former refer to 
the original submission or only the current one?  It might be helpful to model provenance 
of updates so each update can specify information about its origin and timestamp.
```
I think that we should say that a phenopacket is immutable once it has been created. If you need to update a phenopacket, then you need to create a new file. It is the responsibility of users to keep track of versioning. 
I think that if we try to keep track of versioning within the phenopacket itself, things will become unmanageable, because it will be hard to know what was updated at what time (imagine a phenopacket with 10 consecutive updates). THerefore, I would suggest we remove the 
Metadata::updated
      - list of timestamps
element.

@cmungall @mellybelly @julesjacobsen

**Comment by julesjacobsen** [comment]
This has already been discussed to some extent in issue #46. If we assume immutability then there is no requirement for an `updated` field. @drseb do you need this?

Taking biosamples as another example - they create a new phenopacket on request from the database and they are treated as snapshots in time (see the `MetaData` at the end of the file):

https://www.ebi.ac.uk/biosamples/samples/SAMEA4339553.pxf

but in their [json export](https://www.ebi.ac.uk/biosamples/samples/SAMEA4339553.json) they have `release` and `update`. 

```json

{

    "name": "HPSI0614i-voce_5",
    "accession": "SAMEA4339553",
    "domain": "self.b72ab20c613c0a2a89abb550cbb38a547735d312860a16aefb17a0dc77217ee8",
    "release": "2013-01-01T00:00:00Z",
    "update": "2019-07-25T20:00:35.282Z",
    "taxId": 9606,
```

**Comment by drseb** [comment]
ok. if you really want to assume immutability, then you can of course get rid of the "updated".

**Comment by julesjacobsen** [comment]
@drseb that wasn't what I asked. I wanted to know if you relied on this as if you do, being part of a driver project, we ought to keep it.

**Comment by drseb** [comment]
If the decision is to have one phenopacket per change, this question is no longer relevant. I think the **first step** is, that you need to decide if immutable is now assumed or not. If _yes_: we will try to find other solutions, if _not_: an "updated"-field can be helpful.

**Comment by julesjacobsen** [comment]
OK, so how about we have an `Update` message, somewhat like a git commit message:

```proto
message Update {
    google.protobuf.Timestamp updated = 1;
    string updated_by =2;
    string comment = 3;
}
```

**Comment by drseb** [comment]
Regarding the other question, I think you should ask Leslie, Sergi, and Svitlana about this. My opinion is that it would be good to have a better update mechanism, but I agree that it can get complicated on phenopacket-side. I think you idea is a good start for discussion, but I'll let others comment.

**Comment by julesjacobsen** [comment]
@drseb, can you add them to this thread please? If we can't get a resolution by tomorrow at the latest this will have to be moved to the next release.

**Comment by drseb** [comment]
contacted them via email.

**Comment by lmatalonga** [comment]
Hi @drseb and @julesjacobsen,
In the context of the transfer of RD phenotypic data within Solve-RD, we will need to periodically transfer updated patient information. Updates are related to addition of phenotypic information or to new analysis results (update solved status / causative gene / variant, etc.). In these cases a new phenopacket JSON file will be created but we need to somehow state that this is an updated version of a previous phenopacket. Maybe for our use case (Sergi- correct me if I am wrong) and as far as I can think,  it is more about versioning phenopackets from the same individual than updating a phenopacket.  Hope this helps!

**Comment by julesjacobsen** [comment]
@lmatalonga so this will depend on how you use your identifiers for the phenopacket - you could have multiple phenopackets, with different identifiers, produced at different times to describe the same patient. With this model the phenopacket is a convenient 'wire-format' to send data about individuals or families around your system and there isn't a real need for an updated field.

If, on the other hand you are re-using the ids for the phenopacket and including updated data, then there is a potential need for this.

**Comment by julesjacobsen** [comment]
This change has been added to the RC3.
