### ISSUE TITLE
Remove Biosample.individual_id

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#196]
Is there a strong requirement for `Biosample.individual_id`? This is only RECOMMENDED and the scope of a biosample is the phenopacket. Given the phenopacket documents a single individual only, the `Biosample.individual_id` is not really necessary any more - it was when the phenopacket allowed representation of multiple individuals.

_Originally posted by @julesjacobsen in https://github.com/phenopackets/phenopacket-schema/issues/192#issuecomment-518722797_

**Comment by mbaudis** [comment]
@julesjacobsen @pnrobinson While Jules is correct that in its current structure biosample_id isn‘t needed for a phenopacket, I am strongly against removing it as an optional attribute:

* it allows a broader „define things in phenopackets for use beyond its core protocol“, specifically to serve as SchemaBlocks blueprints 
* Phenopackets haven‘t been „one subject only“ from the start, and who knows the trajectory of use cases
