### ISSUE TITLE
GA4GH Security Approval - Outstanding Issues

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#197]
Two remaining changes needed before the GA4GH security team approves phenopackets:

1) In [here:](https://phenopackets-schema.readthedocs.io/en/latest/working.html) Would it be possible to place the disclaimer after the example code sub-section and make it plural « these example implementations are offered as-is… They will need a an independent security review before they can be… »?

2) Do you think you can also add this disclaimer in the GitHub [repo?](https://github.com/phenopackets/phenopacket-schema) Here you can probably keep it singular (exactly as it was before) « A stand-alone security review has been performed on the specification itself, however this example implementation is offered as-is, and without any security guarantees. It will need an independent security review before it can be considered ready…

**Comment by julesjacobsen** [comment]
This replicates #195 - already done.

**Comment by lindsmith** [comment]
Reopening because these are different edits. 
To clarify: the disclaimer [here,](https://phenopackets-schema.readthedocs.io/en/latest/working.html) needs to be moved to after the example code sub-section (so to be the last item on the page) and made plural.
For the github repo disclaimer, I think they're asking for the disclaimer text to be on the main readme page of the repo - it's currently a separate .rst file

**Comment by julesjacobsen** [comment]
I don't think they were asking for the security disclaimer to be added to the README, they just state the repo. It is much more visible in it's own file https://github.com/phenopackets/phenopacket-schema/blob/master/DISCLAIMER.rst rather than sitting at the end of a README which people will likely not read. We have fulfilled their requirements.

**Comment by lindsmith** [comment]
Thanks Jules! I will follow up with security. Quite possible they just had not seen it (rather than wanting the placement changed)
