### ISSUE TITLE
GA4GH Open for Comment

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#198]
Please see below for a comment I received during the open for comment period. I think the first part of the comment has been mostly addressed with the FHIR IG and its reference in the documentation. 

> Some comments on the phenopackets standard.
 It seems to be that this standard might be better first presented to the world in the context of how it is going to interact with other standards… in particular FHIR - which I understand to be an overarching standard that is anticipated to be incorporated into EMRs worldwide.
While I fully appreciate that phenopackets has a use outside of EMR, I believe there has already been considerable work done by GA4GH collaborators to ensure that phenopackets is operable with FHIR. If GA4GH is serious about encouraging standardised data collection in the clinical setting (via EMRs) then we have to ensure that we are recognising from the start how we envisage that data collection will be done in the clinical setting – and presenting whatever cross-mapping has been done to allow cross-talk between phenopackets and FIHR, and other inter-relationship analysis.
Next I note that the documentation provided for phenopackets references HPO terms but not SNOMED – this seems to be an omission when there has been considerable work done crossmapping terms (even prior to GA4GH initiation I was aware of crossmapping work promoted by HVP). This would seem to present the phenopackets product as a sort of niche tool for HPO users… not at all what I think GA4GH would want to be putting out as first release standard which should bring together at least these two standards for terms (there may be more, but those are the ones I am aware of as “being in the game”).

**Comment by julesjacobsen** [comment]
Indeed, we have a [FHIR implementation guide](https://phenopackets-schema.readthedocs.io/en/latest/fhir.html).

The SNOMED to HPO mappings falls under the remit of Clin/Pheno work stream 1, not the “Clinical & Phenotypic Data Capture & Exchange” work stream. We designed the Phenopacket to be agnostic as to the ontologies/terminologies used, so it is wholly possible to use SNOMED concepts and identifiers in a Phenopacket if that suits the user's needs.

**Comment by julesjacobsen** [comment]
Not had any comment on this so closing this.
