### ISSUE TITLE
Rename Phenotype to PhenotypicFeature

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#2]
What are we trying to convey? Originally Phenotype was defined as a collection of positive and negative OntologyTerms.

```protobuf
// Rename to PhenotypicFeature?
message Phenotype {
    string description = 1;
    
    // perhaps we can simplify this and have a single class and a single boolean flag?
    repeated OntologyClass types = 2;
    repeated OntologyClass negated_types = 3;
    
    // the values of this will come from the HPO onset hierarchy
    // i.e. subclasses of HP:0003674
    OntologyClass onset = 4;
    
    // subclasses of HP:0012823 ! Clinical modifier 
    repeated OntologyClass modifiers = 5;
    OntologyClass assay = 6;
    Evidence evidence = 7;
    //Measurement
    //Environment
    //Frequency? Do we want to be able to encode and HPO annotation?
}
```

This was used like this in an Individual

```protobuf
message Individual {
    string id = 1;
    google.protobuf.Timestamp date_of_birth = 2;
    Sex sex = 3;
    repeated Phenotype phenotypes = 4;
    repeated Disease diagnoses = 5;
}
```

@cmungall what alternative are you proposing?

**Comment by cmungall** [comment]
Phenotype was always an individual phenotypic feature. The multiple cardinality was to allow for owl intersection. This was overkill

**Comment by julesjacobsen** [comment]
If we're just sticking to defining a phenotype as an individual ontologyTerm from say HP or MP then that's fine, but what about composing phenotypes from other ontologies  such as the 'large round ears' (PATO:0000586 + PATO:0000411 + UBERON:0001690) or 'white hands with 2-3 finger syndactyly' (PATO:0000586 + PATO:0000323 + HP:0001233 + UBERON:0002398)? In this case  it makes sense to keep them as is. It might be better to remove the negated terms and add a boolean NOT to the whole collection.

**Comment by julesjacobsen** [comment]
Will keep as Phenotype

**Comment by julesjacobsen** [comment]
This should map to ‘PhenotypicFeature’ from the [Biolink model](https://github.com/biolink/biolink-model/blob/f379e28d5d4085e1115798c6cb28e5acc4dba8b4/biolinkmodel/datamodel.py#L843-L851) and is referred to as such in the documentation.

**Comment by julesjacobsen** [comment]
@pnrobinson This will require a lot of updating of the documentation!

Should also consider renaming the `phenotypes` field in `Phenopacket` to `phenotypic_features`

**Comment by pnrobinson** [comment]
Agree we should rename to phenotypic_features
I will work on the documentation once a little more dust has settled.

**Comment by julesjacobsen** [comment]
Good breaking change there! Should have made the change 158 issues ago!
