### ISSUE TITLE
bug in documentation

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#20]
This is not the way to include the package in a different project
```
<dependency>
    <groupId>org.phenopackets</groupId>
    <artifactId>phenopacket-schema</artifactId>
    <version>${project.version}</version>
</dependency>
```
This is because ${project.version} is defined for the project and not for the phenopackets schema.

Suggest revising the documentation to say

add the following line to the properties section of the pom file.
```
<phenopackets.version>0.1.0</phenopackets.version>
```

and then add the following to the dependencies section.
```
<dependency>
   <groupId>org.phenopackets</groupId>
   <artifactId>phenopacket-schema</artifactId>
   <version>${phenopackets.version}</version>
</dependency>
```

**Comment by pnrobinson** [comment]
@julesjacobsen do you agree?

**Comment by julesjacobsen** [comment]
We might need to add filtering to the pom. ${project.version} 

```xml
<dependency>
    <groupId>org.phenopackets</groupId>
    <artifactId>phenopacket-schema</artifactId>
    <version>${project.version}</version>
</dependency>
```

in the docs ought to be filtered so the output becomes

```xml
<dependency>
    <groupId>org.phenopackets</groupId>
    <artifactId>phenopacket-schema</artifactId>
    <version>0.1.0</version>
</dependency>
```

We absolutely want people to use the correct pom. The pom and the schema versions are not the same - we could have v1 and v2 defined in the same pom.

**Comment by pnrobinson** [comment]
I am talking about using phenopacket-schema in a completely different project, where the ${project.version} could be anything at all. So I am just talking about the read the docs. I would also love to know how to syncronise the pom files as above
