### ISSUE TITLE
Rename IscnAllele

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#201]
The "IscnAllele" variant format should be renamed. ISCN describes full karyotypes (i.e. representations of the whole genome), not alleles; and the single elements of ISCN karyotypes (e.g. the `t(8;9;11)(q12;p24;p12)` example used) are referred to as "abnormalities". A full-blown rename for such karyotype elements would be "IscnKaryotypeAbnormality" - but handier suggestions welcome ("IscnAbnormality" ?) ...

Also, it should be made clear that just a single abnormality is being described, instead of an "IscnKaryotype" (however, such could be another/alternative attribute, but may not fit the "list of variants" model...).

**Comment by pnrobinson** [comment]
@julesjacobsen  this seems a good suggestion. I would vote for ``iscnKaryotype`` since in principle somebody might want to represent a normal karyotype here.

**Comment by mbaudis** [comment]
Btw., there is a new (like, this week) online version of ISCN (and book ...). No judgement https://iscn.karger.com.

**Comment by pnrobinson** [comment]
This site seems to require a license...

**Comment by pnrobinson** [comment]
@julesjacobsen @mbaudis The only issue with renaming is that this element is underneath "allele" at present. Can we discuss a solution?

**Comment by mbaudis** [comment]
But it is under "Variant"; so any of `iscnKaryotype` (sounds complete, though) or `iscnAnnotation` ... should be fine.
(Btw., for VCF I appreciate the "allele" use since the VCF "variant" is ... complicated.)

**Comment by julesjacobsen** [comment]
We can use `iscnKaryotype`. The slot is supposed to be for alleles, hence the accompanying `genotype` field, but if ISCN doesn't fit so well into that category, lets go with karyotype.

If agreed, +/-1 this comment and I'll make the change.

**Comment by mbaudis** [comment]
+1, but in documentation that it "may describe individual karyotypic or genomic variations using ISCN syntax, not necessarily complete karyotypes; e.g. `t(14;18)(q32;q21)` alone constitutes a valid annotation" ...

**Comment by julesjacobsen** [comment]
Why not simply `iscnVariation`?

**Comment by pnrobinson** [comment]
@mbaudis why is the above not an allele? ISCN does not describe it this way, but it is assumed to be heterozygous finding, correct?

**Comment by mbaudis** [comment]
@pnrobinson The term "allele" is used for specific genomic variants of genomic loci. ISCN can describe all kinds of genomic "events"; but many of those are not really bound to be "allelic" (try translocations; seems ...odd). In contrast something like VCF describes a specific sequence variation which can be deparsed into existing in 1 (or n) alleles.

Probably the best option, semantically, is to go with the [VRS superclass for genomic alterations](https://vrs.ga4gh.org/en/1.1/terms_and_model.html#variation): "variation". So:

* ISCNvariation for single alterations

... and - and this is an IMO common scenario - optionally:

* ISCNkaryotype

... if the complete karyotype is being annotated (e.g. `47,XX, +21` see e.g. https://coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=AG16714)

**Comment by mbaudis** [comment]
... so this is a +1 for @julesjacobsen 's recommendation, with an additional new parameter :-)

**Comment by pnrobinson** [comment]
@mbaudis the intent of this message is not to fully represent ISCN. A translocation is generally heterozygous and can easily be represented as an allele.

**Comment by pnrobinson** [comment]
the DS example is harder to represent as an allele. So what about ``iscnKaryotype``

**Comment by julesjacobsen** [comment]
`iscnKaryotype` it will be...
