### ISSUE TITLE
Mappings for Sex and KaryotypicSex

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#202]
@mellybelly can you find some mappings between these value sets and some official versions?

https://phenopackets-schema.readthedocs.io/en/latest/sex.html

https://phenopackets-schema.readthedocs.io/en/latest/karyotypicsex.html

@rrfreimuth would mapping the enums to external value sets work for you? This would make things easy for developers using the data and also provide a defined external context.

**Comment by mellybelly** [comment]
@volcs0 what is COG using now for this purpose?

**Comment by julesjacobsen** [comment]
I suggest we map the Sex elements like this:

UNKNOWN_SEX -  [NCIT:C17998](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17998)
MALE - [NCIT:C46112](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C46112)
FEMALE - [NCIT:C46113](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C46113)
OTHER_SEX - [NCIT:C45908](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C45908)

**Comment by volcs0** [comment]
As far as I know, COG has no comprehensive strategy for this. Forms are built using caDSR elements, and those are harmonized (sometimes) to what's in the EVS.

What we've done for our pediatric rhabdomyosarcoma dictionary is this: 

Male - [C0086582](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0086582)
Female - [C0015780](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0015780)
Unknown - [C0439673](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0439673)

We're trying to pull COG in line with these principles. The caDSR team maintains some mappings - I could being Denise Warzel into the conversation for her perspective.

Here is our current draft data dictionary - https://www.dropbox.com/s/ijgukaf1d84doj3/INSTRuCT%20Data%20Dictionary%20v1.0%20%28Final%20Draft%29%20%281%29.xlsx?dl=0


 
--
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
  |   |   | Male | IPVC01001
Female | IPVC01002
Unknown | IPVC00001
  |   |   |   |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |   |   |   |  
  |  
  |  
  |  
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |   |   |   |  
  |  
  |  
  |  
  |  
  |   |   |   |  
  |  
  |  
  |  
  |   |   |   |  
  |  
  |  
  |

**Comment by julesjacobsen** [comment]
Thanks @volcs0 looks like we're looking mostly at the same mappings, however you have mapped to one level up the ontology to define 'male'  as

>An animal who is observed by researcher or clinician to be male, the sex that ordinarily produces sperm. [ NCI ] 

and 'female' as

> A person who belongs to the sex that normally produces ova. The term is used to indicate biological sex distinctions, or cultural gender role distinctions, or both. [ NCI ]

These definitions also include chromosomal sex and gender sex, which we're not trying to define here.

**Comment by rrfreimuth** [comment]
> @rrfreimuth would mapping the enums to external value sets work for you? This would make things easy for developers using the data and also provide a defined external context.

Mappings would be helpful, and should be documented as a minimum, in my opinion.  However, I think we should strive to use coded concepts when they are available.  Is there a reason not to make this an OntologyClass?  Free text has a way of drifting from the intended representations.

**Comment by julesjacobsen** [comment]
@rrfreimuth yes, these mappings will be clearly documented.  These fields are in no way free text, they are the only valid values e.g. they are enumerated types, which in protobuf are an ordered, pre-defined, inextensible, finite set of constants which we have defined the meaning of within the documentation. We have attempted to take a pragmatic approach to these fields and defined the terms internally as these are very likely not to change and it is easier for an application developer to work with constants defined within the system than it is to have to look-up and translate a set of externally defined values.

In a previous version there was no Sex class, only OntologyClasses, but this is just an opaque data container from an application developer's perspective. The logic would run like this:

``` java
OntologyClass sex = individual.getSex();

// check if individual is male
if (equivalentOfMale(sex)) {
    // do male things
}

boolean equivalentOfMale(OntologyClass sexClass) {
   // here we need to do something like this
   return sexClass.getId.().equalsIgnoreCase("NCIT:C46112");
  // or hopefully something more clever
  // it's entirely possible that the provided OntologyClass was completely inappropriate 
}
```

However defining sex as an enumerated type, the compiler will check that we have a legal value when the message is created and it is a pre-defined contract between sender and receiver:

``` java
Sex sex = individual.getSex();

// check if individual is male
// n.b. Sex is strictly one of a set of constants. There can be no other legal value.
if (sex == Sex.MALE) {
    // do male things
}

```

**Comment by mellybelly** [comment]
@julesjacobsen wouldn't we want chromosomal sex for Phenopackets purpose? 

This is rather hard to disentangle elsewhere and so a few years back I had put some concepts into PATO to distinguish, but I think we should fix this in NCIT if we are not happy with those definitions. 

take a look at male as a subclass of biological sex: http://purl.obolibrary.org/obo/PATO_0000384
vs
male genotypic sex as a subclass of genotypic sex: http://purl.obolibrary.org/obo/PATO_0020001

Still seems to be a tricky subject. Need to be clear on the requirements i think?

**Comment by julesjacobsen** [comment]
This issue petered-out and we've reached release 1, so I'm closing this.

**Comment by rrfreimuth** [comment]
FYI, this is still very much a work in progress within HL7:

http://hl7.me/GHP
 https://confluence.hl7.org/display/VOC/Gender+Harmony+Context+Definitions
