### ISSUE TITLE
Change schema diagram to be a directed graph

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#203]
Currently the schema diagram looks like this: 

![graph](https://user-images.githubusercontent.com/1576670/63360680-b27b0d00-c366-11e9-9d4c-c66b9f94efec.png)

Given the schema elements are all composed of more basic elements, it might be more informative to the reader to see this as a directed graph with arrows.

**Comment by pnrobinson** [comment]
@julesjacobsen Is this issue moot given we are moving to v2 and will require more sophisticated graphics? If so can we close? Or can we generate the figure with arrows for now?

**Comment by julesjacobsen** [comment]
I was planning on re-doing this via draw.io which can display it in all its gory details.

**Comment by julesjacobsen** [comment]
Now looks like this

![graph](https://raw.githubusercontent.com/phenopackets/phenopacket-schema/v2/docs/graph/phenopacket-schema-v2.svg)

I think this is a big improvement over the original.

**Comment by pnrobinson** [comment]
LOVE IT!
One suggestion to declutter a bit would be to remove commonly used classes such as Ontology and TimeElement and to essentially regard them as primitives for the purposes of this graphic.

**Comment by julesjacobsen** [comment]
:) Great suggestion, @pnrobinson  How do you like this. I agree that it looks clearer. 
![phenopacket-schema-v2 0-simplified](https://user-images.githubusercontent.com/1576670/115215088-0e2d0900-a0fb-11eb-8c04-18426bee0a3d.png)

Will also go ahead and re-do the v1.0 schema in this style.

**Comment by julesjacobsen** [comment]
A bit of colour never hurt -  @lindsmith requested the coloured versions be reinstated as ISO feedback. So here it is, in GA4GH ish colours.

![graph](https://raw.githubusercontent.com/phenopackets/phenopacket-schema/v2/docs/graph/phenopacket-schema-v1-overview.svg)

And for v2.0
![graph](https://raw.githubusercontent.com/phenopackets/phenopacket-schema/v2/docs/graph/phenopacket-schema-v2-overview.svg)
