### ISSUE TITLE
Mappings for chromosomal aberrations

### ISSUE THREAD

**Issue by volcs0** [phenopackets/phenopacket-schema#204]
Apologies if this is the wrong forum for this question.

We have an international group working on a data dictionary for pediatric AML. One thing that is bothering me is the semi-exhaustive and growing list of chromosomal aberrations to track. 
See attached for an example.
<img width="1675" alt="Screenshot 2019-08-20 15 19 48" src="https://user-images.githubusercontent.com/799188/63381413-3e3c6b80-c35e-11e9-8e94-cad43c1cc093.png">
 
As you can see, this is unsustainable. As we move forward in building the data dictionary, is there a better way we can think about this?
Thanks.
-sam
@mellybelly any thoughts?

**Comment by mellybelly** [comment]
@pnrobinson @mbrush @cmungall 
what is current best practices now? I know this is where HGVS falls short, but i can see how similar to SNPs one needs an identifier for each one. I don't think NCIT is the answer to that.

**Comment by pnrobinson** [comment]
@volcs0 this issue is independent of phenopackets. But can you specify what exactly is unsustainable? Most of the alterations are shown as ISCN strings -- which is unwieldy but afaik there is nothing simpler. How does your system/project generate the findings?

**Comment by julesjacobsen** [comment]
Closing this as this is not a phenopacket-related issue.
