### ISSUE TITLE
Ensure that the CVCL prefix is in a curie context file

### ISSUE THREAD

**Issue by saupchurch** [phenopackets/phenopacket-schema#206]
RNAget is planning to recommend the cellosaurus ontology (CVCL) as an option for cell line.  Is CVCL in a curie context file?

**Comment by mellybelly** [comment]
adding few folks to follow up on this. @cmungall @kshefchek @jmcmurry @mcourtot @mbaudis

Generally I think we need a GA4GH context file, and can be registered in PrefixCommons. 

The only use of CVCL in in PC now is SciCrunch, and I would recommend using CVCL natively. There are also likely identifier issues in Cellosaurus that need review.

For the release, I would use the CLO and punt on this one until we can refine. Sorry for sending you down a rabbit hole.

**Comment by mbaudis** [comment]
AFAIK, `cellosaurus` is the registered prefix? Cellosaurus ids start with `CVCL_`, but that is already in their local part. @AmosBairoch can tell you more ...

**Comment by julesjacobsen** [comment]
While this is an important issue, it's really not a phenopacket issue. This is more a workstream 1 task isn't it?

**Comment by mbaudis** [comment]
@julesjacobsen Yes, not PFX; just ended up here :-)
