### ISSUE TITLE
[SOLVED] phenopacket_test.py doesn't work 

### ISSUE THREAD

**Issue by sasurfer** [phenopackets/phenopacket-schema#207]
following the instructions in the src/test/python/README.md file the phenopacket_test.py still doesn't work because it miss the validate_pb.py file.
This worked for me:
First: download and install the protobuf-compiler 
Second: go to the target/protoc-dependencies and find the name of the dir that contains the validate dir. Let's suppose for sake of clarity that its name is d0bc30131c9573266a593b55aa01c994 and the other dir that doesn't contain validate is a7041998579b3121945d2b1fbf4a6fd1. Then to obtain the pb2 file needed:
protoc  -I../a7041998579b3121945d2b1fbf4a6fd1/:. --python_out=. validate/validate.proto
put the validate dir where you put the phenopacket_test.py and the other pb files and it works.

I didn't make a pull request because I don't know how you wanna insert this info into the project. maybe changing src/test/python/README.md could be the more effective way.

**Comment by julesjacobsen** [comment]
Can you write this up in some bash steps please?

The official docs for this are here:

https://github.com/envoyproxy/protoc-gen-validate#python

Which maintains there is no need for a specific compilation step for Python.

**Comment by julesjacobsen** [comment]
If this is a bit too experimental (noting that the C++ support is partially implemented), it might be best to revert these changes.

**Comment by sasurfer** [comment]
My goal? 
make the python test work

What's the test file? 
phenopacket_test.py

Where is it? 
 /path_to_extracted_dir/phenopacket-schema/src/test/python/

What goes wrong following the instructions in Readme.md (same directory as above)? 
Traceback (most recent call last): File "phenopacket_test.py", line 10, in <module> from base_pb2 import Individual, Sex, PhenotypicFeature, OntologyClass File "/home/jules/python_envs/phenopacket-schema/base_pb2.py", line 18, in <module> from validate import validate_pb2 as validate_dot_validate__pb2 ImportError: cannot import name 'validate_pb2'

Can I use protoc gen validate?
Apparently no. In protoc-gen-validate github site is written "Only proto3 syntax is currently supported"

What's my solution?
create the file validate_pb2.py

How did I do that?
Ignoring the commands that set the environment the steps are the following:
1-From the  /path_to_extracted_dir/phenopacket-schema/ dir install.
shell command:
./mvnw clean install
this generate in ./target/generated-sources/protobuf/python/  pb2 files that are needed to exec the python test example
2-Copy the generated pb2 file to the test example dir:
shell command:
cp  ./target/generated-sources/protobuf/python/* ./src/test/python/
3-install the protoc compiler.  Anyway you do it it's fine. for instance, as you proposed:
shell command:
 ./mvnw assemble
4-find the dir where validate proto has been extracted:
shell commands:
VALDIR=`find . -name validate| sed 's/validate//'`
HASHDIR=$(basename $VALDIR) 
cd $VALDIR
HASHDIR2=`ls ../ | grep -v $HASHDIR`
protoc -I../$HASHDIR2/:. --python_out=. validate/validate.proto
5-copy the validate dir where the test example lies.
shell command:
cp -r validate ../../../src/test/python/
6-Now I can go to the test dir and run the test program:
shell command:
cd  ../../../src/test/python/
python phenopacket_test.py

Regards
Giovanni

**Comment by julesjacobsen** [comment]
Thanks for your help Giovanni. I'm going to remove the validate.proto stuff for the time being as this also impacts the C++ code, it's still an alpha project and it doesn't quite have the right functionality.

**Comment by julesjacobsen** [comment]
Removed in commit: 6c58fe2c3ae7ca9a2a0d40c9db6584a9ca816764
