### ISSUE TITLE
FHIR

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#21]
The rare disease FHIR example seems to use a lot of FHIR code to construct the FHIR message. Can we work on creating the FHIR export function directly from the Phenopacket of the main rare diseas example?

**Comment by pnrobinson** [comment]
@julesjacobsen @drseb @mellybelly Do we have a use case for this in SOLVE-RD by chance? What is the current status of the FHIR export?

**Comment by julesjacobsen** [comment]
I guess we ought to have a PFX -> FHIR conversion at one point. The FHIR code is there so we can have an equivalent FHIR bundle to represent the example text of the rare-disease, cancer and biosample cases.

**Comment by julesjacobsen** [comment]
The ```CancerFhirExample``` is merely meant to be a parallel illustrative example of how this would be encoded using FHIR.
