### ISSUE TITLE
MIABIS

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#215]
Does our [Biosample](https://phenopackets-schema.readthedocs.io/en/latest/biosample.html) map well to the [MIABIS](https://github.com/MIABIS/miabis/wiki) standard?

https://github.com/MIABIS/miabis/wiki

**Comment by pnrobinson** [comment]
@mbaudis I wonder if you have advice about the extent to which phenopackets should support this? We would like to keep phenopackets small-ish so that it can be combined modularly with other GA4GH standards, but at the same time the Biosample is a key component that should have interoperability with MIABIS. We should also ask Ian Fore about this.

**Comment by mbaudis** [comment]
Pinging @mcourtot  here...

**Comment by mcourtot** [comment]
From the Phenopacket point of view I think you'd want interoperability but not full coverage? The relevant portion of MIABIS is probably the sample related attributes - I don't think there is interest in phenopacket in representing biobanks admin data for example. 

On a side note we could do a cute analysis here, using the MIABBIS checklist against our BioSamples Phenopackets export and see what is compliant or not.

**Comment by julesjacobsen** [comment]
Well, we have a partial mapping. 

https://github.com/BBMRI-ERIC/miabis/blob/master/Data-describing-Sample.md - maps to a `Biosample`

> Introduced in 2020 ([Eklund et al., 2020](https://www.liebertpub.com/doi/10.1089/bio.2019.0129)), the component <strong>Sample</strong> is a portion or quantity of biological material that is collected from a sample donor, or which is a digital representation of a biological entity of the sample donor, such as an image. 
> 
> | Attribute Code | Attribute Name | Allowed Values | Description | Constraints | Cardinality | 
> | --- | --- | --- | --- | --- | --- |
> | MIABIS-SAMPLE-01 | Sample ID | Coded string | Unique ID of the sample within a sample collection, often represented by the sample barcode; text identifier. Sample ID meant for sharing. | Pseudonymized, alphanumeric. It is recommended that sample IDs will be persistent within a given biobank. | 1 |
> | MIABIS-SAMPLE-02| Detailed sample type| Text list| The sample type saved from a biological entity for testing diagnostic, propagation, treatment or research purposes| | 1|
> | MIABIS-SAMPLE-03| Sample storage temperature| List: RT, 2oC to 10oC, -18oC to -35oC, -60oC to -85oC, <-135oC, Liquid nitrogen vapor phase, Liquid nitrogen liquid phase, Other| The long term storage temperature at which the sample is stored after preparation, based on SPREC v3 and [MIABIS-2.0-15](https://github.com/MIABIS/miabis/wiki/Structured-data-and-lists#storage-temperature)| | 0|
> | MIABIS-SAMPLE-04| Sample creation date and time| yyyy-mm-ddThh:mm:ss| The date and time the sample was created in the form currently described in MIABIS-SAMPLE-02 Detailed material type. Format according to ISO8601. Could also be partial, for example, YYYY| | 0|
> | MIABIS-SAMPLE-05| Anatomical site ontology| String| Name of ontology used for describing the anatomical source of the sample material, for example, ICD-O-3 topography code| MIABIS-SAMPLE-05 and MIABIS-SAMPLE-06 are required if any ontology information is provided| 0/1|
> | MIABIS-SAMPLE-06| Anatomical site ontology version| Coded string| Version of selected ontology for anatomical site| MIABIS-SAMPLE-05 and MIABIS-SAMPLE-06 are required if any ontology information is provided| 0/1|
> | MIABIS-SAMPLE-07| Anatomical site ontology code| Coded string| Anatomical site code from the selected anatomical site ontology version| MIABIS-SAMPLE-05 and MIABIS-SAMPLE-06 are required if any ontology information is provided| 0|
> | MIABIS-SAMPLE-08| Anatomical site ontology description| String| Description from the selected anatomical site ontology code| MIABIS-SAMPLE-05 and MIABIS-SAMPLE-06 are required if any ontology information is provided| 0|
> | MIABIS-SAMPLE-09| Anatomical site free text| String| Explanation about Anatomical site in case of unknown Anatomical site or insufficient information| MIABIS-SAMPLE-05 and MIABIS-SAMPLE-06 are required if any ontology information is provided| 0|
> | MIABIS-SAMPLE-10| Sample content diagnosis| Text list| The ICD-10 diagnosis code describing content of the sample, such as whether the sample contains cancerous material | | 0...n|
> | MIABIS-SAMPLE-11| Use restrictions| Text list| The restrictions that may change the availability of the samples donated by the sample donor| | 0...n|
> 


https://github.com/BBMRI-ERIC/miabis/blob/master/Data-describing-Sample-Donor.md - maps to an `Individual`

> | Attribute Code| Attribute Name| Allowed Values| Description| Constraints| Cardinality|
> |---|---|---|---|---|---|
> | MIABIS-SAMPLEDONOR-01| Sample donor ID| Coded String| Sample donor ID. Unique ID code of the sample donor within the sample collection/biobank| Pseudonymized, alphanumeric| 1|
> | MIABIS-SAMPLEDONOR-02| Sex| Text list| Biological sex of the sample donor. MIABIS-2.0-9| | 1|
> | MIABIS-SAMPLEDONOR-03| Data categories| Structured data| The data categories from which data are available or can be linked to the sample donor. Can be several values (list modified after MIABIS-2.0-13).| | 0...n|
> | MIABIS-SAMPLEDONOR-04| Birth date| yyyy-mm-ddThh:mm:ss| Birth date of the sample donor. Coding ISO8601. Can also be partial, for example, YYYY.| Date of birth is required when Event date (MIABIS-EVENT-02) is used, otherwise partial date, as in birth year, can be used| 0|
> 
>
