### ISSUE TITLE
Age

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#22]
Can we document the format conventions for Age, as in:
```
Age.newBuilder().setAge("P48Y3M").build()
```
Does this just mean the proband (P) is 48 years and 3 months old? Where does the P come from? It seems the code is treating it as a string

**Comment by pnrobinson** [comment]
@julesjacobsen is this an ISO code for age? I have never seen the "P" before.

**Comment by julesjacobsen** [comment]
@pnrobinson the 'P' is the ISO 8601 for a time duration ('P' probably stands for 'Period')

https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by pnrobinson** [comment]
Then it is wrong for this use case! We need to document

**Comment by pnrobinson** [comment]
No actually it is ok -- it is the period of time from birth. Let's just document this!
