### ISSUE TITLE
Where is the best place to put IDs?

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-schema#220]
Dear Phenopacket development team,
I work on a project where I want to use phenopacket schema to represent individuals from families segregating Mendelian diseases.

Within the project, I have 3 types of identifiers:
- family ID (FID)
- sample ID (PID), and
- experiment ID (EID)
and I want to find the best place within the phenopacket schema to put the IDs.

FID is an obvious one, it goes to `family.id`. Then, for each family member, PID goes either to `family.proband.subject.id`, or `family.relatives[0].subject.id`, while also being placed to `persons` within `family.pedigree`.
Now here comes the question. There are possibly multiple EIDs for the same PID (e.g. exome and genome of the same individual). Given I want to create a single `Family` element representing this case, where should I put EIDs?

Problem with using plain `family.proband.hts_files` is that there is no place where to put EID within the HtsFile element (unless I put it into `description`). Moreover, I have multiple files from the same experiment (BAM files, gVCF per chromosome, etc..)

One way how to store the experiment data would be to create Biosample element. Then, we would store EID as `biosample.id`, PID as `biosample.individual_id`, and all the data into `biosample.hts_files`.
However, the current documentation mainly describes use cases for oncology, which discourages me from using Biosample for rare-disease exome/genome purposes.

What would you recommend, in order to follow SOPs (spirit of phenopacket)?
Thank you,
Daniel

**Comment by pnrobinson** [comment]
@ielis @julesjacobsen can we touch bases about this?

**Comment by julesjacobsen** [comment]
Hi @ielis this might be one of the tardiest responses, almost certainly not ever, but still. Sorry!

I think the answer to your question is here: https://phenopackets-schema.readthedocs.io/en/latest/file.html#individual-to-sample-identifiers

See also https://phenopackets-schema.readthedocs.io/en/latest/pedigree.html

> If a Phenopacket is used to represent any of the individuals listed in the Pedigree, then it is essential that the individual_id used 
 in the pedigree matches the id of the subject of the Phenopacket. It is allowable for the Pedigree to have individuals that do not have an associated Phenopacket. This is useful, for instance, if the Pedigree is being used to store the affected/not affected status of family members being examined by exome or genome sequencing. In this case (i.e. where there are no associated phenopackets for the Pedigree.individual_id), it is expected that the individual_id elements match the sample identifiers of the exome/genome file.

Does this make sense?
