### ISSUE TITLE
Associate evidence with genomic interpretation

### ISSUE THREAD

**Issue by AlgyTaylor** [phenopackets/phenopacket-schema#223]
Hi all,

Hope you're all keeping safe in these unusual times!

I'm Algy Taylor - from the Manchester Centre for Genomic Medicine, UK.  I've been working on a piece of software that pretty much fills your use-case perfectly - an extension to an EHR to cover phenotypic information!  I've gone over your schema with great interest, and am generally a fan.  It incorporates a lot of ideas that I'd (independently) come across, and improves on areas that I'd identified as weaknesses.

One particularly useful thing is the ExternalResource element.  For example, pedigrees - I think probably won't be translated electronically in clinical use.  However, uploaded images of hand-drawn pedigrees are more likely - so ExternalResource, within metadata, has been really useful in that respect.

An area of the application that's not covered is that we have found it particularly useful within the application to store the evidence used (according to [the 2015 ACMG guidelines](https://www.nature.com/articles/gim201530)) to come to the interpretation.  At the moment, there's no logical location to store this within the [GenomicInterpretation](https://phenopackets-schema.readthedocs.io/en/latest/interpretation.html#genomicinterpretation) (be97c610) 'Evidence'-type element to do this.

Is it worth incorporating this into the schema?  We typically record them as recommended in the guidelines (PP4, PM2, etc).  This, of course, only covers variants using those particular guidelines, and there's another, newer, set for (I think) CNVs - forgive me if I'm wrong there.

Best wishes
Algy

**Comment by julesjacobsen** [comment]
Hi Algy, thanks for the feedback and I'm really heartened to hear that this has been useful to you and fits your problem well. I'm really sorry about the late response.

Regarding the Pedigree data, I'm glad you managed to find an element in the MetaData you could repurpose for this, even though a PDF isn't the most openly computable format. Ideally the Phenopacket would contain cleaned data for ease of computation rather than input/storage, but obviously this isn't possible in live EHR systems.

For the ACMG guideline codes what, if anything other than the codes themselves do you record? Is it simple a list of them attached to the variant, or some extra evidence attached to the code as well? Presumably the finding (Pathogenic/likely pathogenic/benign etc.) is recorded too?

I was originally going to incorporate these but eventually decided not to as this was falling within the remit of the GA4GH GKS (Genomic Knowledge Standards) [Variant Annotation](https://ga4gh-gks.github.io/variant_annotation.html) group and I didn't want to create extra noise before they had defined their scope. I confess that I'm not up to speed on where they are right now, but the meeting minutes can be found here:  https://docs.google.com/document/d/15eF5T7nBkLA8NiZ4Vas3gRQgvQfvyh7Yvj9J9pOp9Ic/edit#

I'm not averse to adding the ACMG codes into phenopackets, but I don't want to become a bad standards citizen by doing so!

**Comment by AlgyTaylor** [comment]
Hi Jules,

Thanks for the reply.  For the ACMG codes, we store the evidence code along with a possible strength modifier (for the ones where the evidence can be interpreted as different strengths).  We then use those to calculate a pathogenicity score based on the method in the [Tavtigian paper](https://pubmed.ncbi.nlm.nih.gov/29300386/).

I agree with you on the pedigree data, but as you can probably imagine it's mostly a case of trying to get as much data as we can out of the existing process, and clinically (at least in the area I'm working in) there's not a lot of value in digitising the pedigrees at the moment.

As a thought, is it worth showing you the system that we're currently building?  Thought it might be interesting from your perspective to see an implementation of it, and certainly for me it'd be useful to hear your thoughts!  My email address is my firstname [dot] lastname [at] mft [dot] nhs [dot] uk - hopefully my github username will help you fill in the blanks! :)

**Comment by pnrobinson** [comment]
@AlgyTaylor it would be great to get your feedback on this issue. We are hoping to finalize the v2 phenopackets now in early 2021. I will send you and @julesjacobsen an email to coordinate.
Also, this should be discussed in the GA4GH meeting Dec 17, 9AM East Coast US time if you can join.

**Comment by pnrobinson** [comment]
@julesjacobsen @AlgyTaylor have we come to a decision on this issue? I think the VA group is developing a framework that would allow us to represent the ACMG criteria, but this might not be ready in time for the v2 phenopackets release?

**Comment by AlgyTaylor** [comment]
Hi @julesjacobsen, @pnrobinson ,

It'd be fantastic if it were possible to incorporate whatever the VA group come up with.  Would it maybe be possible to release Phenopackets v2 without it, then update it to v2.1 once that information comes to light (assuming it doesn't massively break compatibility)?

I think, at least in hindsight, it's worth being cautious since there's another set of guidelines for a different type of mutation that our cancer team deal with ... I'm going to say it might be CNVs, although I'm far less familiar with the cancer side of things so I might be completely wrong there!

**Comment by julesjacobsen** [comment]
Hi @AlgyTaylor, it looks like incorporating VA will have to be the case as we're too close to the submission deadline to squeeze in the VA and I'm not sure that that is even ready for use anyhow. It's still on the cards for v2.1+ however.

Are you referring to the paper ["Technical standards for the interpretation and reporting of constitutional copy-number variants: a joint consensus recommendation of the American College of Medical Genetics and Genomics (ACMG) and the Clinical Genome Resource (ClinGen)"](https://www.nature.com/articles/s41436-019-0686-8)?

I wonder if there is a happy middle-ground where it is possible to capture the relevant details,but not over-model things. For example

```proto
message AcmgFinding {
    enum PathogenicityStatus {
        UNCERTAIN_SIGNIFICANCE = 0;
        PATHOGENIC = 1;
        LIKELY_PATHOGENIC = 2;
        LIKELY_BENIGN = 3;
        BENIGN = 4;
    }
    PathogenicityStatus pathogenicity_status = 1;
    
    AcmgCriterion supporting_criteria = 2;
    
}
message AcmgCriterion {
    // e.g. PVS1, PS2, BS1...
    string code = 1;
    // free-text for human explanation
    string note = 2;
}
```

Not sure what you lot need/want to be able to communicate, but some sort of basic requirements could be helpful.

**Comment by AlgyTaylor** [comment]
Hi @julesjacobsen 

Yeah, that's really close to how we're storing it at the moment.  The only differences I can think is that the AcmgFinding on our side has a `contribution_to_phenotype` that can be either, `full`, `partial`, or `none`.

The `AcmgCriterion` is also very close.  The only difference I can see is that, alongside those two string values, there's an ENUM which allows a (usually non-default) strength to be specified, since some of the criteria have variable strength (e.g. segregation data).

The paper in question is this one: https://www.acmg.net/docs/Standards_Guidelines_for_the_Interpretation_of_Sequence_Variants.pdf

Although at some point we'll have to look at the other one you posted since that's used for CNVs.

**Comment by julesjacobsen** [comment]
I'd just like to state that the `AcmgCriterion` etc was a two-minute off the top of my head job and _not_ a solid proposal! Anyway - let's wait for post v2 and see what the VA group have come up with before going any further with this.

**Comment by AlgyTaylor** [comment]
Hehe, yeah ... well, if it did end up being something like you'd suggested `AcmgFinding`/`AcmgCrtierion`, that'd be excellent from my point of view, since it pretty much mirrors what we store anyway :). Be interesting to see what the VA group come up with.

**Comment by julesjacobsen** [comment]
@AlgyTaylor - we've done a bit more work on the interpretation and in particular the [variant interpretation/finding](https://github.com/phenopackets/phenopacket-schema/blob/1c560dbe649444286967a6446604722e62188e14/src/main/proto/phenopackets/schema/v2/core/interpretation.proto#L65-L75) could you please comment on this:

https://github.com/phenopackets/phenopacket-schema/blob/v2/src/main/proto/phenopackets/schema/v2/core/interpretation.proto

Note that the interpretation is now a element of a phenopacket (see line 41):

https://github.com/phenopackets/phenopacket-schema/blob/1c560dbe649444286967a6446604722e62188e14/src/main/proto/phenopackets/schema/v2/phenopackets.proto#L25-L58

**Comment by julesjacobsen** [comment]
Going to close this as I think we've addressed the main point. of this. @AlgyTaylor please re-open if this is not the case.
