### ISSUE TITLE
How to specify Gestational age?

### ISSUE THREAD

**Issue by mshadbolt** [phenopackets/phenopacket-schema#224]
Hello

I am investigating whether I could implement using the phenopackets standard but I can't figure out how one would specify the age of an embryo or fetus i.e. gestational age?

I tried searching the schema documentation and previous issues but couldn't find any information. The age fields seem to only be valid for an amount of time after birth.

Please let me know if there is a way to do this.

**Comment by pnrobinson** [comment]
Have you considered using a term from the Human Developmental Stages ontology:

https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http://purl.obolibrary.org/obo/HsapDv_0000072

If you could provide a description of your requirements then we would be happy to extend the documentation to provide some recommendations.

**Comment by mshadbolt** [comment]
So in an example where I have an embryonic sample with id F78, sex female, and gestational age of 5 weeks. 
Logically I would want to specify the age of the fetus within the 'individual' block, but the 'age' only allows Age or AgeRange, neither of which could be used to specify a gestational age? since they must be an ISO8601 duration and there isn't a way of specifying it is gestational, unless I have misinterpreted the docs?

The other issue with using the hsapdv ontology is that there is no 'week' measurement in the embryo stages, so if I don't the carnegie stage of a fetus it needs to have a very broad ontology term that isn't usually very useful.

Are you suggesting I list gestational age as a phenotypic feature? 
So would it look something like:

```
"individual": {
  "id": "F78",
  "sex": "FEMALE"
}
"biosamples": [{
    "id": "F78",
    "individualId": "F78-donor",
    "description": "embryonic donor",
    "phenotypicFeatures": [{
      "description": "gestational stage",
      "type": {
        "id": "HsapDv:0000006",
        "label": "blastula stage"
      }
    }, {
      "description": "gestational age in weeks
      "type": {
        "id": "UO:0000034",
        "label": "week"
      }
    }
    }],
    "taxonomy": {
      "id": "NCBITaxon:9606",
      "label": "Homo sapiens"
    }
  }]
```

I also don't really understand how I assign a value if I wanted to specify a gestational age, in the example above is there a way to specify '6' gestational weeks? I feel like a 'value' field could be useful.

**Comment by julesjacobsen** [comment]
Hi Marion, this is a great question.  I think what @pnrobinson was suggesting was using the ontology term in the age field (although this isn't possible) e.g.

```json
"individual": {
  "id": "F78",
  "sex": "FEMALE"
  "ageTypeAtCollection":
      "type": {
        "id": "HsapDv_0000024",
        "label": "Carnegie stage 17"
      }
}
```

It's also not all that readable. What would you think of creating a convention for using a negative ISO8601 period? e.g.

```json
"individual": {
  "id": "F78",
  "sex": "FEMALE"
  "age": {
    "ageAtCollection": "-P6W"
  }
}
```

Where negative periods denote prenatal ages e.g. "-P6W" would mean 6 weeks gestational age, "-P40W" would be a full term pregnancy. The drawback to this would be that it is a convention and therefore somewhat fallible and also doesn't specify between gestational and fertilized ages.

So perhaps a different solution would be to have an explicit `gestationalAge` field? e.g.

```json
"individual": {
  "id": "F78",
  "sex": "FEMALE"
  "age": {
    "gestationalAge": "P6W"
  }
}
```

**Comment by pnrobinson** [comment]
See issues https://github.com/phenopackets/phenopacket-schema/issues/248
