### ISSUE TITLE
LiveState

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#229]
Can we change the name of this element to ``vital_status``?

```
 
message LiveState {
    bool deceased = 1;
    TimeElement time_of_death = 2;
}
```
would become
```
message VitalStatus {
    bool deceased = 1;
    TimeElement time_of_death = 2;
}
```

ICGC has an enum called vital_status with alive, dead, unknown, and also an age of death field.

**Comment by julesjacobsen** [comment]
Absolutely. I'd already done this but was trying to decide how/ whether or not to do this:

```proto
message VitalStatus {
    onof status {  
        boolean deceased = 1;
        TimeElement time_of_death = 2;
}
```

**Comment by julesjacobsen** [comment]
But I do like the Enum as it gives a bit more clarity about the status:

```proto
message VitalStatus {
    enum Status {
        UNKNOWN = 0;
        ALIVE = 1;
        DEAD = 2;
    }
    Status status  = 1;
    TimeElement time_of_death = 2;
}
```

**Comment by pnrobinson** [comment]
I agree that the enum is better!

**Comment by julesjacobsen** [comment]
This is also a logical slot to add a cause of death (OntologyClass). In the COVID-19 case there were a lot of underlying health problems, but it was (arguably) COVID-19 which was the cause of the patient's death.

**Comment by pnrobinson** [comment]
implemented!
