### ISSUE TITLE
sex and gender

### ISSUE THREAD

**Issue by heikkil** [phenopackets/phenopacket-schema#232]
This is another (#231) complex issue that still needs to be tackled. 

The discussion last night emphasized that the phenopackets sex is the biological feature that can be determined by text. It was suggested that it should be stated more strongly, perhaps  in the name.  Gender is a more fluid entity that has to be asked from the person. Sounds like a great target for an ontology. Does such an ontology exist?

**Comment by julesjacobsen** [comment]
We've mapped to the Ontology terms in NCIT for this - see https://phenopackets-schema.readthedocs.io/en/latest/sex.html

Gender is another matter and there are a great deal of people cogitating on this within the [FHIR gender harmony group](https://confluence.hl7.org/display/VOC/The+Gender+Harmony+Project)

**Comment by mbaudis** [comment]
I am not getting why the mapping is needed & not an ontologyTerm with recommended values (as are shown in the documentation) is being used?

**Comment by cmungall** [comment]
Hi @heikkil long time no see!

Just as hANCESTRO can be used in #231 can we use GSSPO as the vocabulary here? This is just about to be added to OBO

**Comment by heikkil** [comment]
Hi Chris! Yep, I am back in the infrastructure stuff.

You must mean Gender, Sex, and Sexual Orientation (GSSO) ontology?

Clair A. Kronk and Judith W. Dexheime: Development of the Gender, Sex, and
Sexual Orientation ontology: Evaluation and workflow. Journal of the
American Medical Informatics Association, 27(7), 2020, 1110–1115 doi:
10.1093/jamia/ocaa061

It has everything needed.

     -Heikki

Heikki Lehväslaiho - skype:heikki_lehvaslaiho cell: +358 40 850 6640
http://about.me/heikki

**Comment by heikkil** [comment]
I've been thinking about this recently.

There are three ways of looking into sex in an informative way.
Phenopackets has two. It is either one too many or one missing:

1. chromosomes (and genes) :   Phenopacket:KaryotypicSex
2. secondary, external sexual marks :  Phenopacket:Sex
3. hormonal effects, self-identification : Phenopacket:Gender (?)

     -Heikki

Heikki Lehväslaiho - skype:heikki_lehvaslaiho cell: +358 40 850 6640
http://about.me/heikki

**Comment by pnrobinson** [comment]
Thanks!
I think that we do need to add an element for gender that would be an ontology term. The GSSA could be one option for this.
It would also be good to examine how FHIR and other clinical terminologies deal with this.

**Comment by cmungall** [comment]
> You must mean Gender, Sex, and Sexual Orientation (GSSO) ontology?

Yes, that's the one!

http://obofoundry.org/ontology/gsso

**Comment by pnrobinson** [comment]
It seems NCIT has a collection of terms for gender (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17357)

Would
```
OntologyTerm gender
```
be approppriate?

**Comment by mbaudis** [comment]
@pnrobinson For gender it is o.k. IMO.

**Comment by heikkil** [comment]
Looks great.

     -Heikki

Heikki Lehväslaiho - skype:heikki_lehvaslaiho cell: +358 40 850 6640
http://about.me/heikki
