### ISSUE TITLE
API Version

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#233]
Copying David's comments from the last Subgroup Meeting here. 
Re: the [API version](https://phenopacket-schema.readthedocs.io/en/latest/apiversion.html) - see the approved GA4GH [Service Info](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/README.md) & [Service Registry](https://github.com/ga4gh-discovery/ga4gh-service-registry/blob/develop/README.md) v1 standards.

Also copying in @jb-adams who is working on a registry of GA4GH standards, he may have additional thoughts about this

**Comment by julesjacobsen** [comment]
What were David's comments?

**Comment by lindsmith** [comment]
I'll follow up to make sure I captured this correctly (and cc you), but I believe he was suggesting to look at Service Info & Service Reg and ensure that the new API version field is compatible with those standards. @jb-adams is using Service Info & Service Reg to build a searchable registry of GA4GH standards, where to phenopackets will be listed

**Comment by jb-adams** [comment]
Thanks for looping me in @lindsmith . 

What is the `APIVersion` field meant to capture? Is it the version of Phenopackets that the message/document supports? Or is this talking about versions of other GA4GH specifications? If the former, I don't think it'll present any conflicts with `service-registry`. If it's the latter, or if the new version of Phenopackets is expected to incorporate a web API (e.g. `GET /phenopacket/{id}`), then a discussion with the Discovery Networks group will be necessary.

On another (perhaps unrelated) note, will I (or anyone else) be able to view the documentation for older versions of Phenopackets once newer versions are released at a stable URL? For example:
- `https://docs.phenopackets.org/v1.0`
- `https://docs.phenopackets.org/v1.1`
- `https://docs.phenopackets.org/v2.0`
The reason being is secretariat wants to make sure older versions of GA4GH standards don't disappear once new ones are released.

**Comment by pnrobinson** [comment]
It seems better to stick with the existing field, string phenopacket_schema_version so as not to introduce a breaking feature. The readthedocs will be able to show versions as suggested above!
