### ISSUE TITLE
General Documentation - Element Table Edits

### ISSUE THREAD

**Issue by lindsmith** [phenopackets/phenopacket-schema#235]
Comment:
> Table 2 in section 6.2 (page 9). Specifies a list of messages for the ‘relatives’ and ‘hts_files’ fields. Other tables with these fields such as Table 3 do not explicitly specify a list but do appear to be requesting one based on descriptions.

Proposed Changes:
> It may be a good idea to disambiguate with the approach in Table 2 applied to other tables as well.

For context, Table 2 and Table 3 can be found on pg. 18 & 19 of the [ISO draft](https://drive.google.com/file/d/1XVLgrPT8PZyq1HYga7UQqvPe-TfKaMRI/view?usp=sharing) (not page page 9, as commented above). Equivalent to [this table](https://phenopacket-schema.readthedocs.io/en/latest/family.html) and [this table](https://phenopacket-schema.readthedocs.io/en/latest/cohort.html) found in readthedocs. My interpretation of this comment is that we just need to go through all of the element tables as label "list" where appropriate.

Additional suggestion from the same commenter:
> The meaning of ‘repeated’ as a value for the Status column should be described alongside descriptions of required, recommended, optional in section 5.2.

For context, the commenter is referring to 'repeated' found in the Status column of element tables on [this page](https://phenopacket-schema.readthedocs.io/en/latest/interpretation.html), and is suggesting that we add it to [this section](https://phenopacket-schema.readthedocs.io/en/latest/requirements.html). 'Repeated' is not a requirement level so I'm not sure it makes sense under that heading. We could potentially add a new subsection under Section 5 of the [ISO Draft](https://drive.google.com/file/d/1XVLgrPT8PZyq1HYga7UQqvPe-TfKaMRI/view?usp=sharing) (pg 14 - maybe add a 5.4) or rename the section.

**Comment by pnrobinson** [comment]
@lindsmith I think we have addressed these issues and can close?

**Comment by lindsmith** [comment]
@pnrobinson Yes these have been addressed, we can close
