### ISSUE TITLE
sample-type

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#238]
The Biosample currently has "sample_tissue", but different kinds of material for sequencing can be dervied from a tissue. Therefore, consider adding another field called

sample_type.

This could be an ontology term but would be intended for values such as 

* Amplified DNA
* ctDNA
* Other DNA enrichments
* Other RNA fractions
* polyA+ RNA
* Ribo-Zero RNA
* Total DNA
* Total RNA

(list derived from ICGC)

**Comment by mbaudis** [comment]
@pnrobinson This is complicated, a question of domain:

* If you think of a biosample as biopsy ... type material (IMO the preferable way), many different analysates can be derived from it. It makes much more sense to have the information specifically associated with the analysates (type of purified molecule, purification, labeling, QC ...) part of the "callset" report (i.e. associated with the observed variants). This reflects another hierarchical level - e.g. different analysates (DNA, expression ...) are derived from / "children" of a specific sample.
* When considering per material/analysis you have to duplicate the biosample object with all associated problems.

For me a very clear case for the first option.

**Comment by pnrobinson** [comment]
Proposal is adding a 'derived_from' element to the biosample.
Also add an ontology term for sample type. -- let's name it

**Comment by julesjacobsen** [comment]
This is related to #249 Where I think @mbaudis suggested replacing the `boolean` field `Biosample.is_control_sample` with an `OntologyTerm` in a repeated `sample_type` field? Not sure I like this idea as there are multiple concepts in the same filed being used for slightly different reasons.

**Comment by mbaudis** [comment]
@julesjacobsen Single field `material_type` as OT?

**Comment by pnrobinson** [comment]
@mbaudis @julesjacobsen I think the suggestion is now that we allow one biosample to be dervied from another. Thus, if we derive say RNA from a biopsy, we could represent both as biosamples if that is desired. I think this issue is distinct from the ``is-control-sample`` (boolean) issue (where I think we agreed it would be better to have an ontology term to describe it).

**Comment by mbaudis** [comment]
@pnrobinson @julesjacobsen Good as Peter writes - I'm not overly attached to a specific plane where to draw separation between the biosample as entity and its derived products/measurements. Just slight preferences :-)

**Comment by julesjacobsen** [comment]
This has been added, with a recommendation to use EFO for the field.
