### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#239]
I suggest reviving/rethinking the geolocation object (last [discussed 2019](https://github.com/phenopackets/phenopacket-schema/issues/34)?

A JSON representation of the original GA4GH schema can be found in [SchemaBlocks](https://schemablocks.org/schemas/ga4gh/GeoLocation.html). In the Progenetix project we're using an extended version which also interpolates locations into GeoJSON point objects and adds a `label` and ISO country code (these are mostly for convenience but also for error checks - lat/long frequently get messed up).:

```
		"geo" : {
			"label" : "Antalya, Turkey",
			"precision" : "city",
			"city" : "Antalya",
			"country" : "Turkey",
			"latitude" : 36.91,
			"longitude" : 30.7,
			"geojson" : {
				"type" : "Point",
				"coordinates" : [
					30.7,
					36.91
				]
			},
			"ISO-3166-alpha3" : "TUR"
		}
```

This should provide an example from which to cut down to an "essential" representation.

In any case, geographic attributions are essential as (optional) elements for different types of objects )individual, biosample, experimental procedures...).

**Comment by pnrobinson** [comment]
It seems a geolocation would represent a certain privacy risk, and the use case for genomic analysis is not clear. How essential is this element for the foreseen applications of phenopackets? @mbaudis

**Comment by mbaudis** [comment]
@pnrobinson The `individual` contains DOB, age, sex, alternative identifiers; then you have potentially rare diagnoses, variants ... Anything can be used for privacy breaching attacks.

Regarding the geolocation item:

* In the original design we'd included a `precision` attribute which is helpful for obfuscation; e.g. one can use this to indicate that the given geolocation parameters are somewhere inside the boundaries of the mapped entity (e.g. fall into the same city w/o being verbose). Should probably be a controlled vocabulary...
* This is first and foremost a schema which _per se_ can be connected to any other schema, with different relations. We use this mostly for "place of diagnosis/analysis" since we don't have patient records - and this is already informative at least on an epistemic level (see https://academic.oup.com/database/article/doi/10.1093/database/baaa009/5812711). 

So the geolocation attribute itself is as harmless or privacy breaching as others (but rather less "dangerous" than some).

For the format: `precision` may be adjusted to a better format; the point coordinates are duplicated in the `latitude`, `longitude` parameters (unnecessary but here for readability _and_ as alternative - but Geojson is better as registered / less ambiguous for units...). Pure name based is bad (non-human data - see TARA Ocean; always name errors ...).

Current schema [here](https://progenetix.org/services/schemas/Geodata/).

**Comment by pnrobinson** [comment]
@julesjacobsen @mbaudis From discussions to date I have the impression that there is no defined analysis goal that we want to achieve with Geolocation, and so its addition to the schema (and the additional complexity) might not be justified. Can we close this?

**Comment by mbaudis** [comment]
@pnrobinson Hmmm - very much differing opinion, especially since we have used this & had also long MTT discussions back when. Metagenomics, research epistemology, environmental/cultural/population proxy ... No problem to shelve "beyond v2"; but then, the schema is done & drop in, with IETF (https://geojson.org) at its core:
* https://progenetix.org/services/schemas/GeoLocation/ , with it's components
* https://progenetix.org/services/schemas/GeoJSONgeometry/
* https://progenetix.org/services/schemas/GeoLabels/
