### ISSUE TITLE
sex of individual -- comment is perhaps too narrow

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#24]
Currently the comment for the sex element in individual states the following
```
A PATO term for the biological sex of the individual
    // http://purl.obolibrary.org/obo/PATO_0000047
OntologyClass sex = 5;
```
I think that biological sex and phenotypic sex are nearly synonymous, but it is confusing that we state biological sex in the comment and the PATO term is phenotypic sex.

Also, there are situations where one might want to indicate the genetic sex of an individual and this would be possible by using a different ontology term. I have written the following description in the documentation, do we agree on this?

```
Phenopackets make use of ontology terms to denote the sex of an individual. We recommend using
`PATO terms <https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000047>`_ for this purpose. There are various ways to define sex including phenotypically and genetically, and Phenopackets allows
any ontology term that represents sex in any way to be used. The PATO terms `female <https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000383>`_ and `male <https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000384>`_ represent phenotypic sex. There may be situations when it is more appropriate to use a term such as `male genotypic sex <https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0020001>`_.
   ```

**Comment by cmungall** [comment]
Seems we're inconsistent anyway, we use an enum in the person class in Pedigree

**Comment by pnrobinson** [comment]
The use case for pedigree data is to follow inheritance of variants in a family, and this constrains the meaning of the concept to the point where it does not make sense to allow any flexibility. I would think we can leave this. @cmungall @julesjacobsen

**Comment by julesjacobsen** [comment]
Can we simplify this to use an enum? We're not trying to model gender. These are two existing ways of doing this and it would be *much* simpler to have something we can convert between. 

https://www.hl7.org/fhir/valueset-administrative-gender.html

https://github.com/genomicsengland/GelReportModels/blob/9709c282aab5f1e4e7494042341052c285dadf97/schemas/IDLs/org.gel.models.participant.avro/1.1.0/CommonParticipant.avdl#L7-L20

**Comment by julesjacobsen** [comment]
Changed to enum - used in both Pedigree and Individual
