### ISSUE TITLE
Representation of chemotherapy

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#244]
Often, chemo is represented in the following way:
```
Initial treatment included left mamar sectorectomy, and axillary node dissection. Subsequently, she underwent 4 cycles of epirubicin (240 mg/m2 total dose), cyclophosphamide (2.400 mg/m2) and whole breast radiation with axillary boost (total dose of 50 Grays). As the tumor was established to be estrogen receptor positive, her subsequent medical regime consisted in hormonal therapy with tamoxifen over the next 5 years. 
```

that is, the dosage is given relative to body surface area (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2375356/). 

Should the chemotherapy element support this? I think this is better, it would also correspond to the ICGC model

chemotherapy_dosage_units
https://docs.icgc-argo.org/dictionary

Question for discussion with CDDH is whether other ways of indicating dosage are also required.

**Comment by pnrobinson** [comment]
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C67402

**Comment by julesjacobsen** [comment]
https://github.com/phenopackets/phenopacket-schema/blob/7e636fca1fed142774332f648c4e7e256397b75a/src/main/proto/base.proto#L537-L542

**Comment by pnrobinson** [comment]
Question -- discussions to date have oscillated between having just one class for all kinds of treatment and having different classes for chemo, hormone therapy etc. 
Our impression is that there are more votes for having separate classes

**Comment by julesjacobsen** [comment]
Do we also want an `ImmuneTherapyTreatment`? Currently there are:

```proto
message MedicalAction {
    oneof action {
        Procedure procedure = 1;
        Treatment treatment = 2;
        ChemoTherapyTreatment chemo_therapy = 3;
        HormoneTherapyTreatment hormone_therapy = 4;
        RadiationTherapyTreatment radiation_therapy = 5;
        TherapeuticRegimen therapeutic_regimen = 6;
    }
    OntologyClass intention = 7;
}
```

**Comment by julesjacobsen** [comment]
Nope, we can model `ImmuneTherapy` as a `Treatment` as there are many potential types of immunotherapy.
