### ISSUE TITLE
Proposed Interval for time duration

### ISSUE THREAD

**Issue by rrfreimuth** [phenopackets/phenopacket-schema#246]
Please note that the GKS VRS [defines classes](https://vr-spec.readthedocs.io/en/1.1/terms_and_model.html#non-variation-classes) that represent the concept of an Interval (which is an abstract, base class) on a molecular sequence. At a minimum, please qualify the name of the proposed Interval class so that it does not create confusion with the VRS.

Please also consider aligning to the FHIR representation of time duration, which is modeled as [Period](https://www.hl7.org/fhir/datatypes.html#Period) . The core datatype is [dateTime](https://www.hl7.org/fhir/datatypes.html#dateTime) . Types for [date](https://www.hl7.org/fhir/datatypes.html#date) and [time](https://www.hl7.org/fhir/datatypes.html#time) are also available.

The [Domain Analysis and mapping to FHIR document](https://phenopackets-analysis.readthedocs.io/en/latest/toc.html) has analysis on this particular type, as it pertains to the concept of patient Age.

**Comment by pnrobinson** [comment]
The name of the proposed class is ``DoseInterval``
https://phenopackets-schema.readthedocs.io/en/latest/dose-interval.html
so it should not collide with the VRS class.

**Comment by pnrobinson** [comment]
Here is a description from a forum:
"Period" is a length of time, without the necessary implication of recurrence.
"Interval" more often implies the length of time between two actions.

So, it does seem that "Period" is a better label for this element, especially because is named so in FHIR

**Comment by pnrobinson** [comment]
However, a period is not anchored to a specific start/end

**Comment by pnrobinson** [comment]
Let's rename to ``TimeInterval`` which is the most unambiguous label -- it is intended to be synonymous with the FHIR Period.
