### ISSUE TITLE
Gestational age

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#248]
How to best represent gestational age?

**Comment by julesjacobsen** [comment]
```proto
message GestationalAge {
    int32 weeks = 1;
    int32 days = 2;
}
```

**Comment by dosumis** [comment]
@cmungall - what's the status of human dev stage ontologies (folded under Uberon?)

**Comment by cmungall** [comment]
This is the stage ontology for human:

https://www.ebi.ac.uk/ols/ontologies/hsapdv

you can see the main gestational division into embryo/fetus

![image](https://user-images.githubusercontent.com/50745/100178738-6849db00-2e89-11eb-99ed-54372159e55f.png)

For embryonic, up to day 60 it uses Carnegie stages, e.g

https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000030&viewMode=All&siblings=false

all stages are linked by temporal relations, canonical days are there as text and could easily be axiomatized facilitating interchange between precise days and categories

**Comment by julesjacobsen** [comment]
Presumably these can be mapped to the {weeks, days}? I suggested this as its what is actually used in clinics and is more amenable to (non-semantic) recording and computation.

**Comment by pnrobinson** [comment]
See also https://github.com/phenopackets/phenopacket-schema/issues/224

**Comment by julesjacobsen** [comment]
This renders in YAML as:

```yaml
gestationalAge:
    weeks: 6
    days: 2
```

Computationally its easy to parse:

```java
int totalDays = weeks * 7 + days;
Period period = Period.of(0, 0, totalDays);
```

```python
gestational_age = timedelta(weeks=22, days=5)
```
