### ISSUE TITLE
Biosample: Replace "is_control_sample" with term

### ISSUE THREAD

**Issue by mbaudis** [phenopackets/phenopacket-schema#249]
The `is_control_sample` flag is a bit of an outlier in its format, and also not flexible. We have previously created terms in EFO to accommodate the disambiguation between "abnormal" and "reference" samples, i.e. such serving for calibration purposes vs. observations. See [discussion / resolution here](https://github.com/EBISPOT/efo/issues/365#issuecomment-463218398).

In `progenetix.biosamples` we apply it like this, but are flexible in that respect:
```
	"provenance" : {
		"material" : {
			"type" : {
				"id" : "EFO:0009656",
				"label" : "neoplastic sample"
			}
		},
		"geo" : {
			"label" : "Antalya, Turkey",
			"precision" : "city",
...
```

(The `geo` stub shown here is a reminder of https://github.com/phenopackets/phenopacket-schema/issues/239 ...)

Now `phenopackets.biosample` has already a `sampledTissue` attribute which e.g. refers to an anatomic/developmental ... location attribute. This could be the right place to add by just changing its structure to a list of objects.

**Comment by pnrobinson** [comment]
NCIT has "control analyte" (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C156442&viewMode=All&siblings=false) but there do not arpear to be terms for metastatic sample. WHat would the full list of items be here and what ontology would be used? @mbaudis

**Comment by mbaudis** [comment]
@pnrobinson I had added [these terms](http://identifiers.org/EFO:0009654) etc. to EFO to allow the disambiguation between e.g. normal and cancer samples from the same patient. To your point:

* `metastatic sample` is actually a tricky label due to potential conflict with "sample in metastatic disease" (i.e. one says "metatstatic tumor" and may mean tissue of the primary, potentially)
* I can do a term request for `metastasis sample`, as child of `neoplastic sample` ?!
* other options then could be `primary tumor sample`, `recurrent tumor sample` ?

Obviously, other vocabularies could be used but I'm not aware of any match (therefore the EFO terms).

**Comment by mbaudis** [comment]
@pnrobinson See https://github.com/EBISPOT/efo/issues/917, https://github.com/EBISPOT/efo/issues/918, https://github.com/EBISPOT/efo/issues/919

**Comment by julesjacobsen** [comment]
https://github.com/phenopackets/phenopacket-schema/blob/1c560dbe649444286967a6446604722e62188e14/src/main/proto/phenopackets/schema/v2/core/biosample.proto#L95-L99

**Comment by mbaudis** [comment]
+1
