### ISSUE TITLE
Disease

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#250]
The Disease element currently has 
https://phenopackets-schema.readthedocs.io/en/latest/disease.html
both disease_stage and tnm_finding.
However, TNM is a kind of 'stage'
Consider obsoleting the tnm_stage element.
@mbaudis thoughts?

**Comment by mbaudis** [comment]
@pnrobinson +1 since the stage allows a list of terms.

**Comment by julesjacobsen** [comment]
But isn't the stage derived from the TNM findings? Is there a pressing reason to make the change? 

In deference to [ARGO](https://docs.icgc-argo.org/dictionary) (search for `clinical_tumour_staging_system`), where they have a stage and three separate T, N, M fields on conditional use when the AJCC stage is set, I suggest we keep it as is.

**Comment by mbaudis** [comment]
There is no universal staging system. I.e. hematologic neoplasias are not TNM'd; and I don't think it would be used for brain tumors, and also not pediatric cancers (which, well, are mostly brain tumors / leukemias / soft tissue...). TNM is convenient and it would be cool to just write a CLL Binet B as T2 - but there are AFAIK no conventions supporting this. Also, many disease specific staging systems are increasingly beyond size / node / metastasis (which then also leads to a conflation of diagnoses and staging ...). I could go on :-/

**Comment by julesjacobsen** [comment]
@mbaudis yes, this was my point. The stage is, as you say, fully non-standardised. However, _if_ you use a version of the AJCC staging, and you want to supply the T, M, N findings, adding these to the `tnm_finding` field would be appropriate. Perhaps this field should be renamed `stage_findings` if other staging systems have more granular findings to determine the stage?

I feel we shouldn't introduce as much change as possible, just for changes sake. Is this incorrect as it currently stands? Is it confusing as it currently stands? Does it not meet a particular modelling case? If so, it should be changed. If not, let it be.

**Comment by mbaudis** [comment]
@julesjacobsen Well, this started with @pnrobinson asking if `tnm_finding` could be removed... SO the 2 solutions are:

1. no; TNM is a well standardized, widespread staging system which can be applied to the majority of cancer instances; just keep it separate & leave the option for alternative annotations
2. TNM is just one of the options; so keep the data structure simple & drop it into a list of staging annotations (but then loose direct content control for TNM, to be well formatted)

There is also 2b: Use just one list for `stage` with additional qualifiers / prefix for the items, preferably "objectifying" them.

**Comment by mbaudis** [comment]
FYI: We skirt around this and have both, so far - but then will implement what arises here, I guess :-)

**Comment by julesjacobsen** [comment]
Also to take note - mCode FHIR profile https://hl7.org/fhir/us/mcode/artifacts.html#2 

I think I'm right in saying here that there are individual slots for T, N, and M @ametke can you confirm this?

**Comment by mbaudis** [comment]
It may be fine to capture the basic concepts of stage / regional LN / distant metastasis as separate concepts, or simply have an option for TNM as single annotation. Independent of that, non-TNM staging systems definitely need to be represented - even AJCC points to this (and w/ my collection of staging books I can confirm that neither CNS nor hematopoietic tumors are TNM'd...): [AJCC note on CLL staging](https://www.cancer.org/cancer/chronic-lymphocytic-leukemia/detection-diagnosis-staging/staging.html).

SEER has an overview about [**different non-TNMstaging schemes**](https://www.training.seer.cancer.gov/staging/systems/schemes/).

I don't know too much about FHIR, but see no mention of how to handle non-TNM staging. Fallback staging from SEER is "summary stage" but I don't know how this would end up conceptually in FHIR.

So, back to the top: Happy w/ status quo, and if one can get CURIES for TNM (not familiar if there is a robust system, but see e.g. http://ceur-ws.org/Vol-1442/paper_6.pdf) one can drop the separate attribute.

**Comment by julesjacobsen** [comment]
After looking at M-Code and ICGC ARGO they both model disease stage as separate to the TNM system. We also want to allow non-cancer staging to be possible, so we decided to retain the stage and the TNM findings:

https://github.com/phenopackets/phenopacket-schema/blob/4ab233a8cd881c6714e5a95ef395ea3edbd94ae4/src/main/proto/phenopackets/schema/v2/core/disease.proto#L29-L38

This was expanded to the Biosample as `pathological_stage` and `pathological_tnm_finding`, in line with both M-Code and ARGO:

https://github.com/phenopackets/phenopacket-schema/blob/4ab233a8cd881c6714e5a95ef395ea3edbd94ae4/src/main/proto/phenopackets/schema/v2/core/biosample.proto#L80-L82
