### ISSUE TITLE
Consider removing the Gene/Variant elements from the Phenopacket...

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#257]
and adding them to the ``Interpretation`` element. As they are currently used, the ``Variant`` element of the Phenopacket is intended to be an interpretation -- that a given variant is reponsible for a disease that is responsible for a phenotypic feature. In version 1, we can place this information optionally in the Interpretation or in the Phenopacket, but it would be better to not have two options for doing the same thing.

**Comment by julesjacobsen** [comment]
We should look closely at `Interpretation` and ensure that this really is better.

**Comment by pnrobinson** [comment]
After several discussions at GA4GH zooms and elsewhere, I think the decision is that it is indeed better to remove Gene/Variant elements from the ``Phenopacket`` message and to recommend their use in the ``Interpretation`` element. @julesjacobsen thoughts?

**Comment by julesjacobsen** [comment]
No one raised any negative issues, so I think they should be removed. 

The `Biosample` also contains a `variants` field which would also need removing and then the bio sample be added as a subject to the `Interpretation`. However, this needs to be checked that it still makes sense in that context.
