### ISSUE TITLE
Update details about Phenopackets FHIR IG in the Phenopackets RTD documentation

### ISSUE THREAD

**Issue by monicacecilia** [phenopackets/phenopacket-schema#258]
In the page https://github.com/phenopackets/phenopacket-schema/blob/master/docs/fhir.rst: 
- We need to update the details of the current Phenopackets FHIR IG and point to http://phenopackets.org/core-ig/master/ instead of the AEHRC IG. 
- It will be useful to point to the FHIR Artifacts that we have worked on and added to the IG, here http://phenopackets.org/core-ig/master/artifacts.html
- We should also point to the Domain Analysis Document so interested users can learn both how we are inspecting each element for the purpose of creating the mappings, as well as how to contribute. https://phenopackets-analysis.readthedocs.io/en/latest/

**Comment by pnrobinson** [comment]
done, thanks!
