### ISSUE TITLE
ExternalReference unclear?

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#26]
The External reference is not 100% clear. Here is the current definition
```
 message ExternalReference {
    // e.g. ISBN, PMID:123456, DOI:...
    string id = 1;
    string description = 2;
    }
```
Do we intend the id to be something like "PMID:12345" and the description to be something like "Patient B" from the same article? Can we provide a few examples of the intended use cases?

**Comment by cmungall** [comment]
What would be the downside of replacing all usages of ExternalReference with a simple CURIE? If people want metadata about the publication this can be done via API

**Comment by pnrobinson** [comment]
@cmungall I would say sometimes it might be useful to additionally have a description field to denote what part of the refered-to publication is meant. This could not be done via an API. For instance if we want to refer to patient B in some publication. However, this information could be provided in the description of the subject as well. So we need to decide.
A curie will probably not cover all possible use cases. For instance if this is being used in an EHR setting, or if somebody is refering to a social media post or site.
My original question was just to document our receommendations --

**Comment by pnrobinson** [comment]
We have added additional comments to clarify intended use case and FHIR mapping
