### ISSUE TITLE
Proposal for the addition of a schema block for clinical measurements

### ISSUE THREAD

**Issue by NuriaQueralt** [phenopackets/phenopacket-schema#261]
Dear team,

My name is Núria Queralt Rosinach and I am attending the Phenopackets monthly call as an EJP RD member. In the past BioHackathon for COVID-19 [1], some hackers in the 'ontology' group worked on the idea of extending the schema of phenopackets for *quantitative traits* such as clinical lab measurements to enable to structure for example lab results from [2]. We developed a proposal called 'QuantitativeTraitsFeature' in proto ( see below ) and we are wondering if this is interesting for the project to be added as we noticed that the upcoming release ( version 2 ), already includes a 'Quantity' block. This is the (partial) output of the compiled version, which includes now unit/value:

"quantitativeTraitFeatures": [{
    "description": "",
    "type": {
      "id": "CMO:0000015",
      "label": "Body temperature"
    },
    "negated": false,
    "value": "37.5",
    "unit": {
      "id": "UO:0000027",
      "label": "Degrees Celsius"
    },
    "evidence": []
  }

Please, note that if our proposal is of interest, the first thing that it could be done is to link value/unit fields to the 'Quantity' object.

For more tech details see our proposal in proto (QuantitativeTraitFeature.proto) at:
https://github.com/NuriaQueralt/BioHackathon/blob/master/bh20-ontology-qt/sequence/phenopacket/

And the whole example at:
https://github.com/cp-weiland/QuantitativeTraitFeature/tree/master/src/main/java/org/example

[1] https://github.com/virtual-biohackathons/covid-19-bh20/wiki/Ontology
[2] https://isaric.org/wp-content/uploads/2020/10/ISARIC_COVID-19_RAPID_CRF_25.08.2020.pdf

Please, do not hesitate to ask whatever you need. Thank you very much.
Looking forward to hearing from you!

**Comment by julesjacobsen** [comment]
Hi Nuria, this looks interesting. Would you like to come and present this at a working group meeting?

Also, have you looked at the code in the v1.1 branch yet? The Value and Quantity messages would be well suited for this.

https://github.com/phenopackets/phenopacket-schema/blob/f73b4bd5ad966321d3d6b3c7ff8aa8f63820941b/src/main/proto/base.proto#L150-L169

**Comment by julesjacobsen** [comment]
@NuriaQueralt has volunteered to present some use-cases for the next meeting.

**Comment by julesjacobsen** [comment]
@NuriaQueralt, please have a look at and comment on the schema we have now:

https://github.com/phenopackets/phenopacket-schema/blob/113d9039304aeb02f8ad6a705d26ec9969c3f5c6/src/main/proto/base.proto#L143-L214

If you have any use-cases you used for your original design, do they still work here?

**Comment by NuriaQueralt** [comment]
Hi @Jules, I really like the new schema and its modular structure: it makes it flexible and works very well with our covid-19 use cases. Although, I have some comments and doubts that I would like to discuss:

In comparison with our proposal, the new schema:

* removes fields: negated, assay, onset and evidence. Biosample is now pointing at biosample_id and not to biosample element. Questions:
- why did you remove negated? Then, how to interpret if a measurement is not in the phenopacket (PP)? it means that it is not done, or it means that it is done and in the normal range (so negated)? In use case 1 (see below), lab measurements have the label ‘not done’, so imo this data should be explicitly annotated. 
- I would not remove assay, since it is data tracked in our use cases for interpretation (see below use case 2).

* adds new fields: complex quantity and time element. Time element is a great addition! it allows us to represent ‘measurement date’ collected in use case 2. 

* abstracts: value, complex quantity, time element, quantity, range and reference range. Questions:
- value can be one of ‘quantity’ or ‘ontology class’. Which use case is represented by value::ontology_class? could you provide an example?
- is complex quantity used to represent compositional classes? I think this is a good addition because provides flexibility to reach the expressivity we need, but note that the example provided in the schema (blood pressure (bp) systolic/diastolic) can be represented by different classes in CMO: http://purl.obolibrary.org/obo/CMO_0000004 or
http://purl.obolibrary.org/obo/CMO_0000005, so in this example there is no need of using the composition of bp type and systolic type. Also, I am wondering why complex quantity links to quantity and not to value element? 
- quantity: how to represent adimensional quantities such as ratios or scores? (see ‘Glasgow coma score’ below in use case 1). 
- how to represent units that are not yet standardized? Could be a solution to use one of ‘ontology class’ or ‘string’? (we encountered this issue, see point 4 in use case 1).
- what is the difference between reference range and range? Why is only reference range linked to quantity? Why is range there?

* adds qualifiers ‘low’ and ‘high’ in (reference) range new elements. Question:
- why is ‘Normal’ not represented?


Use case 1: WHO covid19 CRF lab results/vital signs monitoring data:

1. vital sign ‘Glasgow coma score’ does not have a unit. How to represent it?
2. data measurement ‘lab result not done’; is it represented? Note that ‘not done’ is only tracked for lab results measurements, but not for vital signs. One solution here is to include in PP only measurements done, but add the field ‘normal’ in range in order to avoid the confusion “if it is not in PP is because it is not done or because it is done, but the level found is ‘normal’”.
3. data ‘on admission’ and ‘follow-ups’, denote disease progression; where are they represented? Shouldn’t they be linked to measurement? I guess these annotations are represented, but they are linked to disease phenotype schema or (if it exists in PPs) to encounter like in FHIR or OMOP. This data meaning is also captured and related to the data ‘ward’ in use case 2 below, which denotes disease severity/stage. Thus, imo these data should be linked to measurement to aid interpretation. What do you think?
4. for some units we could not map them to any ontology class


Use case 2: Hospital lab results research data:

1. data ‘assay’ and data about the assay, ‘kit’ and ‘device’, are tracked in the use case. Clinical researchers need to know the kit (or protocol of the assay) for the interpretation of measurements since ranges may vary depending on the kit. Maybe this information is annotated using the reference range element? Otherwise, how is this represented?
2. data ‘measurement date’ is represented by time element; great addition!
3. data ‘biosample’ is represented by biosample_id. What is the difference to represent biosample with ‘biosample element’ or with biosample_id? I think it makes sense if we don’t have more information than the id. 
4. data ‘ward’, which includes ICU as value, and denotes the patient disease severity/ disease stage; is it represented linked to measurement? 


Thank you!

**Comment by julesjacobsen** [comment]
@NuriaQueralt many thanks for you detailed feedback and I'm please to hear you generally like the changes. I'll try to address your questions here:

> In comparison with our proposal, the new schema:
> 
>  -  removes fields: negated, assay, onset and evidence. Biosample is now pointing at biosample_id and not to biosample element.

Actually in the latest, version we also removed `biosample_id` from `Measurement` and added a `repeated Measurement` to the `Biosample` itself. So now measurements pertaining to the `Biosample` are contained within that message. The `measurements` field in the Phenopacket would pertain to the `subject`.

> - why did you remove negated? Then, how to interpret if a measurement is not in the phenopacket (PP)? it means that it is not done, or it means that it is done and in the normal range (so negated)? In use case 1 (see below), lab measurements have the label ‘not done’, so imo this data should be explicitly annotated.

We removed 'negated' because a `Measurement` is essentially a complex value and saying "Not 37.5 degrees Celcius" is meaningless as this begets the question "So what _was_ the  subjects temperature?", the answer being an asserted value. So either the `Measurement` was recorded or it was not. For qualitative traits such as PhenotypicFeature having a negated field makes sense as these have no specific value.

>  -   I would not remove assay, since it is data tracked in our use cases for interpretation (see below use case 2).

We never had an `assay` field. Do you mean 'evidence`? 

> -   value can be one of ‘quantity’ or ‘ontology class’. Which use case is represented by value::ontology_class? could you provide an example?



>   -  is complex quantity used to represent compositional classes? I think this is a good addition because provides flexibility to reach the expressivity we need, but note that the example provided in the schema (blood pressure (bp) systolic/diastolic) can be represented by different classes in CMO: http://purl.obolibrary.org/obo/CMO_0000004 or http://purl.obolibrary.org/obo/CMO_0000005, so in this example there is no need of using the composition of bp type and systolic type. Also, I am wondering why complex quantity links to quantity and not to value element?

The `ComplexQuantity` is required for blood pressure as this is given as a compund measurement e.g. 120/80mmHg here the 120 is the systolic measurement and the 80 is the diastolic. You need both measurements to determine someone blood pressure. e.g.

```yaml
complexQuantity:
    - type: 
           id: CMO:0000004
           label: systolic blood pressure
       quantity:
           unit:
              id: NCIT:C49670
              label: Millimeter of Mercury
           value: 120 
           referenceRange:
               unit:
                  id: NCIT:C49670
                  label: Millimeter of Mercury
                low: 90
                high: 120
     - type: 
           id: CMO:0000005
           label: diastolic blood pressure
       quantity:
           unit:
              id: NCIT:C49670
              label: Millimeter of Mercury
           value: 80 
           referenceRange:
               unit:
                  id: NCIT:C49670
                  label: Millimeter of Mercury
                low: 60
                high: 80
```

>   -  quantity: how to represent adimensional quantities such as ratios or scores? (see ‘Glasgow coma score’ below in use case 1).

>  -   how to represent units that are not yet standardized? Could be a solution to use one of ‘ontology class’ or ‘string’? (we encountered this issue, see point 4 in use case 1).


>   -  what is the difference between reference range and range? Why is only reference range linked to quantity? Why is range there?

Looks like I forgot to remove `Range`. Although we could remove `ReferenceRange` and just use `Range`. We wanted stronger typing in the `reference_range` field, but now I wonder if this was the right thing to do.

>   -  adds qualifiers ‘low’ and ‘high’ in (reference) range new elements. Question:
> 
>    - why is ‘Normal’ not represented?

The reference range is the normal range. Any `Quantity` with a `value` < `low` or  > `high` is abnormal. Ah! I see - perhaps this would be clearer naming these fields `lower` and `upper`?

**Comment by mellybelly** [comment]
Just catching up here, but for measurements we'd definitely want interop with LOINC and LOINC parts; see also the LOINC2HPO work. A lot of work has also been done on units and unit harmonization in other contexts (N3C, OHDSI, HL7, etc.)

**Comment by mellybelly** [comment]
some info on the unit harmonization: https://forums.ohdsi.org/t/utilization-of-ucum-for-n3c/12053 
@DaveraGabriel

Also please consider OBA as it is intended to be the superclasses of traits for HPO and other OBO phenotype ontologies: http://www.obofoundry.org/ontology/oba.html

**Comment by NuriaQueralt** [comment]
@mellybelly thank you so much for pointing at OBA! I was not aware of this ontology. @cmungall very nice that OBA includes quantitative traits (aka measurable phenotypes) like levels and that is intended to be the superclasses of traits for HPO and other phenotype ontologies in OBO. This fits very nicely our covid-19 use case, where hospitals are monitoring metabolites levels like 'IL-6 (pg/mL)'. It is ideal that now we can represent the quality that is being measured such as 'blood interleukin-6 amount (http://purl.obolibrary.org/obo/OBA_VT0008595)'. This is really helpful! thank you for filling this gap!!!

**Comment by pnrobinson** [comment]
@mellybelly definitely all of the above e.g. LOINC can be used here. measurements and traits are two sides of the same coin. For instance, the measurement might be LOINC:blood glucose test and the trait might be OBA:blood glucose level. It is possible that this distinction does not matter for downstream analysis. In any case, it would be great to have logical maps between LOINC and OBA to facilitate integration of clinical measurements.

**Comment by matentzn** [comment]
Great discussion; was not aware pheno packets already deals with stuff like that - that's good to know! Commenting mostly to ensure I am aware of future developments.

**Comment by julesjacobsen** [comment]
@NuriaQueralt I think this issue can be closed now. Are you happy with the state of it? We needed to change the ComplexQuantity model one more time so that it is only possible to have a` Value` or a `ComplexValue`:

https://github.com/phenopackets/phenopacket-schema/blob/e76b15cd33d1de0e8244ae0c811e54c7c8c99093/src/main/proto/phenopackets/schema/v2/base.proto#L143-L217

**Comment by NuriaQueralt** [comment]
@julesjacobsen completely agree with the change and overalll it looks very good! So from my side this issue can be closed. THANK YOU ALL THE TEAM!!! It has been a real pleasure!!!

**Comment by julesjacobsen** [comment]
Brilliant!. Thanks @NuriaQueralt for your fantastic input!

**Comment by ianfore** [comment]
Is this the right place to follow up this from the 3/25/21 call? I promised to follow up on dbGaP examples.
The following is a simple example of how a data dictionary

    <variable id="phv00409136.v1">
        <name>age</name>
        <description>Subject's age</description>
        <type>integer, encoded value</type>
        <unit>Years</unit>
        <value code="N/A">Not available</value>
    </variable>

The type is intended to represent a column which for the most part contains integer ages but in some cases the column contains N/A. There are many variables like this in dbGaP, representing a very common occurrence. I'm not suggesting this should be included as is - there are many differences; the schema is in xml not json; the handling of unit does not use a unit ontology as we discussed. Those differences aside, this is shared to show where a 'complex type' has proved necessary in providing phenotypic data specifically to accompany genomic data.
Other types used have been 
"float, encoded value"
"numeric, encoded value"
Probably don't need all of integer, float and numeric though.

Also suggested during this weeks Search call that this would be a good topic to discuss jointly. The more general question about how one discovers a Phenopacket schema from within Search has come up before, but this would provide a specific example to explore.

**Comment by pnrobinson** [comment]
@ianfore  the idiomatic way of representing this in a phenopacket would be to simply not specify the age. I thought we were talking about two specific situations
1. Complex data such as blood pressure (which consists of two links measurements
2. Data whose result is "greater than some number"

There is a new representation of complex measurements such as blood pressure (available now in the protobuf code, the RTD documentation will be available next week) for the first item

I think we decided to postpone the decision of whether to represent the "greater than some number". My presumption is that data points like this will usually or even almost always be of the form "greater than the upper limit" or "below the limit of detection", in which case the result could easily be represented by an ontology term. If there are examples of measurements that are like "greater than some number that is not the upper limit but is important to know about" that would be motivation to add this level of complexity to this element. (Note this is my opinion but if it is not consensus that we should discuss this on the next call). If you are aware of data that looks like this it would be really helpful to have an example or two. Could I suggest that we then make a new issue for it?
