### ISSUE TITLE
Remove AttributeValue

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#27]
This element is complicated and we should provide a number of examples of the intended use cases (currently unclear). Also, item 9 is commented out and should either be removed or repaired prior to the official release.

**Comment by julesjacobsen** [comment]
Agreed. It might be best to simply remove these more esoteric bits. I added them for completeness, making the possibly incorrect assumption that these were required by the former GA4GH group. I feel we should aim for simplicity over completeness. If there is an obvious and pressing need it's easy enough to add. Taking away is harder.

**Comment by julesjacobsen** [comment]
In the interest of narrowing scope I suggest we remove this. Please add your thumbs-up/down/ comments.
