### ISSUE TITLE
Add/Update Recommended Ontologies

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#276]
Just catching up here, but for measurements we'd definitely want interop with LOINC and LOINC parts; see also the LOINC2HPO work. A lot of work has also been done on units and unit harmonization in other contexts (N3C, OHDSI, HL7, etc.)

_Originally posted by @mellybelly in https://github.com/phenopackets/phenopacket-schema/issues/261#issuecomment-806091445_

**Comment by julesjacobsen** [comment]
@pnrobinson has this been fully resolved? https://github.com/phenopackets/phenopacket-schema/blob/v2/docs/recommended-ontologies.rst

**Comment by pnrobinson** [comment]
I think we can close this issue even though we will epect to receive further comments/suggestions.
