### ISSUE TITLE
Remove AttributeValues and Attributes

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#28]
We seem to be defining both a list and a map
```
message AttributeValues {
    repeated AttributeValue values = 1;
}

message Attributes {
map<string, AttributeValues>
}
```

This seems confusing and will make client code more complicated. It seems it might be better to demand a map whose key represents what the attribute is about? Otherwise can we specify when the list should be used and when the map should be used?

**Comment by cmungall** [comment]
possible dupe with #27

**Comment by pnrobinson** [comment]
@cmungall @julesjacobsen Yes this is probably a duplicate but still I find this potentially confusing. @drseb please also have a look at this. I currently do not follow how these fields are supposed to be used.

**Comment by drseb** [comment]
These are not the same. One is _Attributes_, which is a map. The value of the map is an _AttributeValue_. Not sure what exactly you want to discuss here, but it seems to me, that you want to avoid having possible confusion about usage. However, it seems to me you are supposed to never use the _AttributeValues_ alone. Is that what you mean?

**Comment by julesjacobsen** [comment]
I agree we need to look at these - they were taken from the original GA4GH metadata schemas. As @drseb said, the ```Attributes``` is a map of ```AttributeValues``` which  is a list of ```AttributeValue```. In other words ```Attributes``` is a multi-value map. They are confusingly named in my opinion and I'm not entirely sold on having this without any obvious need.

**Comment by julesjacobsen** [comment]
In the interest of narrowing scope I suggest we remove this. Please add your thumbs-up/down/ comments.
