### ISSUE TITLE
Disease

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#281]
This is the current definition, but do we want to limt this to be previous diagnosis?

```
laterality
~~~~~~
If donor has history of prior malignancy, indicate laterality of previous diagnosis.
```

**Comment by julesjacobsen** [comment]
No, I don't think we do. It should simply indicate the laterality of the disorder, if applicable.

**Comment by julesjacobsen** [comment]
One thing we didn't model was whether a disease was the subject of/reason for a medical action. Given more than one disease in a phenopacket, there is no way to state that medical action A was performed as a primary treatment for disease D1 and not D2.

**Comment by pnrobinson** [comment]
@julesjacobsen  Should we consider adding an ontology term to medical action, target_of_treatment, with the term required to denote a disease mentioned in the phenopacket (if used).

**Comment by julesjacobsen** [comment]
Oops, looks like I forgot to commit my local changes! I had added this to `MedicalAction`

```proto
  // The condition or disease that this treatment was intended to address.
  // FHIR mapping Procedure::reasonCode TODO: 0..1 or 0..n?
  OntologyClass treatment_reason = 7;
```
I think I slightly prefer your suggestion of `target_of_treatment`  to the `treatment_reason`. How about `treatment_target` which fits with all the other `treatment_...` field names?

**Comment by julesjacobsen** [comment]
Updated in 695d471f089269b871a4b82d16f3f787b742f442
