### ISSUE TITLE
Update element

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#284]
The ``Update`` element is not currently used anywhere. Also, should we add a ``created`` timestamp element to the top-level elements?

**Comment by julesjacobsen** [comment]
Its used as part of the `MetaData`, which already has a `created` field.

https://github.com/phenopackets/phenopacket-schema/blob/a6a23654ae271947191da573501fbd4d46e0c469/src/main/proto/phenopackets/schema/v2/core/base.proto#L24-L42

I'll move `MetaData` into the phenopackets.proto file as this is the only place its used.

**Comment by pnrobinson** [comment]
sorry, somehow misplaced this remembrance :smile: 
I updated the docs
