### ISSUE TITLE
Add page describing major changes from v1 to v2

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#286]

**Comment by julesjacobsen** [comment]
Also need to update [CHANGELOG.rst](https://github.com/phenopackets/phenopacket-schema/blob/v2/CHANGELOG.rst)

**Comment by julesjacobsen** [comment]
Started an update section in commits a99c44c1acccef0caac469d0e12be6a8b48c5c19 and fbedc022b90eb92a7cc81a88b195a1832a9b5300
