### ISSUE TITLE
evidence elelement -- can we discuss & document the intended usage?

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#29]
For this element, 
```
message Evidence {
    OntologyClass evidence_code = 1;
    ExternalReference reference = 2;
  }
```
I have written this
```
For example, in order to describe the evidence for a phenotypic observation that is derived from a publication, one might use
the ECO term `author statement from published clinical study used in manual assertion` <https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0006017>`_ and record a PubMed id in the reference field
(See :ref:`External Reference element`). 
```

Is this correct? Are there any other examples we can provide here?

**Comment by cmungall** [comment]
cc @mbrush

**Comment by pnrobinson** [comment]
@mbrush @cmungall  -- so are we OK with this? Can I close this issue?

**Comment by julesjacobsen** [comment]
That was my intention - TAS and journal article reference. I guess another example would be a clinical observation. In this case its less clear what the external reference might be.

**Comment by mbrush** [comment]
If I recall there are only a few 'types' of evidence that are relevant/allowed in the spec - and we have ECO terms for each.  If this is the case, it might be nice if the documentation briefly described each of these evidence types/ECO terms, and provided an example of their intended use.
 
A couple related questions:  First, wanted to confirm my understanding that the 'assertion' that we are capturing evidence for is a statement that an individual (or cohort/group) exhibits a particular phenotypic feature, correct?  Second, I was curious if the current two element evidence model (pub and EOC code) is sufficient, or if there are plans to expand.

**Comment by pnrobinson** [comment]
@mbrush do you have suggestions as to the necessary ECO codes? I do not think that the phenopacket standard restricts the ECO codes that can be used here, but if we want to do so then we need to document it. 
The main use case now is probably that a publication support some phenotypic or related assertion.

**Comment by pnrobinson** [comment]
We have added additional documentation. The answer to the above two question is Yes, the 'assertion' that we are capturing evidence for is a statement that an individual (or cohort/group) exhibits a particular phenotypic feature. The answer to the second question is that the first phenopacket standard will have just these two items (pub and ECO code) unless an important areas is identified as lacking.
