### ISSUE TITLE
Date of birth as Timestamp is too precise

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#3]
```protobuf
message Individual {
    string id = 1;
    
    // is this not too precise a field?
    google.protobuf.Timestamp date_of_birth = 2;
    Sex sex = 3;
    repeated Phenotype phenotypes = 4;
    repeated Disease diagnoses = 5;
}
```

Yes! However it has temporality baked-in, which is good. If we were to be less precise I guess ```year_of_birth``` and ```month_of_birth```  fields could be used, but this becomes a pain to model.

**Comment by pnrobinson** [comment]
There is a typo: ``suspect conditions`` should be ``suspected conditions``.
