### ISSUE TITLE
Treatment - HormoneTherapyTreatment, ChemoTherapyTreatment

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#304]
Currently hormone and chemotherapy are subclasses of treatment, with the only difference being the `cumulative_dose` field in chemo and hormone therapy.

https://phenopacket-schema.readthedocs.io/en/v2/medical-action.html
https://phenopacket-schema.readthedocs.io/en/v2/treatment.html
https://phenopacket-schema.readthedocs.io/en/v2/hormonetherapy.html
https://phenopacket-schema.readthedocs.io/en/v2/chemotherapytreatment.html

It was pointed out that the same therapy (a steroid treatment) could be applied as either a treatment for cancer, inflammation and falls into both the hormone and chemotherapy classes. In order to address this is was suggested that the  `cumulative_dose` field be added to the `Treatment` class and the `HormoneTherapyTreatment` and `ChemoTherapyTreatment`. The intention of the cumulative dose was for tracking toxicity, which could be applicable to a generic `Treatment`

**Comment by mcourtot** [comment]
Would it be feasible to just keep 'treatment' and then have a 'treatment objective' which could be 'hormone therapy' 'cancer therapy' 'xx therapy' etc?

**Comment by julesjacobsen** [comment]
Yes, `Treatment` is part of a `MedicalAction` (sorry, should have added that initially), which has the fields `treatment_target`  and `treatment_intent` which should help with this.
