### ISSUE TITLE
Variant.sequence

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#31]
```
 Variant {
    // genome assembly isn't strictly necessary if using the sequence accession as that will be unique for the assembly/sequence
    GenomeAssembly genome_assembly = 1;
    // Accession of the sequence e.g. NC_000010.10 (GRCh37 chromosome 10)
    string sequence =
```

I think it would be better to rename "sequence" to sequence_accession or accession_number, because I thought sequence would be a sequence of nucleotides -- the label is confusing.

**Comment by cmungall** [comment]
+1

Also I would avoid "sequence" as a field name as it's reserved in many languages

Also can we require a CURIE here?

**Comment by pnrobinson** [comment]
I have altered the name of the element to ``sequence_accession``. I would say that for most people it is more natural to not use accessions and it is obvious (at least to those in the know) that NM_* is a RefSeq, uc\d+ is from UCSC, and ENS-lots of digits is from ensembl. I am making the PR for the string version now, but if we feel strongly we can make the change @cmungall @julesjacobsen

**Comment by julesjacobsen** [comment]
Thanks Peter, I think this is a decent change.
