### ISSUE TITLE
Allow SPDI, HGVS and VCF for encoding of Variant

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#33]
```
// Deleted bases on the forward strand - equivalent to the VCF REF
    string deletion = 5;
    // Inserted bases on the forward strand - equivalent to the VCF ALT
    string insertion = 6;
```
Can we go over exactly what we want people to do with these fields and document them?
I am not a SPDI expert, but I do not think that deletions require a string. According to the documentation, When a nucleotide deletion occurs, nothing is inserted. In SPDI syntax, InsertedSequence is simply an empty string. Thus, the deletion of the same A nucleotide as above is represented as:
```
Seq1:4:1: 
```
Thus, is this a mistake, or do we want people to add EITHER SPDI OR VCF (which would be a recipe for disaster!!!)

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/variation/notation/

**Comment by pnrobinson** [comment]
What about
```proto
repeated variant variantlist=42;

message variant {
 string id = 1;
 oneof {
    hgvsvariant = 2;
    spdivariant = 3;
    vcfvariant = 4;
   iscnvariant = 5;
}
```

For instance, ISCN is for large-scale chromosomal anomalies, https://www.humpath.com/spip.php?article13862

**Comment by pnrobinson** [comment]
then
```proto
message ISCNvariant {
   string id = 1;
// an ICSN code such as del(6)(q23q24) , t(8;9;11)(q12;p24;p12), +15
   string var = 2;
  OntologyClass genotype = 3;
}
```
Comment --

**Comment by pnrobinson** [comment]
then
```proto
message VCFvariant {
   string id = 1;
  string chrom = 2;
   string ref = 3;
   string var = 3;
  OntologyClass genotype = 3;
}
```
Question -- do we want to store any of the other VCF fields?

**Comment by pnrobinson** [comment]
then
```proto
message HGVSvariant {
   string id = 1;
// e.g., NM_000226.3:c.470T>G
  string hgvs = 2;
  OntologyClass genotype = 3;
}
```

**Comment by pnrobinson** [comment]
We should add as a comment that we plan to add VMCvariant as soon as that format has been approved by GA4GH

**Comment by julesjacobsen** [comment]
I think this seems a sensible suggestion. It prevents uncertainty, allows people to choose a relevant system and enables adding future representation, e.g. VMC when ready.
