### ISSUE TITLE
Possible to get the json examples for RD & cancer?

### ISSUE THREAD

**Issue by peupeubangbang** [phenopackets/phenopacket-schema#332]
just wondering if its possible to have the RD & cancer v2 examples in **.json** format added to the Python folder? (If you have available) I have found the COVID json example :)

we are looking to use aspects of the phenopacket schema for an aggregate Patient Summary data file focusing on RD patients and our Python loving developer is keen to build out a template in json but wants to look in more detail at the schema. No problem if you don't have those json examples written up I'm sure we will manage between the COVID example and the readthedocs!

**Comment by julesjacobsen** [comment]
Hi @peupeubangbang, assuming your Python-loving developer isn't completely allergic to Java, this repository has a set of examples which it will generate in json: https://github.com/phenopackets/phenopacket-tools/releases/tag/v1.0.0

Have you checked out the docs too?  https://phenopacket-schema.readthedocs.io/en/v2/examples.html

**Comment by peupeubangbang** [comment]
Thanks @julesjacobsen I completely missed this in the repo and docs - that is great!

@ktogher check this out for the Java code 🙂
