### ISSUE TITLE
Implement GA4GH Pedigree model

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#333]
@buske

Will require an `ethnicity` field adding to Individual:

>Re-opening given discussion with Pedigree group on 2022-03-03. This field is useful/required for many test ordering systems. The codes used will likely be national-specific codes and not necessarily universally applicable.

_Originally posted by @julesjacobsen in https://github.com/phenopackets/phenopacket-schema/issues/231#issuecomment-1058533105_

**Comment by julesjacobsen** [comment]
Plan is to add `org.ga4gh.pedigree.Pedigree` and component classes, composed using Phenopacket-schema entities i.e. [Individual](https://phenopacket-schema.readthedocs.io/en/latest/individual.html), [OntologyClass](https://phenopacket-schema.readthedocs.io/en/latest/ontologyclass.html).

The GA4GH Pedigree would be incorporated as a `oneof` in the [Family.pedigree](https://phenopacket-schema.readthedocs.io/en/latest/family.html#data-model) field.

**Comment by julesjacobsen** [comment]
- [ ] Implement classes
- [ ] Update Family
- [ ] Test backwards compatibility
- [ ] Update Docs
- [ ] Drink Tea

A note on backward compatibility - if it is not possible for the pedigree to be made a `oneof` we will have to try another solution.

**Comment by pnrobinson** [comment]
@julesjacobsen I think this is something we will have to leave for a future version? Should we close?

**Comment by M-casado** [comment]
Hi everyone, sorry to budge in this thread, but I was wondering if you could give more details about the future population building block. I came from https://github.com/phenopackets/phenopacket-schema/issues/231, and I also am interested in having ethnicity part of a phenopacket. 

Regardless of what the final implementation is, would it include both ancestry informative markers (Ancestry category [HANCESTRO:0004]) and other less informative markers (in case the former are missing; e.g. National origin [NCIT:C28407] or Ethnic group [EFO:0001799]).

**Comment by julesjacobsen** [comment]
Currently https://github.com/phenopackets/phenopacket-schema/commit/727b245c0ec0df71467344eef7d04cb07b00ae9e

This is external to the phenopacket-schema as it lives in the `org.ga4gh.pedigree` namespace and imports `Phenopacket` and `OntologyClass` . This might change to use the Pedigree model `Individual` and potentially a `Concept` (would be identical to `OntologyClass`, only native to the Pedigree model to  reduce depencencies)

**Comment by julesjacobsen** [comment]
@M-casado have you got a use-case and model in mind? If so please continue this in #231

**Comment by M-casado** [comment]
Hi @julesjacobsen, I do not a specific use-case and model in mind. There is a general desire from the users of my archive (EGA) to be able to provide the ethnicity of their probands, and we will try to conform to phenopackets.

**Comment by cmungall** [comment]
What's the status of this?

**Comment by julesjacobsen** [comment]
This is work in progress and taking lead from the [GA4GH-Pedigree](https://github.com/GA4GH-Pedigree-Standard/pedigree) working group.

**Comment by acabrelles** [comment]
Hello! I'm pretty new to the use of phenopackets, and I am trying to build one as complete as possible as an example via the Python modules created here, and I stumbled upon an issue with the Pedigrees (I thought It'd be a good idea to mention it here). 

It may be my ignorance, but the Pedigrees are a list of Persons, and I have tried all my might to find this Person bit in the code. I was given an error that calls for phenopackets.schema.v2.core.pedigree_pb2.Person, but I have not had the ability to find it.

**Comment by julesjacobsen** [comment]
Hi @acabrelles how are you accessing this? Are you using the [PyPi library](https://pypi.org/project/phenopackets/)?

**Comment by ielis** [comment]
Hello @acabrelles , 

the `phenopackets` Python package deployed on PyPi mostly includes just the code generated by the Python Protobuf compiler, and the code is a bit clunky.

This is nicely shown in the `Person` class. In Phenopacket schema, the `Person` message is [nested](https://github.com/phenopackets/phenopacket-schema/blob/d69fc9e6fe425ed0ca05ec81ee5b8f0380f4754d/src/main/proto/phenopackets/schema/v2/core/pedigree.proto#L14) in `Pedigree`. Therefore, you do not really have to import it in Python, in order to use it.

Please try something like this to build a `pedigree`:

```python
from phenopackets.schema.v2.core.individual_pb2 import MALE
from phenopackets.schema.v2.core.pedigree_pb2 import Pedigree

person = Pedigree.Person(
    family_id='FAM001',
    individual_id='ID1',
    paternal_id=None,
    maternal_id='ID2',
    affected_status=Pedigree.Person.AFFECTED,
    sex=MALE
)
pedigree = Pedigree()
pedigree.persons.append(
    person,
)
```

**Comment by acabrelles** [comment]
@ielis thank you so much, I did not realize that it was right there this whole time! I assumed it'd be like Cohorts. Thank you!

Also @julesjacobsen I'm sorry for the lack of response, I wrote a message but just now I realized I forgot to send it. I see things clearly now.

Thank you for the quick replies!

**Comment by julesjacobsen** [comment]
Closing this issue as the Pedigree model project has been in limbo for a couple of years now.
