### ISSUE TITLE
Bug in documentation for MedicalAction | TherapeuticRegimen

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-schema#344]
The [table with definition](https://phenopacket-schema.readthedocs.io/en/latest/therapeutic-regimen.html#id2) of the `TherapeuticRegimen` contains `status` in the last row. However, according to the corresponding `proto` file, this should have been `regimen_status`.

**Comment by pnrobinson** [comment]
@julesjacobsen I will make a PR for this and some other documentation issues, OK?
