### ISSUE TITLE
Can we add new variables or values to the phenopacket building blocks?

### ISSUE THREAD

**Issue by MarioCazalla** [phenopackets/phenopacket-schema#363]
Hello all,
We are working with phenopackets and we want to know if it is possible to add new interesting variables to the phenopacket building blocks.

Thank you very much for your work.

**Comment by pnrobinson** [comment]
Hi there,
it is certainly possible from a software point of view, but then the new packets would not be valid phenopackets. It might be better to wrap the phenopacket in another data structure that additionally contains the data that your application requires. Finally, please let us know what was missing and how you solved it.

**Comment by MarioCazalla** [comment]
Hello Mr Robinson,
I am currently trying to transfer data from a FHIR file to Phenopacket but I cannot find all the equivalents that FHIR could have comparing with Phenopacket on your website. I found this URL https://docs.google.com/spreadsheets/d/1zZy3cxaIztQlGk79VI1jSV2Dg5C05HB681z1JGu_vZo/edit#gid=1588933282 where I see some, but it is not complete.
On the other hand, do you know any tool that has already been created for mapping from FHIR format to Phenopacket? 
Thank you very much in advance.

**Comment by pnrobinson** [comment]
This library may be of interest, although it does not include FHIR code: https://github.com/phenopackets/phenopacket-tools
We are woprking on a FHIR implementation guide -- https://github.com/phenopackets/core-ig, but this may not help if your data is formated with generic FHIR. If you are interested in joining a team of people in working on the IG please get in contact

**Comment by pnrobinson** [comment]
Closing this for now, please reopen if there are additional comments!
