### ISSUE TITLE
Is meta_data always required?

### ISSUE THREAD

**Issue by holtgrewe** [phenopackets/phenopacket-schema#373]
Is it the intention of the specification that `meta_data` is mandatory for `proband` and `relatives.*` if the containing `family` already has a full specification?

**Comment by pnrobinson** [comment]
Our implementation in [phenopacket-tools](https://github.com/phenopackets/phenopacket-tools) requires that each phenopacket have a proper metadatasection. This is admittedly redundant but we felt that it does not add much and is less error prone.

**Comment by holtgrewe** [comment]
Thanks for the info.
