### ISSUE TITLE
please relax protobuf dependency in setup.py

### ISSUE THREAD

**Issue by holtgrewe** [phenopackets/phenopacket-schema#375]
Currently the protobuf version is pinned as `protobuf==3.20.2`.

This is bad for several reasons. For one, this triggers conflicts if another dep needs a more modern version. For another, the version has a NIST HIGH security issue.

https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf

Rather use `protobuf>=3.20.2,<4.0`. IMO it can be expected that google will adhere to semver.

A pypi release would be appreciated.

Thanks for the great package.

**Comment by holtgrewe** [comment]
@pnrobinson any news on this? ;-)

**Comment by pnrobinson** [comment]
@iimpulse  -- can we adjust the versions as suggested by @holtgrewe  ?

**Comment by holtgrewe** [comment]
@pnrobinson any news on this?

**Comment by iimpulse** [comment]
see the post1 fix here @holtgrewe https://pypi.org/project/phenopackets/

**Comment by holtgrewe** [comment]
Sorry for not getting back to you earlier. Yeah, that worked.
