### ISSUE TITLE
Upgrade to protobuf 3.7.0

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#39]
Consider update from version 3.5.1 to 3.6.1 of protobuf.

I believe this might fix the following error warning (see the change log https://github.com/protocolbuffers/protobuf/blob/master/CHANGES.txt).
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/robinp/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by julesjacobsen** [comment]
Good call - it's only a warning so is just an eyesore at the moment. I think the fix required went into master after 3.6.1 was released so we'll need to use the version after 3.6.1.
