### ISSUE TITLE
Add submitter fields to MetaData

### ISSUE THREAD

**Issue by drseb** [phenopackets/phenopacket-schema#40]
Consider adding 'submitted_by' or  'submitter_identifier' as fields to the MetaData message

**Comment by drseb** [comment]
How does it relate to https://github.com/phenopackets/phenopacket-schema/blob/da69897c44b3299d8c27c277f3b1714644787a4a/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L12 ?

**Comment by julesjacobsen** [comment]
Similar - that is intended to be used for the program used to create the phenopacket - e.g. RD-CONNECT v 2.4 it is meant to be for auditing/ tracing the provenance of the phenopacket.
https://github.com/phenopackets/phenopacket-schema/blob/da69897c44b3299d8c27c277f3b1714644787a4a/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L11-L12

A ```submitted_by``` would really mean who the actual submitter of the data was.
