### ISSUE TITLE
created / updated

### ISSUE THREAD

**Issue by drseb** [phenopackets/phenopacket-schema#46]
Shouldn't it be possible to store multiple updates? If I look here https://phenopackets-schema.readthedocs.io/en/latest/individual.html#updated it seem that only one update is possible.

**Comment by julesjacobsen** [comment]
This could be changed to an array of timestamps. I originally intended for this to be overwritten with each update so only one was required. If you'd like a more complete history, sure.

**Comment by julesjacobsen** [comment]
@drseb How about we remove the created and updated fields from Individual and Biosample and add this a the level of the Phenopacket in the MetaData section?

**Comment by drseb** [comment]
> I originally intended for this to be overwritten with each update so only one was required.

Then it should be just relabelled to "lastupdated", right?

I don't really need a complete history. But maybe others need it. Then an array would be good - independent where it is located (Individual or Metadata)
