### ISSUE TITLE
Cohort?

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#5]
We had one before, we cold have one again.

Could be defined as an aggregated individual:

```proto
message Cohort {
  string id = 1;
  string description = 2;
  int size = 3;
  repeated Phenotype phenotypes = 4;
  repeated Cohort sub_groups = 5;
}
```

or maybe an actual set of individuals:

```proto
message Cohort {
  string id = 1;
  string description = 2;
  int size = 3;
  repeated Individual members = 4
  repeated Phenotype phenotypes = 5;
  repeated Cohort sub_groups = 6;
}
```

or something else.

**Comment by pnrobinson** [comment]
@julesjacobsen In light of the last year's work, it seems we could more easily define a Cohort as
```
message Cohort {
  string id = 1;
  string description = 2;
  int size = 3;
  repeated PhenoPacket = 4;
}
```
Should we do so?

**Comment by cmungall** [comment]
What' the use case here? Surely there would need to be further information
associated with the cohort, e.g.
https://hl7.org/fhir/researchstudy-mappings.html

**Comment by pnrobinson** [comment]
Implemented with a few revisions and additions.
