### ISSUE TITLE
Add variant list to biosample

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#57]
These would represent somatic variants in a cancer sample, for instance @cmungall @mellybelly @julesjacobsen @mbaudis

**Comment by mbaudis** [comment]
+1 for variant list (lists are good, mostly); but not sure about the implicit "somatic"scope.

I'd rather suggest that for PXF you'd follow the model of declaring the sample as "reference" (i.e. representing the "normal" of the individual it belongs to - this could be the default & optional), in contrast to "aberrant" - this would delineate the sample as being divergent from the individual's baseline (neoplasia, inflammation ...).

We'd recently introduced the relevant concepts to EFO (may exist elsewhere - I'm following here the leads of others...). See the discussion for the [EFO issue](https://github.com/EBISPOT/efo/issues/365).

Also, example being part of my [comment](https://github.com/phenopackets/phenopacket-schema/issues/58#issuecomment-471710859) regarding #58.

----

(Btw.: This solves a lot of headaches when dealing with queries e.g. against cancer databases, where you have a mix of germline - e.g. inherited BRCA1mut? - versus somatic mutation profiling. If followed through, the "EFO_0009656" / "EFO_0009654" separation is extremely helpful.)

**Comment by julesjacobsen** [comment]
@mbaudis Are you suggesting two variant lists, or just a sample type flag on a ```Biosample``` message?

**Comment by mbaudis** [comment]
@julesjacobsen That depends on how you model the biosample relationships. The flag should be on the Biosample; variants inherit their provenance (reference/germline or aberrant) then from this.

If you represent multiple biosamples in a phenopacket, you have to provide a connection about which biosample the variants come from. This could be by having variant lists per biosample, or a single list and `biosample_id` or such. Or you generally represent variants as attributes of a biosample object.

**Comment by julesjacobsen** [comment]
@mbaudis OK - essentially we have this, but are in the process of refining things.
https://github.com/phenopackets/phenopacket-schema/blob/48f1096ca32809a692625b8b71c91e57d40b4efc/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L203

https://github.com/phenopackets/phenopacket-schema/blob/48f1096ca32809a692625b8b71c91e57d40b4efc/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L242

**Comment by mbaudis** [comment]
@julesjacobsen So the variants are covered (since attribute of `biosample`); but `type` should be expanded; maybe into a more general wrapper for different kinds of information representing the sample's origin?

**Comment by julesjacobsen** [comment]
@mbaudis we have decided to narrow down the scope of the ```Biosample.type``` and changed it to ```Biosample.sampled_tissue``` as this ought to be more self-explanatory.

https://github.com/phenopackets/phenopacket-schema/blob/696d4faeac5d99ad337a8801319f7b4ea125c7cf/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L200-L203

**Comment by mbaudis** [comment]
@julesjacobsen There is no strict need to have a sample declared as "abnormal" if the object model is followed through (i.e., the histology is declared with the biosample). That is also in line with the standard data model & we've always done it that way. The "abnormal" / "reference" ... labelling is mostly suitable for queries / databases, not for the proper modelling of the data.

**Comment by pnrobinson** [comment]
@mbaudis We are not declaring samples normal or abnormal anywhere -- unclear if you are agreeing or pointing out an issue?

**Comment by mbaudis** [comment]
@pnrobinson Not sure myself; see above - try to rephrase:
* for biosamples, an indication about their respective "state" respective to the individual's "normal" can be made:
>  EFO:0009654 reference sample
> Subclass of material sample (OBI_0000747)
> Definition: A material sample derived from cells or tissue representing a physiologically or phenotypically normal state.
> Synonyms: germline reference sample||inherited reference sample||baseline reference sample||non-neoplastic sample||native sample
* this is highly relevant for many use cases (cancer, treatment response, inflammation...); a typical use case here could be a phenopacket containing samples both for the germline and tumor tissue of an individual
* in principle, one does not need a specific label for the normal <-> abnormal separation, since this can be inferred from other biosample attributes (e.g. histology)
* however, 
    - there are no terms for "normal" histologies/classifications in most(?) disease classifications
    - assertion of a "normal" state would be based on the lack of any classification saying otherwise, which isn't robust
    - data analyses (and annotation checks) can become very efficient with such a normal <-> abnormal flag

Now, these issues may not be relevant when using properly formatted phenopackets with complete information, for data transfer etc.; this labelling becomes much more relevant in data de-normalisation/database/query scenarios. In that respect I cannot answer if it is an "issue" - "no" for a minimal data model; "yes" for potential use cases.

**Comment by pnrobinson** [comment]
@mbaudis  @julesjacobsen 
So I am trying to rephrase -- you are suggesting that we add a flag such as this to the biosample
```proto
// if true, this sample is being use as a normal control, often in combination with
// another sample that is thought to contain a pathological finding
// the default value is false
bool control_sample = 42;
```

**Comment by pnrobinson** [comment]
implemented, please reopen if needed!
