### ISSUE TITLE
Add surgical procedure type for biosample

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#58]
For instance, prostatocystectomy is used to remove bladder cancer, and a biopsy is taken from the resulting specimen. On the other hand, a smaller biopsy could be taken by cystsocopy.
There are NCI thesaurus terms to represent these procedures. 

@cmungall @mellybelly @julesjacobsen @mbaudis @drseb

**Comment by mbaudis** [comment]
@pnrobinson Very good point for improvement. We're playing around with designing a first level `provenance` attribute, where this could be part of, as an optional named object. Example here, using EFO:

```
"provenance" : {
  "material" : {
    "description" : "normal kidney",
    "type" : {
      "id" : "EFO:0009654",
      "label" : "reference sample"
    }
  },
  "collection_process" : {
    "description" : "percutaneous needle biopsy from left kidney",
    "type" : {
      "id" : "EFO:0009293",
      "label" : "percutaneous kidney biopsy"
    }
  },
  "geo" : {
    "label" : "New York City, United States",
    "precision" : "city",
    "city" : "New York City",
    "country" : "United States",
    "latitude" : 40.71,
    "longitude" : -74.01
  }
}
```

The example doesn't include a time component etc. Also, looking at EFO, there are __gaps__ to fill... 

Only first ideas here; so please comment!

**Comment by mbaudis** [comment]
(The `collection_process` was written _ad hoc_, based on Peter's creation of the issue. Other instantiations & examples encouraged!)

**Comment by julesjacobsen** [comment]
@mbaudis where are you discussing the provenance attribute? Are you referring to [this issue](https://github.com/ga4gh-metadata/SchemaBlocks/issues/7) if so, could you or @mcourtot add the information in the Google doc to the issue, or open up the Google doc.

**Comment by julesjacobsen** [comment]
Commenting on the ```collection_process```

```json
  "collection_process" : {
    "description" : "percutaneous needle biopsy from left kidney",
    "type" : {
      "id" : "EFO:0009293",
      "label" : "percutaneous kidney biopsy"
    }
  }
```

The 'left' is getting lost in a comment. This is likely important, so ought there not be a ```laterality``` field in there? Or perhaps relative location, to take into account front/back, medial/lateral.

**Comment by mbaudis** [comment]
@julesjacobsen I used `provenance` here in a physical sense (a.k.a. "sample origin"); this is just meant as an example - @mcoutot 's issue is about evidence modelling.
Re. kidney example: Yes, that is intentional - I actually did put in the "left" for making a case about incomplete ontologies ... See note about "gaps".
(IMO the "left" could be expressed by having a subclass.)

**Comment by julesjacobsen** [comment]
@pnrobinson surgical procedure sounds like it ought to be a message in its own right.

**Comment by julesjacobsen** [comment]
https://github.com/phenopackets/phenopacket-schema/blob/696d4faeac5d99ad337a8801319f7b4ea125c7cf/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L261-L275

**Comment by julesjacobsen** [comment]
Might want to add some docs about the preferred ontologies for each field?

**Comment by mbaudis** [comment]
@julesjacobsen @pnrobinson So my example would translate to:

```
"collection_process" : {
  "description" : "percutaneous needle biopsy from left kidney",
  "procedure" : {
    "code" : {
      "id" : "EFO:0009293",
      "label" : "percutaneous kidney biopsy"
    },
    "body_site" : {
      "id" : "UBERON:0004538",
      "label" : "left kidney"
    },
  }
}
```

Looks good to me...

**Comment by julesjacobsen** [comment]
Cool
