### ISSUE TITLE
Primary, Met, Recurrence 	

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#60]
Check NCIT terms and document

**Comment by julesjacobsen** [comment]
https://github.com/phenopackets/phenopacket-schema/blob/069faedba9c154c237e3999a7e1ab9d84ade9e45/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L252-L254

Not sure how many terms we need to add:

```proto
    // Is the specimen tissue from the primary tumor, a metastasis or a recurrence?
    // Most likely a child term of NCIT:C7062 (Neoplasm by Special Category)
    // NCIT:C3677 (Benign Neoplasm)
    // NCIT:C84509 (Primary Malignant Neoplasm)
    // NCIT:C95606 (Second Primary Malignant Neoplasm)
    // NCIT:C3261 (Metastatic Neoplasm)
    // NCIT:C4813 (Recurrent Malignant Neoplasm)
    OntologyClass tumor_progression = 18;
```

**Comment by pnrobinson** [comment]
we will recommend the NCIT terms -- 
Primary, metastasis,recurrence Is the specimen tissue from the primary tumor, a metastasis or a recurrance For now, we are using PDXNet entities, but we should use the NCIT terms for these items. This would allow users to enter a more specific NCIT term such as Distant metastasis (C18206), which is a child of Metastasis (C19151)

**Comment by cmungall** [comment]
What if we want to record both recurrent and metastatic? The tumor_progression field is single valued.

Is the intent to only use a restricted subset of these classes, and not to combine the tumor type with the progression? E.g. "recurrent breast carcinoma" http://purl.obolibrary.org/obo/NCIT_C7771 would be prohibited, instead this would be composed from "recurrent neoplasm" in the progression field plus "breast carcinoma" in the disease or phenotype fields.

I recommend formally defining value sets for each of these fields (not sure if there is a way to specify this at the protobuf level, other than reifying as an enum in the schema).

It seems there a lot of ways to capture the actual cancer, this could potentially be confusing.

 * phenopacket.disease.class (using NCIT or MONDO)
 * individual.phenotype.class (using an HPO class)
 * biosample.phenotype.class (using an HPO class)
 * biosample.histological_diagnosis 
 * biosample.tumor_progression (as a subclass of the progression class, e.g recurrent breast carcinoma http://purl.obolibrary.org/obo/NCIT_C7771)

This gets more complex as we consider different use cases - e.g. a disease of hereditary polyposis syndrome with a phenotype of colerectal cancer that is both recurrent and has spread to lymph nodes.

I think it's a fundamental law of file formats or data models that if you give people more than one way to say the same thing, they WILL find that way and use it, even if to the designer it seems "obvious" not to do it that way.

**Comment by pnrobinson** [comment]
This was a recommendation by the PDX oncology teams and I think the field is used in a predefined way. I will ask Steve to help us either define this better of figure out how we should improve the item.

**Comment by julesjacobsen** [comment]
@pnrobinson is this issue resolved? It's not clear if it is or not. Most cancer folks appear to be positive about what we have and I think you've been more specific about the required terms/child terms in the (docs)[https://phenopackets-schema.readthedocs.io/en/latest/biosample.html#histological-diagnosis].
