### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#62]
- [ ] Add documentation about how to use a Python library to read a phenopacket.

**Comment by pnrobinson** [comment]
@cmungall  Any chance you or some Pythonista in your group can provide code for this?  We have now gotten the C++ build to work (https://github.com/phenopackets/phenopacket-schema/pull/152). The Python code is now also at the top level and so should be easier to use. My Python arts are not yet advanced enough to progress quickly, but with a little head start I could finished. For instance, the first but not the second line works (if the generated Python files are in the same directory)...
```
from phenopackets_pb2 import Phenopacket
phenopacket = phenopackets_pb2.Phenopacket()
```

**Comment by pnrobinson** [comment]
Kent:
```
export PYTHONPATH=.:$PYTHONPATH
virtualenv -p /usr/bin/python3.6 venv
pip install google
https://stackoverflow.com/questions/36183486/importerror-no-module-named-google
pip install --upgrade google-api-python-client
pip install protobuf
cp /home/kshefchek/test-git/phenopacket-schema/target/generated-sources/protobuf/python/* venv/lib/python3.6/site-packages/
import base_pb2 as pb2
```

**Comment by pnrobinson** [comment]
I am trying to implement a Python example that will be similar to the C++ example, but cannot seem to input the JSON file.
See: https://github.com/pnrobinson/phenopacketpp/tree/master/python3
(the README explains how I set things up). I copied the two generated python files into the directory and did not change anything else.

Because of example 4 here, I think my code should work
https://www.programcreek.com/python/example/88496/google.protobuf.json_format.Parse
but I get this:

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    json_format.Parse(json_string,phenopacket)
  File "/home/robinp/.conda/envs/p3/lib/python3.7/site-packages/google/protobuf/json_format.py", line 397, in Parse
    if not isinstance(text, six.text_type): text = text.decode('utf-8')
AttributeError: 'dict' object has no attribute 'decode'
```

**Comment by julesjacobsen** [comment]
@pnrobinson I think this is resolved in the cpp_layout branch https://github.com/phenopackets/phenopacket-schema/blob/cpp_layout/src/test/python/phenopacket_test.py

**Comment by julesjacobsen** [comment]
This is now here: https://github.com/phenopackets/phenopacket-schema/blob/master/src/test/python/phenopacket_test.py

Was confirmed as 'just fine' by Davide.
