### ISSUE TITLE
Consider changes to Phenopacket

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#63]
- [ ] Remove the ``individuals``
- [ ] put the Individual (subject) phenotypes at the phenopacket level
- [ ] The entire description of families for Mendelian diagnostics case is done via the ``pedigree``
- [ ] This would go hand in hand with the proposed changes in ``Cohort`` #5 in which multiple individuals would be represented by ``repeated phenopacket``

**Comment by drseb** [comment]
not sure I understand the proposed changes.

I think we will for now implement solve-rd specific solutions via different mechanism until it is clearer how design decision are being made and the whole schema is more settled. until then we will stick with an older version (+different workarounds), so the changes here should not affect this project.

**Comment by julesjacobsen** [comment]
Cool, so we'll chop and change.

**Comment by julesjacobsen** [comment]
So in short, a Phenopacket should be a phenotypic description of an individual. Cases requiring more than one individual to be bundled together, e.g. a Mendelian diagnosis  or a cohort should build upon the Phenopacket message.
