### ISSUE TITLE
Create new maven release for partner review 

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#69]

**Comment by julesjacobsen** [comment]
@pnrobinson I think I've put this off for long enough now. Do you have any blockers not on the issue tracker preventing this?

**Comment by pnrobinson** [comment]
@julesjacobsen  make it so!

**Comment by julesjacobsen** [comment]
@pnrobinson Will hold until issues #107 and #110 are resolved

**Comment by julesjacobsen** [comment]
https://github.com/phenopackets/phenopacket-schema/releases/tag/v0.4.0
