### ISSUE TITLE
Use case example: Rare disease case report

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#72]
@mellybelly I would like to invite Pablo and Gert and Richard to talk about a use case example of how we will use phenopackets for publications.

**Comment by pnrobinson** [comment]
- [ ] Mail sent to SOLVE-RD/Phenotips groups
- [ ] Mail sent to Pablo
- [ ] Mail sent to Gert
- [ ] Mail sent to Richard

**Comment by julesjacobsen** [comment]
@pnrobinson Where did you get the example case for the Toronto example from? Was this not sufficient?

**Comment by pnrobinson** [comment]
What do you mean by Toronto example?

**Comment by julesjacobsen** [comment]
The one you and Ada produced

https://github.com/phenopackets/phenopacket-schema/blob/master/src/test/resources/toronto_rare_disease_example.md

and 

https://github.com/phenopackets/phenopacket-schema/blob/master/src/test/java/org/phenopackets/schema/v1/examples/RareDiseaseFamilyExample.java

**Comment by pnrobinson** [comment]
I had forgotten about this example. It is from https://www.nature.com/articles/nrg2783. I would propose that we add it as an example of the Family message (the spherocytosis example is an unadorned Phenopacket). I will work on this during this week.

**Comment by ielis** [comment]
This would also fit well into the validator software as an example. I have been using just some *"stubs"* in the validator.

**Comment by pnrobinson** [comment]
now sufficiently worked out
