### ISSUE TITLE
delete the many archived subling repositories

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#77]
The uber-repository contains many out of date/obsolete repositories. It would be good to delete them or not show them, because it will be very confusing to visitors. Maybe we can broadcast the fast that we will delete these old repositories and do so 2 weeks later

**Comment by julesjacobsen** [comment]
The less nuclear option would be to add a warning about when this will happen and just make them private.

**Comment by cmungall** [comment]
and/or rename repo affixing -LEGACY to the end or somesuch

**Comment by pnrobinson** [comment]
Are there any active users that would appreciate this? I would suggest that reducing clutter is more important than retaining files for future ontology historians :-0

**Comment by pnrobinson** [comment]
@julesjacobsen @cmungall Can we delete the obsolete repositories? AFAIK there are no users and I think it is confusing to see all of that. Also, we will probably want to move the two active repositories to GA4GH -- could we delete the other repo's at that time?

**Comment by pnrobinson** [comment]
@julesjacobsen @cmungall  I still think we should archive/delete the obsolete repositories -- but the world did not come to an end between this comment and the previous one either. Could we either close this issue or delete the repos? :-0

**Comment by pnrobinson** [comment]
@julesjacobsen as we move towards the v2 release, we should rename the old repositories "-LEGACY" and archive them.

**Comment by julesjacobsen** [comment]
These are all archived. There are some newer ones like [operations](https://github.com/phenopackets/operations) and [domain-analysis](https://github.com/phenopackets/domain-analysis) which look abandoned.
