### ISSUE TITLE
setup phenopackets mailing list

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#78]
We should have a mailing list to announce changes for users of the schema. Probably a google groups is the easiest way to go?

**Comment by LCCarmody** [comment]
who is the prospective audience?

**Comment by pnrobinson** [comment]
Probably mainly developers who write code that uses phenopackets, and a few other geeky individuals.

**Comment by nicolevasilevsky** [comment]
google groups works for me

**Comment by monicacecilia** [comment]
Google groups will probably work well. 

Some suggestions from my experience:
- Be sure to advertise to your user base and all potentially interested, that you will have a new mailing list. For example, monarch-internal, GA4GH lists, etc. Is there a phenopackets twitter? 😉 
- Also add a link to instruct users on how to join the mailing list on your site (does phenopackets have a site?), ReadMe on the repo, and on documentation pages.
- You will have to make a decision on whether to moderate or not the incoming messages; be sure to assign someone as moderator from the beginning if you do.

**Comment by cmungall** [comment]
oh yes very good point about the moderation. I prefer to moderate incoming
users rather than messages. I think it is good to force people to add a
sentence about why they want to join to avoid spammers.

**Comment by julesjacobsen** [comment]
We have one! phenopackets@groups.io (thank-you @drseb)
