### ISSUE TITLE
metadata question

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#84]
How should we link out to OMIM (do we need to modify the MetaData/Resource element?)
https://github.com/monarch-initiative/HpoCaseAnnotator/issues/42

**Comment by julesjacobsen** [comment]
I think the best one can do is give it a curie prefix of OMIM and then the url = 'https://omim.org'

``` java
Resource.newBuilder()
                    .setId("omim")
                    .setName("Online Mendelian Inheritance in Man")
                    .setNamespacePrefix("OMIM")
                    .setUrl("https://omim.org")
                    .setVersion("01-04-2019")
                    .build()
```

**Comment by julesjacobsen** [comment]
@pnrobinson can you close this if you're happy (with the response!).

**Comment by pnrobinson** [comment]
seems fine, thanks!
