### ISSUE TITLE
diseases in the murine example

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#88]
```
"diseases": [],
(...)
"genes": [],
```
We are describing a mouse model of the human disease Marfan syndrome. In theory, we could use these fields to enter this information, but that would mean that we are using the fields with a different semantics for mouse and human, which would probably result in errors.

For the human example, ``genes`` is used in the MatchMaker exchange situation to say, "we think that a mutation in this gene is responsible but for privacy reasons we are not revealing the variant", and diseases means "we made these diagnoses". In the mouse example, we have genetically altered the gene and the mouse may or may not be a good model of some disease associated with the orthologue in humans.

@mellybelly @cmungall @drseb @julesjacobsen  I would propose that we leave these fields empty in the mouse example and provide this explanation on the read the docs page. Thoughts?

**Comment by julesjacobsen** [comment]
This is no longer the case:

https://phenopackets-schema.readthedocs.io/en/latest/animal-model-example.html
