### ISSUE TITLE
Noting requirements in the documentation

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#89]
Given that in protobuf everything is optional, we should decide on a standardized way to declare that we think that certain fields are actually required for a Phenopacket. Perhaps each page of the read the docs "building blocks" should have a table with requirements that looks the same on each page?
@julesjacobsen @ielis
I am going to make one for the variants page with this information: 

For the Phenopacket standard,
the ``allele`` element is required, the ``genotype`` element is recommended but not required 
(if the information in unknown),
and the ``background`` element is optional.

**Comment by pnrobinson** [comment]
@cmungall @mellybelly @julesjacobsen @ielis
I would like to suggest that we have three categories for the fields of the Phenopacket
- required
- recommended
-optional

We can then construct the PhenoPacket Validator to 
- throw en error if a required element is not present
- optionally throw a warning if a recommended element is not present
- do nothing if an optional element is present or not present.

I have created tables on the Read The Docs pages for the (new) variant and OntologyClass pages. See
https://github.com/phenopackets/phenopacket-schema/pull/90

If we all like this I will format each of the Read The Doc pages in this way and Daniel can use this as a guide for writing the Validator code.

**Comment by mellybelly** [comment]
I like idea of required, recommended, optional @pnrobinson.
That said, should we just use the same nomenclature as W3C? 
 **must, must not, required, should, should not, recommended, may, optional**
?? https://www.ietf.org/rfc/rfc2119.txt

**Comment by pnrobinson** [comment]
@mellybelly  I think we already are, and actually many of these words are regarded as synonyms by W3C.

**Comment by mellybelly** [comment]
Can we make it explicit? there are many people who expect this type of verbiage for a standard such as this

**Comment by pnrobinson** [comment]
I see what you mean. I will add a separate page to the Read the docs that will be analogous to the page you sent -- sound good?

**Comment by mellybelly** [comment]
+1!

**Comment by pnrobinson** [comment]
see https://github.com/phenopackets/phenopacket-schema/pull/92

**Comment by pnrobinson** [comment]
I have created a page for this.
