### ISSUE TITLE
Links between pages

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#91]
@ielis @julesjacobsen I am having some difficulties getting links between individual RST pages to work. I you could spare some guru time to relieve me of my ignorance that would be great. I did try to implement what the RTFM says but must be making some dumb mistake.

**Comment by ielis** [comment]
Regarding RST I am a complete greenhorn :(

**Comment by pnrobinson** [comment]
Possibly the issue (which is not documented well at RTD) is that anchor names are not allowed to contain an underslash. For instance this is ok
```
.. _rstpedigree:
```
but this is not:
```
.. _rst_pedigree:
```

In order to refer to the first anchor on another page, we use 
```
:ref:`Pedigree element<rstpedigree>`
```
Note that here we do not use the initial underslash and we are using a display name.

**Comment by julesjacobsen** [comment]
Sorry, I'm an RST neophyte too. Looks like you've solved the issue?

**Comment by pnrobinson** [comment]
Yes, the above was the trick and things are working now!
