### ISSUE TITLE
AnVIL metadata

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#97]
As mentioned by Heidi Rehm during her [talk](https://drive.google.com/file/d/1EVc1aOKS1OrM0tgRcxDKOHwzqpNPAhuF/view) at the recent Genomics of Rare Disease Conference, the [AnVIL](http://anvilproject.org/) project is discussing a data model. How do we stack up to their requirements?

<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">Enjoying the Genomics of Rare Disease Meeting in Hinxton. For those who asked for my slides on Global Data Sharing, I&#39;ve posted them on a shared Google link: <a href="https://t.co/LMiSakwGLC">https://t.co/LMiSakwGLC</a></p>&mdash; Heidi Rehm (@HeidiRehm) <a href="https://twitter.com/HeidiRehm/status/1111581531850661888?ref_src=twsrc%5Etfw">29 March 2019</a></blockquote>

ANVIL Possible Metadata to Include for Rare Disease Cases
===

Demographic
====
Project ID
Family ID/Individual ID/Paternal ID/Maternal ID
PED file (relationships, affected status)
Sex
Ancestry
Consanguinity
Prior testing info (panel, WES, etc)
Other Available Datasets (RNAseq, etc)

Phenotype Data
====
Affected Status
Core Phenotype (OMIM, HPO)
HPO Terms (present)
HPO Terms (absent)
Family history
Age of onset
Descriptive phenotype synopsis

Case Status and Included Genes/Variants
====
Solved state (Solved, Tier 1 Candidate, Tier 2 Candidate)
Known/Published Gene Name and Variant
Tier 1 Candidate Gene Name and Variant
Tier 2 Candidate Gene Name and Variant

Flagged Variants - repeated if >1 variant
====
Chrom/Pos/Ref/Alt
Gene/Transcript/hgvsc/hgvsp
Zygosity
Clinical significance (Pathogenic, LP, VUS, Other)
Data Source
Data type (WES/WGS/Array/RNAseq)
Method details (WES capture, PCR-free WGS, etc)
Date of data generation
Tissue type

**Comment by pnrobinson** [comment]
@julesjacobsen  Interesting -- I will send Heidi a mail and see if we can collaborate

**Comment by julesjacobsen** [comment]
Yes, unfortunately I didn't manage to talk to her about this.

@pnrobinson @mbrush  note use of ```zygosity``` in the flagged variants section. Relevant to #90

**Comment by mellybelly** [comment]
some info relating to the ANVIL model, which is currently deriving from GDC, is here: https://docs.google.com/spreadsheets/d/1edxXULuJM5iHeL_mA4H21pgXmsbF08EsL1mUcNjbwZk/edit#gid=180970461

**Comment by pnrobinson** [comment]
@mellybelly I think the scope of ANVIL is not the same although there are overlaps. Do we have a concrete action item?

**Comment by pnrobinson** [comment]
@julesjacobsen @mellybelly I think the phenopackets cover all of these elements. I do not see an action item, can we close?

**Comment by julesjacobsen** [comment]
I think we can close.
